/**
 * Global hockey federations reference table — complete IIHF membership.
 *
 * Source: Wikipedia "List of members of the IIHF" + IIHF.com association pages +
 * federation own websites. Covers all 84 IIHF member + associate national
 * associations (as of 2025).
 *
 * ⚠️  29 established nations have verified federation-specific required-doc lists.
 *    55 emerging/associate members use a standard 5-doc baseline template —
 *    sourced from general IIHF standards. Verify with your local federation.
 *
 * Doc kinds (team_documents.kind): birth_cert | transfer | insurance | safeguarding |
 *   medical_release | registration | code_of_conduct | photo_id | injury_waiver
 */

export interface FederationDoc {
  kind: string;
  label: string;
  note?: string;
}

export interface Federation {
  countryCode: string;
  countryName: string;
  federationName: string;
  federationUrl: string;
  governingBody: string;
  safeguardingBody: string;
  safeguardingUrl?: string;
  requiredDocKinds: FederationDoc[];
  ageGroupNote: string;
}

export const FEDERATIONS: Federation[] = [
  {
    countryCode: 'AD',
    countryName: 'Andorra',
    federationName: 'Andorran Federation of Ice Sports',
    federationUrl: 'https://www.iihf.com/en/associations/310/andorra',
    governingBody: 'IIHF',
    safeguardingBody: 'Andorra Ministry of Sports',
    safeguardingUrl: 'https://www.iihf.com/en/associations/310/andorra',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'Emerging hockey nation; IIHF associate member.',
  },
  {
    countryCode: 'AE',
    countryName: 'United Arab Emirates',
    federationName: 'UAE Ice Sports Federation',
    federationUrl: 'https://www.iihf.com/en/associations/375/united-arab-emirates',
    governingBody: 'IIHF',
    safeguardingBody: 'UAE National Olympic Committee',
    safeguardingUrl: 'https://www.iihf.com/en/associations/375/united-arab-emirates',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'Emerging hockey nation; IIHF member since 1989.',
  },
  {
    countryCode: 'AM',
    countryName: 'Armenia',
    federationName: 'Ice Hockey Federation of Armenia',
    federationUrl: 'https://www.iihf.com/en/associations/318/armenia',
    governingBody: 'IIHF',
    safeguardingBody: 'Armenian Ministry of Sports',
    safeguardingUrl: 'https://www.iihf.com/en/associations/318/armenia',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'Emerging hockey nation; IIHF member since 1993.',
  },
  {
    countryCode: 'AR',
    countryName: 'Argentina',
    federationName: 'Argentine Association of Ice and In-Line Hockey',
    federationUrl: 'https://www.iihf.com/en/associations/312/argentina',
    governingBody: 'IIHF',
    safeguardingBody: 'Argentine Ministry of Sports',
    safeguardingUrl: 'https://www.iihf.com/en/associations/312/argentina',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'IIHF associate member.',
  },
  {
    countryCode: 'AT',
    countryName: 'Austria',
    federationName: 'ÖEHV — Österreichischer Eishockeyverband',
    federationUrl: 'https://www.oehv.at',
    governingBody: 'ÖEHV',
    safeguardingBody: 'ÖEHV Child Protection',
    safeguardingUrl: 'https://www.oehv.at',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for ÖEHV player registration' },
      { kind: 'registration', label: 'ÖEHV Player Registration', note: 'Annual; via Austrian hockey portal' },
      { kind: 'insurance', label: 'Austrian Ice Hockey Insurance', note: 'Mandatory; ÖEHV accident + liability coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct', note: 'Required; Austrian Sports Federation guidelines' },
      { kind: 'medical_release', label: 'Medical Fitness Certificate', note: 'Physician-signed' },
    ],
    ageGroupNote: "Austrian Eishockey-Liga (EBEL) is top men's league. Youth: U20/U18/U16/U14/U12.",
  },
  {
    countryCode: 'AU',
    countryName: 'Australia',
    federationName: 'Ice Hockey Australia',
    federationUrl: 'https://www.icehockeyaustralia.com',
    governingBody: 'Ice Hockey Australia',
    safeguardingBody: 'IHA Child Protection',
    safeguardingUrl: 'https://www.icehockeyaustralia.com',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for IHA player registration' },
      { kind: 'registration', label: 'IHA Player Registration', note: 'Annual; via IHA portal or state association' },
      { kind: 'insurance', label: 'Australian Ice Hockey Insurance (Marsh/Club Links)', note: 'Mandatory personal accident + public liability; included in registration' },
      { kind: 'code_of_conduct', label: 'Code of Conduct', note: 'Required; IHA and state association guidelines' },
      { kind: 'safeguarding', label: 'Working with Children Check', note: 'Required for coaches, officials, volunteers working with children (state-specific)' },
      { kind: 'medical_release', label: 'Medical Information Form', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'AIHL is top senior league. Youth: U18/U16/U14/U12.',
  },
  {
    countryCode: 'AZ',
    countryName: 'Azerbaijan',
    federationName: 'Ice Hockey Federation of Azerbaijan',
    federationUrl: 'https://www.iihf.com/en/associations/319/azerbaijan',
    governingBody: 'IIHF',
    safeguardingBody: 'Azerbaijan Ministry of Youth and Sports',
    safeguardingUrl: 'https://www.iihf.com/en/associations/319/azerbaijan',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'Emerging hockey nation; IIHF member since 1993.',
  },
  {
    countryCode: 'BA',
    countryName: 'Bosnia and Herzegovina',
    federationName: 'Bosnia and Herzegovina Ice Hockey Federation',
    federationUrl: 'https://www.iihf.com/en/associations/323/bosnia-and-herzegovina',
    governingBody: 'IIHF',
    safeguardingBody: 'Bosnia and Herzegovina Ministry',
    safeguardingUrl: 'https://www.iihf.com/en/associations/323/bosnia-and-herzegovina',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'Emerging hockey nation; IIHF member since 2001.',
  },
  {
    countryCode: 'BE',
    countryName: 'Belgium',
    federationName: 'Royal Belgian Ice Hockey Federation',
    federationUrl: 'https://www.belgianicehockey.be',
    governingBody: 'Royal Belgian Ice Hockey Federation',
    safeguardingBody: 'Belgian Ice Hockey Child Protection',
    safeguardingUrl: 'https://www.belgianicehockey.be',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for Belgian Ice Hockey Federation license' },
      { kind: 'registration', label: 'Belgian Ice Hockey License', note: 'Annual; via Belgian Ice Hockey Federation' },
      { kind: 'insurance', label: 'Belgian Ice Hockey Insurance', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct', note: 'Required; Belgian Sports Ministry guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration Form', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'Belgian Ice Hockey League is top national competition.',
  },
  {
    countryCode: 'BG',
    countryName: 'Bulgaria',
    federationName: 'Bulgarian Ice Hockey Federation',
    federationUrl: 'https://www.iihf.com/en/associations/324/bulgaria',
    governingBody: 'IIHF',
    safeguardingBody: 'Bulgarian Ministry of Youth and Sports',
    safeguardingUrl: 'https://www.iihf.com/en/associations/324/bulgaria',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'Emerging hockey nation; IIHF member since 1985.',
  },
  {
    countryCode: 'BH',
    countryName: 'Bahrain',
    federationName: 'Bahrain Hockey Committee',
    federationUrl: 'https://www.iihf.com/en/associations/314/bahrain',
    governingBody: 'IIHF',
    safeguardingBody: 'Bahrain Ministry of Sports',
    safeguardingUrl: 'https://www.iihf.com/en/associations/314/bahrain',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'IIHF associate member. Newest IIHF member (joined 2024).',
  },
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    federationName: 'Brazilian Ice Sports Federation',
    federationUrl: 'https://www.iihf.com/en/associations/325/brazil',
    governingBody: 'IIHF',
    safeguardingBody: 'Brazilian Ministry of Sports',
    safeguardingUrl: 'https://www.iihf.com/en/associations/325/brazil',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'IIHF associate member. Multiple rinks in São Paulo.',
  },
  {
    countryCode: 'BY',
    countryName: 'Belarus',
    federationName: 'Belarusian Ice Hockey Association',
    federationUrl: 'https://www.iihf.com/en/associations/322/belarus',
    governingBody: 'Belarusian Ice Hockey Association',
    safeguardingBody: 'Belarusian Ice Hockey Association Child Protection',
    safeguardingUrl: 'https://www.iihf.com/en/associations/322/belarus',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: "Extraleague is top men's league. Youth: U20/U18/U16.",
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    federationName: 'Hockey Canada',
    federationUrl: 'https://www.hockeycanada.ca',
    governingBody: 'Hockey Canada',
    safeguardingBody: 'Hockey Canada Safety Program',
    safeguardingUrl: 'https://www.hockeycanada.ca/en-ca/safety',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Proof of Age', note: 'Government-issued; required for all participants' },
      { kind: 'registration', label: 'Hockey Canada Registration', note: 'Annual; via your provincial hockey association' },
      { kind: 'insurance', label: 'Hockey Canada Insurance Confirmation', note: 'Included with registration; accident coverage mandatory' },
      { kind: 'code_of_conduct', label: 'Hockey Canada Code of Conduct', note: 'Respect in Sport required for coaches/volunteers' },
      { kind: 'safeguarding', label: 'Criminal Record Check / Vulnerable Sector Check', note: 'Required for coaches, bench staff, volunteers working with minors' },
      { kind: 'medical_release', label: 'Medical Information Form', note: 'Emergency contacts, allergies, conditions; updated annually' },
    ],
    ageGroupNote: 'Hockey Canada categories: U21/U18/U15/U13/U11/U9/U7.',
  },
  {
    countryCode: 'CH',
    countryName: 'Switzerland',
    federationName: 'Swiss Ice Hockey (SIHF)',
    federationUrl: 'https://www.sihf.ch',
    governingBody: 'Swiss Ice Hockey',
    safeguardingBody: 'SIHF Child Protection Policy',
    safeguardingUrl: 'https://www.sihf.ch',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport / Residence Permit', note: 'Required for SIHF player license' },
      { kind: 'registration', label: 'SIHF Player License', note: 'Annual; via club and Verband registration' },
      { kind: 'insurance', label: 'Swiss Ice Hockey Insurance (SWICA/KPT)', note: 'Mandatory accident + liability; club-provided or individual' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; SIHF fair-play campaign' },
      { kind: 'medical_release', label: 'Medical Information Form', note: 'Disclosed conditions; Swiss sports medicine standards' },
    ],
    ageGroupNote: "Swiss NL is top men's league. Youth: U20/U17/U15/U13.",
  },
  {
    countryCode: 'CL',
    countryName: 'Chile',
    federationName: 'Chilean Ice and Inline Hockey Federation',
    federationUrl: 'https://www.iihf.com/en/associations/326/chile',
    governingBody: 'IIHF',
    safeguardingBody: 'Chilean Ministry of Sports',
    safeguardingUrl: 'https://www.iihf.com/en/associations/326/chile',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'IIHF associate member.',
  },
  {
    countryCode: 'CN',
    countryName: 'China',
    federationName: 'Chinese Ice Hockey Association',
    federationUrl: 'https://www.icehockeychina.cn',
    governingBody: 'Chinese Ice Hockey Association',
    safeguardingBody: 'General Administration of Sport of China',
    safeguardingUrl: 'https://www.iihf.com/en/associations/334/china',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'Developing nation; IIHF member since 1963.',
  },
  {
    countryCode: 'CO',
    countryName: 'Colombia',
    federationName: 'Colombian Ice Hockey Federation',
    federationUrl: 'https://www.iihf.com/en/associations/327/colombia',
    governingBody: 'IIHF',
    safeguardingBody: 'Colombian Ministry of Sports',
    safeguardingUrl: 'https://www.iihf.com/en/associations/327/colombia',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'IIHF associate member.',
  },
  {
    countryCode: 'CZ',
    countryName: 'Czech Republic',
    federationName: 'Czech Ice Hockey Association (Český hokej)',
    federationUrl: 'https://www.czechicehockey.cz',
    governingBody: 'Český hokej',
    safeguardingBody: 'Český hokej Child Protection',
    safeguardingUrl: 'https://www.czechicehockey.cz',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for ČSLH player registration' },
      { kind: 'registration', label: 'ČSLH Player Registration', note: 'Annual; via ČSLH register (IS ČSLH)' },
      { kind: 'insurance', label: 'Czech Ice Hockey Insurance', note: 'Mandatory; individual or club-provided' },
      { kind: 'code_of_conduct', label: 'Code of Conduct', note: 'ČSLH fair-play code; mandatory for all categories' },
      { kind: 'medical_release', label: 'Medical Fitness Certificate', note: 'Physician-signed; confirms fitness to play' },
    ],
    ageGroupNote: 'Extraliga juniorů (U20), dorost (U18), žáci (U14/U12).',
  },
  {
    countryCode: 'DE',
    countryName: 'Germany',
    federationName: 'Deutscher Eishockey-Bund (DEB)',
    federationUrl: 'https://www.deb-europe.de',
    governingBody: 'Deutscher Eishockey-Bund',
    safeguardingBody: 'DEB Child Protection',
    safeguardingUrl: 'https://www.deb-europe.de',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for DEB registration' },
      { kind: 'registration', label: 'DEB Spielerlizenz', note: 'Annual player license; via DEB portal or Landesverband' },
      { kind: 'insurance', label: 'German Ice Hockey Insurance (ARAG/DEB)', note: 'Mandatory personal accident + liability; included in license fee' },
      { kind: 'code_of_conduct', label: 'DEB Code of Conduct', note: 'Required; follows German Sports Confederation (DOSB) guidelines' },
      { kind: 'medical_release', label: 'Medical Fitness Certificate', note: 'Physician-signed; required for first-time registration' },
    ],
    ageGroupNote: "DEL is top men's league. Youth: DNL U20/U19, U17, U15.",
  },
  {
    countryCode: 'DK',
    countryName: 'Denmark',
    federationName: 'Danish Ice Hockey Union (DIU)',
    federationUrl: 'https://www.ishockey.dk',
    governingBody: 'Danish Ice Hockey Union',
    safeguardingBody: 'Danish Ice Hockey Union Child Protection',
    safeguardingUrl: 'https://www.ishockey.dk',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for DIU player registration' },
      { kind: 'registration', label: 'DIU Player Registration', note: 'Annual; via Danish hockey portal' },
      { kind: 'insurance', label: 'Danish Ice Hockey Insurance (Tryg/Alm. Brand)', note: 'Mandatory; club-provided or individual' },
      { kind: 'code_of_conduct', label: 'Code of Conduct', note: 'Required; DIU fair-play code' },
      { kind: 'medical_release', label: 'Medical Fitness Certificate', note: 'Physician-signed; confirms fitness to play' },
    ],
    ageGroupNote: "Metal Ligaen is top men's league. Youth: U20/U18/U16.",
  },
  {
    countryCode: 'DZ',
    countryName: 'Algeria',
    federationName: 'Hockey Algeria',
    federationUrl: 'https://www.iihf.com/en/associations/309/algeria',
    governingBody: 'IIHF',
    safeguardingBody: 'Algerian Ministry of Sports',
    safeguardingUrl: 'https://www.iihf.com/en/associations/309/algeria',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'IIHF associate member. North Africa.',
  },
  {
    countryCode: 'EE',
    countryName: 'Estonia',
    federationName: 'Estonian Ice Hockey Association',
    federationUrl: 'https://www.eestihoki.ee',
    governingBody: 'Eesti Hoki Liit',
    safeguardingBody: 'Estonian Ice Hockey Association Child Protection',
    safeguardingUrl: 'https://www.eestihoki.ee',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for Estonian Hockey Association registration' },
      { kind: 'registration', label: 'Eesti Hoki Liit Player License', note: 'Annual; via Estonian hockey portal' },
      { kind: 'insurance', label: 'Estonian Ice Hockey Insurance (ERGO)', note: 'Mandatory; individual or club-provided' },
      { kind: 'code_of_conduct', label: 'Code of Conduct', note: 'Required; Estonian Sports Federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: "Meistriliiga is top men's league.",
  },
  {
    countryCode: 'ES',
    countryName: 'Spain',
    federationName: 'RFEDH — Real Federación Española de Deportes de Hielo',
    federationUrl: 'https://www.rfedh.es',
    governingBody: 'Real Federación Española de Deportes de Hielo',
    safeguardingBody: 'RFEDH Child Protection',
    safeguardingUrl: 'https://www.rfedh.es',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport / DNI', note: 'Required for RFEDH sports license' },
      { kind: 'registration', label: 'RFEDH Sports License', note: 'Annual; via RFEDH portal' },
      { kind: 'insurance', label: 'Spanish Ice Hockey Insurance (Musacuer)', note: 'Mandatory; included in license fee' },
      { kind: 'code_of_conduct', label: 'Code of Conduct', note: 'Required; Spanish Sports High Council (CSD) guidelines' },
      { kind: 'medical_release', label: 'Medical Certificate', note: 'Physician-signed; required for competitive license' },
    ],
    ageGroupNote: "Liga Elite is top men's. Youth: Júnior U20, Juvenil U18, Cadete U16.",
  },
  {
    countryCode: 'FI',
    countryName: 'Finland',
    federationName: 'Suomen Jääkiekkoliitto',
    federationUrl: 'https://www.finhockey.fi',
    governingBody: 'Suomen Jääkiekkoliitto',
    safeguardingBody: 'Finnish Ice Hockey Association Child Protection',
    safeguardingUrl: 'https://www.finhockey.fi',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Passport or Birth Certificate', note: 'Required for Jääkiekkoliitto registration' },
      { kind: 'registration', label: 'Jääkiekkoliitto Player License', note: 'Annual; via club registration system' },
      { kind: 'insurance', label: 'Finnish Hockey Insurance (Tapiola/Lähitapiola)', note: 'Personal accident + team liability; mandatory' },
      { kind: 'code_of_conduct', label: 'Player Code of Conduct', note: 'Fair play; signed by player and parent for under-18s' },
      { kind: 'medical_release', label: 'Medical Information Form', note: 'Disclosed conditions; team physician review' },
    ],
    ageGroupNote: "Liiga is top men's. Youth: U20/U18/U16/U14/U12. Age cutoff Jan 1.",
  },
  {
    countryCode: 'FR',
    countryName: 'France',
    federationName: 'FFHG — Fédération Française de Hockey sur Glace',
    federationUrl: 'https://www.hockeyfrance.com',
    governingBody: 'Fédération Française de Hockey sur Glace',
    safeguardingBody: 'FFHG Child Protection',
    safeguardingUrl: 'https://www.hockeyfrance.com',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for FFHG player license' },
      { kind: 'registration', label: 'FFHG Player License', note: 'Annual; via FFHG portal or departmental committee' },
      { kind: 'insurance', label: 'French Hockey Insurance (MAIF/AXA)', note: 'Mandatory accident + civil liability; included in license' },
      { kind: 'code_of_conduct', label: 'Code of Conduct', note: 'Required; follows French Sports Ministry guidelines' },
      { kind: 'medical_release', label: 'Medical Certificate', note: 'Physician-signed; mandatory for competitive categories' },
    ],
    ageGroupNote: "Ligue A is top men's. Youth: U22/U18/U15/U12.",
  },
  {
    countryCode: 'GB',
    countryName: 'Great Britain',
    federationName: 'Ice Hockey UK',
    federationUrl: 'https://www.icehockeyuk.co.uk',
    governingBody: 'Ice Hockey UK',
    safeguardingBody: 'Ice Hockey UK Welfare & Safeguarding',
    safeguardingUrl: 'https://www.icehockeyuk.co.uk/welfare',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'UK-born players; passport for naturalised players' },
      { kind: 'registration', label: 'EIHA Registration', note: 'Annual; via English Ice Hockey Association portal' },
      { kind: 'insurance', label: 'British Ice Hockey Insurance', note: 'Mandatory public liability + personal accident' },
      { kind: 'code_of_conduct', label: 'Code of Conduct', note: 'All participants; UK Sport standards' },
      { kind: 'safeguarding', label: 'DBS Check (Enhanced)', note: 'Barred list check required for coaches/staff working with under-18s' },
      { kind: 'medical_release', label: 'Medical Declaration Form', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'EIHL is top. Youth: U20/U18/U16/U14/U12.',
  },
  {
    countryCode: 'GE',
    countryName: 'Georgia',
    federationName: 'Georgian Ice Hockey Federation',
    federationUrl: 'https://www.iihf.com/en/associations/352/georgia',
    governingBody: 'IIHF',
    safeguardingBody: 'Georgian Ministry of Sports',
    safeguardingUrl: 'https://www.iihf.com/en/associations/352/georgia',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'Emerging hockey nation; IIHF member since 1994.',
  },
  {
    countryCode: 'GR',
    countryName: 'Greece',
    federationName: 'Hellenic Winter Sports Federation',
    federationUrl: 'https://www.iihf.com/en/associations/353/greece',
    governingBody: 'IIHF',
    safeguardingBody: 'Hellenic Olympic Committee',
    safeguardingUrl: 'https://www.iihf.com/en/associations/353/greece',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'IIHF associate member. Limited program.',
  },
  {
    countryCode: 'HK',
    countryName: 'Hong Kong',
    federationName: 'Hong Kong Ice Hockey Association',
    federationUrl: 'https://hkciha.com/en',
    governingBody: 'IIHF',
    safeguardingBody: 'Hong Kong Sports Federation & Olympic Committee',
    safeguardingUrl: 'https://www.iihf.com/en/associations/353/hong-kong',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'Developing hockey nation; IIHF member since 1983.',
  },
  {
    countryCode: 'HR',
    countryName: 'Croatia',
    federationName: 'HSHL — Croatian Ice Hockey Association',
    federationUrl: 'https://www.hshl.hr',
    governingBody: 'Hrvatski Savez Hokeja na Ledu',
    safeguardingBody: 'HSHL Child Protection',
    safeguardingUrl: 'https://www.hshl.hr',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for Croatian Ice Hockey Association registration' },
      { kind: 'registration', label: 'HSHL Player Registration', note: 'Annual; via Croatian hockey portal' },
      { kind: 'insurance', label: 'Croatian Ice Hockey Insurance', note: 'Mandatory; club-provided or individual' },
      { kind: 'code_of_conduct', label: 'Code of Conduct', note: 'Required; Croatian Sports Federation guidelines' },
      { kind: 'medical_release', label: 'Medical Information Form', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'Croatian Ice Hockey League is national competition.',
  },
  {
    countryCode: 'HU',
    countryName: 'Hungary',
    federationName: 'Hungarian Ice Hockey Federation (MJSZ)',
    federationUrl: 'https://www.icehockey.hu',
    governingBody: 'Magyar Jégkorong Szövetség',
    safeguardingBody: 'MJSZ Child Protection',
    safeguardingUrl: 'https://www.icehockey.hu',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for Hungarian Ice Hockey Federation registration' },
      { kind: 'registration', label: 'MJSZ Player License', note: 'Annual; via Hungarian hockey portal' },
      { kind: 'insurance', label: 'Hungarian Ice Hockey Insurance (MÁV)', note: 'Mandatory; club-provided or individual' },
      { kind: 'code_of_conduct', label: 'Code of Conduct', note: 'Required; Hungarian Sports Federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'Austrian Hockey League (EBEL) includes Hungarian clubs.',
  },
  {
    countryCode: 'ID',
    countryName: 'Indonesia',
    federationName: 'Indonesia Ice Hockey Federation',
    federationUrl: 'https://www.iihf.com/en/associations/356/indonesia',
    governingBody: 'IIHF',
    safeguardingBody: 'Indonesia Ministry of Youth and Sports',
    safeguardingUrl: 'https://www.iihf.com/en/associations/356/indonesia',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'IIHF associate member. Development stage.',
  },
  {
    countryCode: 'IE',
    countryName: 'Ireland',
    federationName: 'Irish Ice Hockey Association',
    federationUrl: 'https://www.iihf.com/en/associations/355/ireland',
    governingBody: 'IIHF',
    safeguardingBody: 'Irish Sports Council',
    safeguardingUrl: 'https://www.iihf.com/en/associations/355/ireland',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'IIHF associate member.',
  },
  {
    countryCode: 'IL',
    countryName: 'Israel',
    federationName: 'Israel Ice Hockey Federation',
    federationUrl: 'https://israelhockey.org',
    governingBody: 'IIHF',
    safeguardingBody: 'Israel Ice Hockey Federation Child Protection',
    safeguardingUrl: 'https://www.iihf.com/en/associations/354/israel',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'Developing nation; IIHF member since 1991.',
  },
  {
    countryCode: 'IN',
    countryName: 'India',
    federationName: 'Ice Hockey Association of India',
    federationUrl: 'https://www.iihf.com/en/associations/351/india',
    governingBody: 'IIHF',
    safeguardingBody: 'Ice Hockey Association of India',
    safeguardingUrl: 'https://www.iihf.com/en/associations/351/india',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'Emerging nation; IIHF member since 1989.',
  },
  {
    countryCode: 'IR',
    countryName: 'Iran',
    federationName: 'Ice Hockey Association of the Islamic Republic of Iran',
    federationUrl: 'https://iranicehockey.com/en',
    governingBody: 'Ice Hockey Association of Iran',
    safeguardingBody: 'Iran Ministry of Sports',
    safeguardingUrl: 'https://www.iihf.com/en/associations/14688/iran',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'IIHF full member since 2019.',
  },
  {
    countryCode: 'IS',
    countryName: 'Iceland',
    federationName: 'Ice Hockey Iceland (ÍHÍ)',
    federationUrl: 'https://www.ihi.is/en',
    governingBody: 'Íshokkísamband Íslands (ÍHÍ)',
    safeguardingBody: 'Icelandic Sports Federation',
    safeguardingUrl: 'https://www.ihi.is/en',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'Icelandic Hockey League (IHL) is top competition. IIHF member since 1989.',
  },
  {
    countryCode: 'IT',
    countryName: 'Italy',
    federationName: 'FISG — Federazione Italiana Sport del Ghiaccio',
    federationUrl: 'https://www.federghiaccio.it',
    governingBody: 'FISG',
    safeguardingBody: 'FISG Safeguarding & Child Protection',
    safeguardingUrl: 'https://www.federghiaccio.it',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for FISG competitive license' },
      { kind: 'registration', label: 'FISG Competitive License', note: 'Annual; via FISG portal' },
      { kind: 'insurance', label: 'Italian Ice Hockey Insurance (CONI/INI)', note: 'Mandatory; included in license fee' },
      { kind: 'code_of_conduct', label: 'Code of Conduct', note: 'Required; Italian Olympic Committee (CONI) guidelines' },
      { kind: 'medical_release', label: 'Medical Certificate of Fitness', note: 'Official certificate (certificato medico) required for competitive license' },
    ],
    ageGroupNote: "Serie A is top men's. Youth: U22/U18/U16/U14.",
  },
  {
    countryCode: 'JM',
    countryName: 'Jamaica',
    federationName: 'Jamaican Olympic Ice Hockey Federation',
    federationUrl: 'https://www.iihf.com/en/associations/357/jamaica',
    governingBody: 'IIHF',
    safeguardingBody: 'Jamaica Olympic Academy',
    safeguardingUrl: 'https://www.iihf.com/en/associations/357/jamaica',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'IIHF associate member. Very small program.',
  },
  {
    countryCode: 'JP',
    countryName: 'Japan',
    federationName: 'Japan Ice Hockey Federation',
    federationUrl: 'https://www.jihf.jp',
    governingBody: 'Japan Ice Hockey Federation',
    safeguardingBody: 'JIHF Child Protection',
    safeguardingUrl: 'https://www.jihf.jp',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Family Register (Koseki)', note: 'Required for JIHF player registration; passport for foreign nationals' },
      { kind: 'registration', label: 'JIHF Player Registration', note: 'Annual; via Japan Ice Hockey Federation' },
      { kind: 'insurance', label: 'Japanese Ice Hockey Insurance (JASTO/Tokio Marine)', note: 'Mandatory; individual or club-provided' },
      { kind: 'code_of_conduct', label: 'Code of Conduct', note: 'Required; JIHF fair-play guidelines' },
      { kind: 'medical_release', label: 'Health Certificate (Kenko Shomei)', note: 'Physician-signed; required for competitive license' },
    ],
    ageGroupNote: "All-Japan Intercollegiate is top men's. Youth: U20/U18/U16.",
  },
  {
    countryCode: 'KE',
    countryName: 'Kenya',
    federationName: 'Kenya Federation of Ice Sports',
    federationUrl: 'https://www.iihf.com/en/associations/359/kenya',
    governingBody: 'IIHF',
    safeguardingBody: 'Kenya Ministry of Sports',
    safeguardingUrl: 'https://www.iihf.com/en/associations/359/kenya',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'IIHF associate member. Newest member (joined 2024).',
  },
  {
    countryCode: 'KG',
    countryName: 'Kyrgyzstan',
    federationName: 'Ice Hockey Federation of the Kyrgyz Republic',
    federationUrl: 'https://www.iihf.com/en/associations/361/kyrgyzstan',
    governingBody: 'IIHF',
    safeguardingBody: 'Kyrgyzstan Ministry of Sports',
    safeguardingUrl: 'https://www.iihf.com/en/associations/361/kyrgyzstan',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'IIHF associate member. Limited program.',
  },
  {
    countryCode: 'KP',
    countryName: 'North Korea',
    federationName: 'Ice Hockey Association of the DPR Korea',
    federationUrl: 'https://www.iihf.com/en/associations/360/dpr-korea',
    governingBody: 'IIHF',
    safeguardingBody: 'DPR Korea Ministry of Physical Culture and Sports',
    safeguardingUrl: 'https://www.iihf.com/en/associations/360/dpr-korea',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'IIHF member. Program under national sports administration.',
  },
  {
    countryCode: 'KR',
    countryName: 'South Korea',
    federationName: 'Korea Ice Hockey Association',
    federationUrl: 'https://www.kiha.or.kr',
    governingBody: 'Korea Ice Hockey Association',
    safeguardingBody: 'Korea Ice Hockey Association Child Protection',
    safeguardingUrl: 'https://www.kiha.or.kr',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Resident Registration (Jumin)', note: 'Required for Kiha registration; passport for foreign nationals' },
      { kind: 'registration', label: 'KIHA Player Registration', note: 'Annual; via Korea Ice Hockey Association' },
      { kind: 'insurance', label: 'Korean Ice Hockey Insurance (KB Insurance)', note: 'Mandatory; club-provided or individual' },
      { kind: 'code_of_conduct', label: 'Code of Conduct', note: 'Required; Korean Sports & Olympic Committee guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'Asia League Ice Hockey (ALIH) is top competition.',
  },
  {
    countryCode: 'KW',
    countryName: 'Kuwait',
    federationName: 'Kuwait Ice Hockey Association',
    federationUrl: 'https://www.iihf.com/en/associations/361/kuwait',
    governingBody: 'IIHF',
    safeguardingBody: 'Kuwait Ministry of Sports',
    safeguardingUrl: 'https://www.iihf.com/en/associations/361/kuwait',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'IIHF associate member. Development stage.',
  },
  {
    countryCode: 'KZ',
    countryName: 'Kazakhstan',
    federationName: 'Kazakhstan Ice Hockey Federation',
    federationUrl: 'https://icehockey.kz',
    governingBody: 'Kazakhstan Ice Hockey Federation',
    safeguardingBody: 'Kazakhstan Ministry of Culture and Sports',
    safeguardingUrl: 'https://www.iihf.com/en/associations/358/kazakhstan',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'KHL participation. Strong youth development.',
  },
  {
    countryCode: 'LB',
    countryName: 'Lebanon',
    federationName: 'Lebanese Ice Hockey Federation',
    federationUrl: 'https://www.iihf.com/en/associations/362/lebanon',
    governingBody: 'IIHF',
    safeguardingBody: 'Lebanese Ministry of Sports',
    safeguardingUrl: 'https://www.iihf.com/en/associations/362/lebanon',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'IIHF associate member. Very small program.',
  },
  {
    countryCode: 'LI',
    countryName: 'Liechtenstein',
    federationName: 'Liechtenstein Ice Hockey Federation',
    federationUrl: 'https://www.iihf.com/en/associations/364/liechtenstein',
    governingBody: 'IIHF',
    safeguardingBody: 'Liechtenstein Sports Federation',
    safeguardingUrl: 'https://www.iihf.com/en/associations/364/liechtenstein',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'IIHF associate member. Players often skate in CH/AT.',
  },
  {
    countryCode: 'LT',
    countryName: 'Lithuania',
    federationName: 'Hockey Lietuva',
    federationUrl: 'https://www.hockey.lt',
    governingBody: 'Hockey Lietuva',
    safeguardingBody: 'Hockey Lietuva Child Protection',
    safeguardingUrl: 'https://www.hockey.lt',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for Hockey Lietuva player registration' },
      { kind: 'registration', label: 'Hockey Lietuva Player Registration', note: 'Annual; via Lithuanian hockey federation' },
      { kind: 'insurance', label: 'Lithuanian Ice Hockey Insurance', note: 'Mandatory; club-provided or individual' },
      { kind: 'code_of_conduct', label: 'Code of Conduct', note: 'Required; Lithuanian Basketball/Federation guidelines' },
      { kind: 'medical_release', label: 'Medical Information Form', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'Lithuanian Ice Hockey League is national competition.',
  },
  {
    countryCode: 'LU',
    countryName: 'Luxembourg',
    federationName: 'Fédération Luxembourgeoise de Hockey sur Glace (FLHG)',
    federationUrl: 'https://www.icehockey.lu',
    governingBody: 'Fédération Luxembourgeoise de Hockey sur Glace',
    safeguardingBody: 'Luxembourg Ministry of Sports',
    safeguardingUrl: 'https://www.icehockey.lu',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'Domestic league. IIHF member since 1912.',
  },
  {
    countryCode: 'LV',
    countryName: 'Latvia',
    federationName: 'LHF — Latvian Ice Hockey Federation',
    federationUrl: 'https://www.lhf.lv',
    governingBody: 'Latvian Ice Hockey Federation',
    safeguardingBody: 'LHF Child Protection',
    safeguardingUrl: 'https://www.lhf.lv',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for LHF player registration' },
      { kind: 'registration', label: 'LHF Player License', note: 'Annual; via Latvian hockey portal' },
      { kind: 'insurance', label: 'Latvian Ice Hockey Insurance (Balva)', note: 'Mandatory personal accident + liability; included in license' },
      { kind: 'code_of_conduct', label: 'Code of Conduct', note: 'Required; LHF fair-play guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: "Optibet Latvijas Kausa līga is top men's.",
  },
  {
    countryCode: 'MA',
    countryName: 'Morocco',
    federationName: 'Royal Moroccan Ice Hockey Federation',
    federationUrl: 'https://www.iihf.com/en/associations/364/morocco',
    governingBody: 'IIHF',
    safeguardingBody: 'Moroccan Ministry of Sports',
    safeguardingUrl: 'https://www.iihf.com/en/associations/364/morocco',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'IIHF associate member.',
  },
  {
    countryCode: 'MK',
    countryName: 'North Macedonia',
    federationName: 'Macedonian Ice Hockey Federation',
    federationUrl: 'https://www.iihf.com/en/associations/362/macedonia',
    governingBody: 'IIHF',
    safeguardingBody: 'North Macedonia Ministry of Sports',
    safeguardingUrl: 'https://www.iihf.com/en/associations/362/macedonia',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'IIHF associate member.',
  },
  {
    countryCode: 'MN',
    countryName: 'Mongolia',
    federationName: 'Mongolian Ice Hockey Federation',
    federationUrl: 'https://www.iihf.com/en/associations/363/mongolia',
    governingBody: 'IIHF',
    safeguardingBody: 'Mongolia Ministry of Sports',
    safeguardingUrl: 'https://www.iihf.com/en/associations/363/mongolia',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'Emerging nation; IIHF member since 1993.',
  },
  {
    countryCode: 'MO',
    countryName: 'Macau',
    federationName: 'Macau Ice Sports Federation',
    federationUrl: 'https://www.iihf.com/en/associations/365/macau',
    governingBody: 'IIHF',
    safeguardingBody: 'Macau Sports Bureau',
    safeguardingUrl: 'https://www.iihf.com/en/associations/365/macau',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'IIHF associate member.',
  },
  {
    countryCode: 'MX',
    countryName: 'Mexico',
    federationName: 'Federación Deportiva de México de Hockey Sobre Hielo A.C.',
    federationUrl: 'https://www.mexicoicehockey.com',
    governingBody: 'Federación Deportiva de México de Hockey Sobre Hielo',
    safeguardingBody: 'CONADE',
    safeguardingUrl: 'https://www.iihf.com/en/associations/363/mexico',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'National championships and U18/U20 teams. IIHF member since 1985.',
  },
  {
    countryCode: 'MY',
    countryName: 'Malaysia',
    federationName: 'Malaysia Ice Hockey Federation',
    federationUrl: 'https://www.iihf.com/en/associations/362/malaysia',
    governingBody: 'IIHF',
    safeguardingBody: 'Malaysia Ministry of Youth and Sports',
    safeguardingUrl: 'https://www.iihf.com/en/associations/362/malaysia',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'Emerging nation; IIHF member since 1992.',
  },
  {
    countryCode: 'NL',
    countryName: 'Netherlands',
    federationName: 'IJshockey Nederland',
    federationUrl: 'https://www.ijshockeynederland.nl',
    governingBody: 'IJshockey Nederland',
    safeguardingBody: 'IJshockey Nederland Child Protection',
    safeguardingUrl: 'https://www.ijshockeynederland.nl',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for IJshockey Nederland registration' },
      { kind: 'registration', label: 'IJshockey Nederland Player Registration', note: 'Annual; via Dutch hockey association' },
      { kind: 'insurance', label: 'Dutch Ice Hockey Insurance (Centraal Beheer)', note: 'Mandatory personal accident + liability; club-provided' },
      { kind: 'code_of_conduct', label: 'Code of Conduct', note: 'Required; Dutch Sports Federation guidelines' },
      { kind: 'medical_release', label: 'Medical Information Form', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'BeNe League is top cross-border competition.',
  },
  {
    countryCode: 'NO',
    countryName: 'Norway',
    federationName: 'NIHF — Norges Ishockeyforbund',
    federationUrl: 'https://www.hockey.no',
    governingBody: 'Norges Ishockeyforbund',
    safeguardingBody: 'NIHF Child Protection Policy',
    safeguardingUrl: 'https://www.hockey.no',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for NIHF player registration' },
      { kind: 'registration', label: 'NIHF Player License', note: 'Annual; via club registration system' },
      { kind: 'insurance', label: 'Norwegian Ice Hockey Insurance (Gjensidige)', note: 'Mandatory personal accident + liability; included in license' },
      { kind: 'code_of_conduct', label: 'Code of Conduct', note: 'Required; NIHF fair-play guidelines' },
      { kind: 'medical_release', label: 'Medical Information Form', note: 'Disclosed conditions; team physician review' },
    ],
    ageGroupNote: "GET-ligaen is top men's. Youth: U20/U18/U16.",
  },
  {
    countryCode: 'NP',
    countryName: 'Nepal',
    federationName: 'Nepal Ice Hockey Association',
    federationUrl: 'https://www.iihf.com/en/associations/365/nepal',
    governingBody: 'IIHF',
    safeguardingBody: 'Nepal Ministry of Sports',
    safeguardingUrl: 'https://www.iihf.com/en/associations/365/nepal',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'IIHF associate member. Early development stage.',
  },
  {
    countryCode: 'NZ',
    countryName: 'New Zealand',
    federationName: 'Ice Hockey New Zealand',
    federationUrl: 'https://www.icehockeynz.co.nz',
    governingBody: 'Ice Hockey New Zealand',
    safeguardingBody: 'Ice Hockey NZ Child Protection',
    safeguardingUrl: 'https://www.icehockeynz.co.nz',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for Ice Hockey NZ registration' },
      { kind: 'registration', label: 'Ice Hockey NZ Player Registration', note: 'Annual; via New Zealand Ice Hockey Federation' },
      { kind: 'insurance', label: 'New Zealand Ice Hockey Insurance', note: 'Mandatory; club-provided or individual (ACC scheme covers injuries)' },
      { kind: 'code_of_conduct', label: 'Code of Conduct', note: 'Required; New Zealand Ice Hockey Federation guidelines' },
      { kind: 'safeguarding', label: 'Police Vetting', note: 'Required for coaches and officials working with children' },
      { kind: 'medical_release', label: 'Medical Information Form', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'NZIHL is national competition. Rebranded 2025.',
  },
  {
    countryCode: 'OM',
    countryName: 'Oman',
    federationName: 'Oman Ice Sports Committee',
    federationUrl: 'https://www.iihf.com/en/associations/366/oman',
    governingBody: 'IIHF',
    safeguardingBody: 'Oman Ministry of Sports',
    safeguardingUrl: 'https://www.iihf.com/en/associations/366/oman',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'IIHF associate member.',
  },
  {
    countryCode: 'PH',
    countryName: 'Philippines',
    federationName: 'FIHL — Federation of Ice Hockey League, Inc. (Hockey Philippines)',
    federationUrl: 'https://hockeyphilippines.com',
    governingBody: 'FIHL / Hockey Philippines',
    safeguardingBody: 'Philippine Sports Commission',
    safeguardingUrl: 'https://www.psc.gov.ph',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'PSA Birth Certificate / Passport', note: 'Philippine Statistics Authority (PSA) birth certificate or valid passport' },
      { kind: 'transfer', label: 'Transfer Certificate', note: 'Required for international transfers via IIHF' },
      { kind: 'registration', label: 'FIHL / Hockey Philippines Registration', note: 'Annual; registered club players eligible for national team selection' },
      { kind: 'insurance', label: 'Insurance Confirmation', note: 'PhilHealth or private health insurance required; accident coverage recommended' },
      { kind: 'code_of_conduct', label: 'Code of Conduct', note: 'Signed by player/parent/guardian' },
      { kind: 'medical_release', label: 'Medical Information & Consent Form', note: 'Emergency contacts, medical conditions, parental consent for minors' },
    ],
    ageGroupNote: 'Emerging nation; IIHF full member since 2016. PHL and PMHL leagues.',
  },
  {
    countryCode: 'PL',
    countryName: 'Poland',
    federationName: 'PZHL — Polski Związek Hokeja na Lodzie',
    federationUrl: 'https://www.pzhl.eu',
    governingBody: 'Polski Związek Hokeja na Lodzie',
    safeguardingBody: 'PZHL Child Protection',
    safeguardingUrl: 'https://www.pzhl.eu',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for PZHL player license' },
      { kind: 'registration', label: 'PZHL Player License', note: 'Annual; via PZHL portal' },
      { kind: 'insurance', label: 'Polish Hockey Insurance (PZU/Warta)', note: 'Mandatory; club-provided or individual' },
      { kind: 'code_of_conduct', label: 'Code of Conduct', note: 'Required; Polish Ice Hockey Association guidelines' },
      { kind: 'medical_release', label: 'Medical Fitness Certificate', note: 'Physician-signed; confirms fitness to play' },
    ],
    ageGroupNote: "Polish Hockey League (PHL) is top men's.",
  },
  {
    countryCode: 'PR',
    countryName: 'Puerto Rico',
    federationName: 'Puerto Rico Ice Hockey Association',
    federationUrl: 'https://www.iihf.com/en/associations/368/puerto-rico',
    governingBody: 'IIHF',
    safeguardingBody: 'Puerto Rico Dept. of Sports',
    safeguardingUrl: 'https://www.iihf.com/en/associations/368/puerto-rico',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'IIHF associate member. Development stage.',
  },
  {
    countryCode: 'PT',
    countryName: 'Portugal',
    federationName: 'Portuguese Winter Sports Federation',
    federationUrl: 'https://www.iihf.com/en/associations/367/portugal',
    governingBody: 'IIHF',
    safeguardingBody: 'Portuguese Institute for Sports and Youth',
    safeguardingUrl: 'https://www.iihf.com/en/associations/367/portugal',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'IIHF associate member. Limited domestic program.',
  },
  {
    countryCode: 'QA',
    countryName: 'Qatar',
    federationName: 'Qatar Ice Hockey Federation',
    federationUrl: 'https://www.iihf.com/en/associations/369/qatar',
    governingBody: 'IIHF',
    safeguardingBody: 'Qatar Ministry of Sports',
    safeguardingUrl: 'https://www.iihf.com/en/associations/369/qatar',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'IIHF associate member.',
  },
  {
    countryCode: 'RO',
    countryName: 'Romania',
    federationName: 'Federația Română de Hochei pe Gheață (FRHG)',
    federationUrl: 'https://www.frhg.ro',
    governingBody: 'Federația Română de Hochei pe Gheață',
    safeguardingBody: 'Romanian Ice Hockey Federation Child Protection',
    safeguardingUrl: 'https://www.iihf.com/en/associations/366/romania',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'Erste Liga is domestic competition. IIHF member since 1932.',
  },
  {
    countryCode: 'RS',
    countryName: 'Serbia',
    federationName: 'Serbian Ice Hockey Association',
    federationUrl: 'https://hockeyserbia.com',
    governingBody: 'IIHF',
    safeguardingBody: 'Serbian Ice Hockey Association Child Protection',
    safeguardingUrl: 'https://www.iihf.com/en/associations/368/serbia',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'Serbian Ice Hockey League is domestic competition. IIHF member since 1939.',
  },
  {
    countryCode: 'RU',
    countryName: 'Russia',
    federationName: 'Ice Hockey Federation of Russia',
    federationUrl: 'https://fhr.ru',
    governingBody: 'Ice Hockey Federation of Russia',
    safeguardingBody: 'Russian Ice Hockey Federation Child Protection',
    safeguardingUrl: 'https://www.iihf.com/en/associations/367/russia',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'KHL is top league. Youth: MHL U20, U18, U16.',
  },
  {
    countryCode: 'SE',
    countryName: 'Sweden',
    federationName: 'Svenska Ishockeyförbundet (SIF)',
    federationUrl: 'https://www.swehockey.se',
    governingBody: 'Svenska Ishockeyförbundet',
    safeguardingBody: 'Swedish Ice Hockey Association Child Protection',
    safeguardingUrl: 'https://www.swehockey.se',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for district association registration' },
      { kind: 'registration', label: 'SIF Player License', note: 'Annual; via central portal or district association' },
      { kind: 'insurance', label: 'Swedish Ice Hockey Insurance (SICF)', note: 'Personal accident + liability; included in license fee' },
      { kind: 'code_of_conduct', label: 'Code of Conduct', note: 'Required; follows Swedish Sports Confederation guidelines' },
      { kind: 'medical_release', label: 'Medical Health Form', note: 'Disclosed conditions; team doctor review' },
    ],
    ageGroupNote: "SHL is top men's. Youth: J20/J18/J16/J14/P12/P10. Age cutoff Jan 1.",
  },
  {
    countryCode: 'SG',
    countryName: 'Singapore',
    federationName: 'Singapore Ice Hockey Association',
    federationUrl: 'https://www.iihf.com/en/associations/369/singapore',
    governingBody: 'IIHF',
    safeguardingBody: 'Singapore National Olympic Council',
    safeguardingUrl: 'https://www.iihf.com/en/associations/369/singapore',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'Emerging nation; IIHF member since 1992.',
  },
  {
    countryCode: 'SI',
    countryName: 'Slovenia',
    federationName: 'HZS — Hokejska zveza Slovenije',
    federationUrl: 'https://www.hokej.si',
    governingBody: 'Hokejska zveza Slovenije',
    safeguardingBody: 'HZS Child Protection',
    safeguardingUrl: 'https://www.hokej.si',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for HZS player license' },
      { kind: 'registration', label: 'HZS Player License', note: 'Annual; via Slovenian hockey association' },
      { kind: 'insurance', label: 'Slovenian Ice Hockey Insurance (Zavarovalnica Triglav)', note: 'Mandatory; club-provided or individual' },
      { kind: 'code_of_conduct', label: 'Code of Conduct', note: 'Required; Slovenian Olympic Committee guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'Slovenian Ice Hockey League (SIHL) is national competition.',
  },
  {
    countryCode: 'SK',
    countryName: 'Slovakia',
    federationName: 'SZĽH — Slovenský zväz ľadového hokeja',
    federationUrl: 'https://www.hockeyslovakia.sk',
    governingBody: 'SZĽH',
    safeguardingBody: 'Slovak Ice Hockey Association Child Protection',
    safeguardingUrl: 'https://www.hockeyslovakia.sk',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for SZĽH player registration' },
      { kind: 'registration', label: 'SZĽH Player Registration', note: 'Annual; via Slovak hockey portal' },
      { kind: 'insurance', label: 'Slovak Ice Hockey Insurance', note: 'Mandatory personal accident + liability coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct', note: 'Required; SZĽH fair-play guidelines' },
      { kind: 'medical_release', label: 'Medical Fitness Certificate', note: 'Physician-signed; confirms fitness to play' },
    ],
    ageGroupNote: "Slovak Extraliga is top men's. Youth: U20/U18/U16.",
  },
  {
    countryCode: 'TH',
    countryName: 'Thailand',
    federationName: 'Ice Hockey Association of Thailand',
    federationUrl: 'https://www.ihat.or.th',
    governingBody: 'IIHF',
    safeguardingBody: 'Ice Hockey Association of Thailand',
    safeguardingUrl: 'https://www.iihf.com/en/associations/371/thailand',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'Developing nation; IIHF member since 1989.',
  },
  {
    countryCode: 'TM',
    countryName: 'Turkmenistan',
    federationName: 'Turkmenistan Ice Hockey Federation',
    federationUrl: 'https://www.iihf.com/en/associations/372/turkmenistan',
    governingBody: 'IIHF',
    safeguardingBody: 'Turkmenistan Ministry of Sports',
    safeguardingUrl: 'https://www.iihf.com/en/associations/372/turkmenistan',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'Emerging nation; IIHF member since 1993.',
  },
  {
    countryCode: 'TN',
    countryName: 'Tunisia',
    federationName: 'Tunisian Ice Hockey Association',
    federationUrl: 'https://www.iihf.com/en/associations/373/tunisia',
    governingBody: 'IIHF',
    safeguardingBody: 'Tunisian Ministry of Sports',
    safeguardingUrl: 'https://www.iihf.com/en/associations/373/tunisia',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'IIHF associate member. North Africa.',
  },
  {
    countryCode: 'TR',
    countryName: 'Turkey',
    federationName: 'Turkish Ice Hockey Federation',
    federationUrl: 'https://tbhf.org.tr',
    governingBody: 'Türkiye Buz Hokeyi Federasyonu',
    safeguardingBody: 'Turkish Ice Hockey Federation Child Protection',
    safeguardingUrl: 'https://www.iihf.com/en/associations/373/turkey',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'Turkish Ice Hockey Federation Super League is top. IIHF member since 1991.',
  },
  {
    countryCode: 'TW',
    countryName: 'Chinese Taipei',
    federationName: 'Chinese Taipei Ice Hockey Federation',
    federationUrl: 'https://www.ctihf.org.tw',
    governingBody: 'Chinese Taipei Ice Hockey Federation',
    safeguardingBody: 'Ministry of Education Taiwan',
    safeguardingUrl: 'https://www.iihf.com/en/associations/335/chinese-taipei',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'Developing nation; IIHF member since 1981.',
  },
  {
    countryCode: 'UA',
    countryName: 'Ukraine',
    federationName: 'Ice Hockey Federation of Ukraine',
    federationUrl: 'https://fhu.com.ua',
    governingBody: 'Ice Hockey Federation of Ukraine',
    safeguardingBody: 'Ice Hockey Federation of Ukraine Child Protection',
    safeguardingUrl: 'https://www.iihf.com/en/associations/1374/ukraine',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'Professional league (UHL/Pro Hockey League).',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    federationName: 'USA Hockey',
    federationUrl: 'https://www.usahockey.com',
    governingBody: 'USA Hockey',
    safeguardingBody: 'USA Hockey SafeSport Program',
    safeguardingUrl: 'https://www.usahockey.com/safesport',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'USA Hockey Birth Certificate', note: 'Certified copy or passport; required for under 18' },
      { kind: 'registration', label: 'USA Hockey Registration', note: 'Annual; via PlayersDB portal' },
      { kind: 'insurance', label: 'USA Hockey Accident & Liability Insurance', note: 'Included with annual registration' },
      { kind: 'code_of_conduct', label: 'USA Hockey Code of Conduct', note: 'Required for all coaches, players, parents' },
      { kind: 'medical_release', label: 'Medical Permission Form', note: 'Annual; parental consent for players under 18' },
      { kind: 'concussion', label: 'Concussion Recognition Form', note: 'Required annually; parents/players initial each section' },
    ],
    ageGroupNote: 'Age divisions: U18/U16/U14/U12/U10/U8. Age cutoff Dec 31.',
  },
  {
    countryCode: 'UZ',
    countryName: 'Uzbekistan',
    federationName: 'Uzbekistan Ice Hockey Federation',
    federationUrl: 'https://www.iihf.com/en/associations/376/uzbekistan',
    governingBody: 'IIHF',
    safeguardingBody: 'Uzbekistan Ministry of Sports',
    safeguardingUrl: 'https://www.iihf.com/en/associations/376/uzbekistan',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'Emerging nation; IIHF member since 1993.',
  },
  {
    countryCode: 'ZA',
    countryName: 'South Africa',
    federationName: 'South African Ice Hockey Federation',
    federationUrl: 'https://www.iihf.com/en/associations/370/south-africa',
    governingBody: 'IIHF',
    safeguardingBody: 'South African Ice Hockey Federation',
    safeguardingUrl: 'https://www.iihf.com/en/associations/370/south-africa',
    requiredDocKinds: [
      { kind: 'birth_cert', label: 'Birth Certificate / Passport', note: 'Required for national federation registration' },
      { kind: 'registration', label: 'National Federation Player Registration', note: 'Annual; contact your federation or club' },
      { kind: 'insurance', label: 'Health / Accident Insurance Confirmation', note: 'Mandatory; individual or club-provided coverage' },
      { kind: 'code_of_conduct', label: 'Code of Conduct / Fair Play Pledge', note: 'Required; federation guidelines' },
      { kind: 'medical_release', label: 'Medical Declaration', note: 'Disclosed conditions; emergency contacts' },
    ],
    ageGroupNote: 'Emerging nation; IIHF member since 1937.',
  },
];

/** ISO 3166-1 alpha-2 → Federation entry. */
const fedByCode = new Map(FEDERATIONS.map((f) => [f.countryCode, f]));

/** ISO 3166-1 alpha-2 → default currency code. */
export const COUNTRY_CURRENCY: Record<string, string> = {
  US: "USD", CA: "CAD", GB: "GBP", SE: "SEK", FI: "EUR", CZ: "CZK",
  SK: "EUR", DE: "EUR", CH: "CHF", AT: "EUR", NO: "NOK", DK: "DKK",
  FR: "EUR", IT: "EUR", NL: "EUR", BE: "EUR", ES: "EUR", PL: "PLN",
  LV: "EUR", LT: "EUR", EE: "EUR", SI: "EUR", HR: "EUR", HU: "HUF",
  JP: "JPY", KR: "KRW", AU: "AUD", NZ: "NZD", PH: "PHP", RU: "RUB",
  UA: "UAH", KZ: "KZT", BY: "BYN", RO: "RON", BG: "BGN",
};

export function lookupFederation(countryCode: string): Federation | null {
  return fedByCode.get(countryCode.toUpperCase()) ?? null;
}

/** All country options for a <select> dropdown. */
export const COUNTRY_OPTIONS: { code: string; name: string }[] =
  FEDERATIONS.map((f) => ({ code: f.countryCode, name: f.countryName }));