// Static facts about NHL teams — used to enrich API data for rich team detail pages
// Key: slug (used in URLs and API lookups)

export const NHL_TEAM_DATA: Record<string, {
  founded: number;
  arena: string;
  city: string;
  state: string;
  division: string;
  conference: string;
  colors: string[];
  championships: number;
  captain?: string;
  coach?: string;
  generalManager?: string;
  description: string;
  notablePlayers: string[];
  rivalries: string[];
  website: string;
  social?: { twitter?: string };
}> = {
  'boston-bruins': {
    founded: 1924,
    arena: 'TD Garden',
    city: 'Boston',
    state: 'Massachusetts',
    division: 'Atlantic',
    conference: 'Eastern',
    colors: ['#000000', '#C8102E'],
    championships: 6,
    captain: 'Brad Marchand',
    coach: 'Joe Sacco',
    generalManager: 'Don Sweeney',
    description: 'The Boston Bruins are one of the Original Six NHL franchises and among the most storied hockey clubs in North America. Founded in 1924, the Bruins play out of TD Garden in Boston, Massachusetts and have amassed six Stanley Cup championships. The franchise is known for a passionate, demanding fan base and a rivalry with the Montreal Canadiens that spans nearly a century.',
    notablePlayers: ['Bobby Orr', 'Frank Mahovlich', 'Phil Esposito', 'Cam Neely', 'Ray Bourque', 'Patrice Bergeron', 'Brad Marchand'],
    rivalries: ['montreal-canadiens', 'toronto-maple-leafs', 'new-york-rangers'],
    website: 'https://nhl.com/bruins',
    social: { twitter: '@NHLBruins' },
  },
  'toronto-maple-leafs': {
    founded: 1917,
    arena: 'Scotiabank Arena',
    city: 'Toronto',
    state: 'Ontario',
    division: 'Atlantic',
    conference: 'Eastern',
    colors: ['#003887', '#FFFFFF'],
    championships: 13,
    captain: 'Auston Matthews',
    coach: 'Craig Berube',
    generalManager: 'Brad Treliving',
    description: 'The Toronto Maple Leafs are one of the Original Six and the most championship-decorated franchise in hockey — 13 Stanley Cups. They play out of Scotiabank Arena in the heart of downtown Toronto, Canada\'s largest city and arguably its most sports-crazed market. The city has been waiting for Cup number 14 since 1967, and that wait has only sharpened the fanbase\'s passion and intensity.',
    notablePlayers: ['Syl Apps', 'Ted Kennedy', 'Dave Keon', 'Mats Sundin', 'Auston Matthews', 'Mitch Marner'],
    rivalries: ['montreal-canadiens', 'boston-bruins'],
    website: 'https://nhl.com/mapleleafs',
    social: { twitter: '@MapleLeafs' },
  },
  'montreal-canadiens': {
    founded: 1909,
    arena: 'Bell Centre',
    city: 'Montreal',
    state: 'Quebec',
    division: 'Atlantic',
    conference: 'Eastern',
    colors: ['#C8102E', '#FFFFFF', '#001E5F'],
    championships: 24,
    captain: 'Nick Suzuki',
    coach: 'Martin St-Louis',
    generalManager: 'Kent Hughes',
    description: 'The Montreal Canadiens are the oldest professional hockey franchise in North America and the most decorated team in NHL history with 24 Stanley Cups. Founded in 1909, the Canadiens play out of the Bell Centre in Montreal, Quebec — a city where hockey is religion. The franchise\'s dynasty years, particularly the five consecutive championships from 1956 to 1960, built a legacy that has never been matched.',
    notablePlayers: ['Maurice Richard', 'Jean Béliveau', 'Guy Lafleur', 'Ken Dryden', 'Larry Robinson', 'Nick Suzuki'],
    rivalries: ['boston-bruins', 'toronto-maple-leafs'],
    website: 'https://nhl.com/canadiens',
    social: { twitter: '@CanadiensMTL' },
  },
  'detroit-red-wings': {
    founded: 1926,
    arena: 'Little Caesars Arena',
    city: 'Detroit',
    state: 'Michigan',
    division: 'Atlantic',
    conference: 'Eastern',
    colors: ['#C8102E', '#FFFFFF'],
    championships: 11,
    captain: 'Dylan Larkin',
    coach: 'Todd McLellan',
    generalManager: 'Ilari Kärnä',
    description: 'The Detroit Red Wings are one of the Original Six and one of the most successful hockey organizations in history. Eleven Stanley Cups. Twenty consecutive playoff appearances. A city that bleeds red from the rafters down. The Red Wings play out of Little Caesars Arena in downtown Detroit and have been a pillar of American hockey culture since 1926. They built their identity on hard work, physical play, and championship DNA.',
    notablePlayers: ['Gordie Howe', 'Steve Yzerman', 'Nicklas Lidstrom', 'Alex Yzerman', 'Niklas Kronwall', 'Dylan Larkin'],
    rivalries: ['chicago-blackhawks', 'boston-bruins'],
    website: 'https://nhl.com/redwings',
    social: { twitter: '@DetroitRedWings' },
  },
  'chicago-blackhawks': {
    founded: 1926,
    arena: 'United Center',
    city: 'Chicago',
    state: 'Illinois',
    division: 'Central',
    conference: 'Western',
    colors: ['#C8102E', '#001E5F', '#FFFFFF'],
    championships: 6,
    captain: 'Connor Bedard',
    coach: 'Anders Sorensen',
    generalManager: 'Kyle Davidson',
    description: 'The Chicago Blackhawks are one of the Original Six and a cornerstone of American hockey. Founded in 1926, the Blackhawks play out of the United Center on the Near West Side of Chicago. The franchise has won six Stanley Cups and carries a passionate, working-class fan base that reflects the city itself. The famous Indianhead sweater is one of the most recognizable logos in professional sports.',
    notablePlayers: ['Stan Mikita', 'Bobby Hull', 'Tony Esposito', 'Jonathan Toews', 'Patrick Kane', 'Connor Bedard'],
    rivalries: ['detroit-red-wings', 'st-louis-blues', 'minnesota-wild'],
    website: 'https://nhl.com/blackhawks',
    social: { twitter: '@NHLBlackhawks' },
  },
  'colorado-avalanche': {
    founded: 1995,
    arena: 'Ball Arena',
    city: 'Denver',
    state: 'Colorado',
    division: 'Central',
    conference: 'Western',
    colors: ['#1E4D8C', '#003384', '#A2A0A0'],
    championships: 3,
    captain: 'Nathan MacKinnon',
    coach: 'Patrick Roy',
    generalManager: 'Chris MacGregor',
    description: 'The Colorado Avalanche burst onto the scene in 1996 with one of the most dominant first seasons in professional sports history — winning the Cup in their first year after relocating from Quebec. They\'ve since established themselves as one of the premier franchises in hockey, with three Stanley Cups and a core built around Nathan MacKinnon and Cale Makar. Ball Arena in Denver is regarded as one of the best venues in hockey.',
    notablePlayers: ['Joe Sakic', 'Patrick Roy', 'Peter Forsberg', 'Nathan MacKinnon', 'Cale Makar'],
    rivalries: ['vegas-golden-knights', 'dallas-stars', 'minnesota-wild'],
    website: 'https://nhl.com/avalanche',
    social: { twitter: '@Avalanche' },
  },
  'vegas-golden-knights': {
    founded: 2017,
    arena: 'T-Mobile Arena',
    city: 'Las Vegas',
    state: 'Nevada',
    division: 'Pacific',
    conference: 'Western',
    colors: ['#B4975A', '#000000', '#C8102E', '#FFFFFF'],
    championships: 1,
    captain: 'Mark Stone',
    coach: 'John Tortorella',
    generalManager: 'Ken Vasilchenko',
    description: 'The Vegas Golden Knights are the most successful expansion franchise in professional sports history. In just their second season, they reached the Stanley Cup Final. By their fourth season, they had won it. The Knights play out of T-Mobile Arena on the Las Vegas Strip and have built one of the loudest, most hostile home environments in hockey. No organization has changed the expansion draft model more than Vegas.',
    notablePlayers: ['Marc-Andre Fleury', 'William Karlsson', 'Mark Stone', 'Shea Theodore'],
    rivalries: ['colorado-avalanche', 'anaheim-ducks', 'san-jose-sharks'],
    website: 'https://nhl.com/goldenknights',
    social: { twitter: '@GoldenKnights' },
  },
  'carolina-hurricanes': {
    founded: 1997,
    arena: 'PNC Arena',
    city: 'Raleigh',
    state: 'North Carolina',
    division: 'Metropolitan',
    conference: 'Eastern',
    colors: ['#C8102E', '#000000', '#8C8C8C'],
    championships: 1,
    captain: 'Jordan Staal',
    coach: 'Rod Brind\'Amour',
    generalManager: 'Eric Tulsky',
    description: 'The Carolina Hurricanes have been one of the most consistent contenders in the NHL\'s Eastern Conference over the last decade. They play out of PNC Arena in Raleigh, North Carolina and have one Stanley Cup to their name from 2006. Under head coach Rod Brind\'Amour, one of the most respected figures in hockey, the Hurricanes have built a fast, aggressive identity that reflects the development philosophy of modern NHL coaching.',
    notablePlayers: ['Rod Brind\'Amour', 'Eric Staal', 'Sebastian Aho', 'Andrei Svechnikov', 'Frederik Andersen'],
    rivalries: ['new-jersey-devils', 'new-york-rangers', 'washington-capitals'],
    website: 'https://nhl.com/hurricanes',
    social: { twitter: '@NHLCanes' },
  },
  'edmonton-oilers': {
    founded: 1972,
    arena: 'Rogers Place',
    city: 'Edmonton',
    state: 'Alberta',
    division: 'Pacific',
    conference: 'Western',
    colors: ['#003888', '#FC4C02', '#FFFFFF'],
    championships: 5,
    captain: 'Connor McDavid',
    coach: 'Kris Knoblauch',
    generalManager: 'Stan Bowman',
    description: 'The Edmonton Oilers are built around Connor McDavid — widely considered the greatest player of his generation and arguably of all time. Five Stanley Cups. A city that lives and breathes hockey. Rogers Place is a world-class arena that comes alive when the Oilers are in playoff contention. The McDavid-Draisaitl combination is one of the most electric duos the sport has ever seen.',
    notablePlayers: ['Wayne Gretzky', 'Mark Messier', 'Paul Coffey', 'Connor McDavid', 'Leon Draisaitl'],
    rivalries: ['calgary-flames', 'vegas-golden-knights', 'colorado-avalanche'],
    website: 'https://nhl.com/oilers',
    social: { twitter: '@EdmontonOilers' },
  },
  'new-york-rangers': {
    founded: 1926,
    arena: 'Madison Square Garden',
    city: 'New York',
    state: 'New York',
    division: 'Metropolitan',
    conference: 'Eastern',
    colors: ['#0038A8', '#C8102E', '#FFFFFF'],
    championships: 4,
    captain: 'Jacob Trouba',
    coach: 'Peter Laviolette',
    generalManager: 'Chris Drury',
    description: 'The New York Rangers are one of the Original Six and the most prominent hockey franchise in the world\'s largest city. They play out of Madison Square Garden — the most famous arena in the world — and carry a fan base that spans the entire globe. Four Stanley Cups. A recent run to the Eastern Conference Final has the Rangers positioned as one of the premier franchises in the East, with a passionate young core and championship ambitions.',
    notablePlayers: ['Mark Messier', 'Brian Leetch', 'Mike Richter', 'Adam Fox', 'Artemi Panarin', 'Vincent Trocheck'],
    rivalries: ['new-york-islanders', 'new-jersey-devils', 'boston-bruins'],
    website: 'https://nhl.com/rangers',
    social: { twitter: '@NYRangers' },
  },
};

export default NHL_TEAM_DATA;