// /learn/[...qaSlug]
//
// WS28 PR3 — Q&A catch-all route. Renders any Q&A page generated by
// /lib/qa-content-generator. The path segments are joined and looked up
// against the generated page slugs.
//
// Slug format: "{prefix}-{name}"
//   /learn/hockey-in-canada         → slug "hockey-in-canada"
//   /learn/nhl-teams                → slug "nhl-teams"
//   /learn/hockey-rinks-in-toronto-canada → slug "hockey-rinks-in-toronto-canada"
//
// All Q&A pages share the same template:
//   - H1 question
//   - 40-80 word direct answer (Featured Snippet format)
//   - Long-form answer body (Markdown)
//   - FAQPage JSON-LD
//   - Data provenance section
//   - Related URLs

import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { generateQAPages, findQAPage, type QAPageConfig } from '@/lib/qa-content-generator';
import { withDefaultOg } from '@/lib/metadata-defaults';

export const revalidate = 3600;
export const dynamicParams = true;

export async function generateMetadata({ params }: { params: Promise<{ qaSlug: string[] }> }): Promise<Metadata> {
  const { qaSlug } = await params;
  const slug = (qaSlug || []).join('-');
  const page = await findQAPage(slug);
  if (!page) return { title: 'Not found' };
  return {
    title: { absolute: page.og_title },
    description: page.meta_description,
    alternates: { canonical: `https://rinkstop.com${page.url_path}` },
    openGraph: withDefaultOg({
      title: page.og_title,
      description: page.meta_description,
      url: `https://rinkstop.com${page.url_path}`,
      type: 'article',
    }),
  };
}

function renderInline(text: string): React.ReactNode {
  const parts: React.ReactNode[] = [];
  let key = 0;
  let remaining = text;
  while (remaining.length > 0) {
    const boldMatch = remaining.match(/\*\*(.+?)\*\*/);
    const linkMatch = remaining.match(/\[([^\]]+)\]\(([^)]+)\)/);
    let firstIdx = Infinity;
    let firstMatch: RegExpMatchArray | null = null;
    let firstType: 'bold' | 'link' | null = null;
    if (boldMatch && boldMatch.index !== undefined && boldMatch.index < firstIdx) {
      firstIdx = boldMatch.index;
      firstMatch = boldMatch;
      firstType = 'bold';
    }
    if (linkMatch && linkMatch.index !== undefined && linkMatch.index < firstIdx) {
      firstIdx = linkMatch.index;
      firstMatch = linkMatch;
      firstType = 'link';
    }
    if (!firstMatch || firstIdx === Infinity) {
      parts.push(remaining);
      break;
    }
    if (firstIdx > 0) parts.push(remaining.slice(0, firstIdx));
    if (firstType === 'bold') {
      parts.push(<strong key={key++}>{firstMatch[1]}</strong>);
      remaining = remaining.slice(firstIdx + firstMatch[0].length);
    } else {
      const url = firstMatch[2];
      const isInternal = url.startsWith('/');
      parts.push(
        isInternal
          ? <Link key={key++} href={url} style={{ color: '#4A90D9', textDecoration: 'underline' }}>{firstMatch[1]}</Link>
          : <a key={key++} href={url} style={{ color: '#4A90D9', textDecoration: 'underline' }} target="_blank" rel="noopener noreferrer">{firstMatch[1]}</a>
      );
      remaining = remaining.slice(firstIdx + firstMatch[0].length);
    }
  }
  return parts;
}

function renderMarkdown(md: string): React.ReactNode {
  const blocks: React.ReactNode[] = [];
  let key = 0;
  const lines = md.split('\n');
  let para: string[] = [];
  let list: string[] = [];
  const flushPara = () => {
    if (para.length) {
      blocks.push(<p key={key++}>{renderInline(para.join(' '))}</p>);
      para = [];
    }
  };
  const flushList = () => {
    if (list.length) {
      blocks.push(
        <ul key={key++} style={{ color: 'rgba(255,255,255,0.75)', fontSize: '0.9375rem', lineHeight: 1.7 }}>
          {list.map((item, i) => <li key={i}>{renderInline(item)}</li>)}
        </ul>
      );
      list = [];
    }
  };
  for (const line of lines) {
    if (line.startsWith('## ')) {
      flushPara(); flushList();
      blocks.push(<h2 key={key++} style={{ fontSize: '1.25rem', fontWeight: 700, color: '#fff', marginTop: '1.5rem', marginBottom: '0.75rem' }}>{line.slice(3)}</h2>);
    } else if (line.startsWith('- ')) {
      flushPara();
      list.push(line.slice(2));
    } else if (line.trim() === '') {
      flushPara(); flushList();
    } else {
      flushList();
      para.push(line);
    }
  }
  flushPara(); flushList();
  return blocks;
}

export default async function QAPage({ params }: { params: Promise<{ qaSlug: string[] }> }) {
  const { qaSlug } = await params;
  const slug = (qaSlug || []).join('-');
  const page = await findQAPage(slug);
  if (!page) notFound();

  const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: page.faqs.map((f) => ({
      '@type': 'Question',
      name: f.q,
      acceptedAnswer: { '@type': 'Answer', text: f.a },
    })),
  };

  return (
    <main style={{ maxWidth: '880px', margin: '0 auto', padding: '0.75rem 1rem 3rem' }}>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />

      <nav style={{ fontSize: '0.75rem', color: 'rgba(255,255,255,0.4)', marginBottom: '1rem' }}>
        <Link href="/" style={{ color: 'rgba(255,255,255,0.4)' }}>Home</Link>
        <span style={{ margin: '0 0.4rem' }}>›</span>
        <Link href="/learn" style={{ color: 'rgba(255,255,255,0.4)' }}>Learn hockey</Link>
        <span style={{ margin: '0 0.4rem' }}>›</span>
        <span style={{ color: 'rgba(255,255,255,0.6)' }}>Q&A</span>
      </nav>

      <h1 style={{ fontSize: 'clamp(1.5rem, 4vw, 2.25rem)', color: '#fff', lineHeight: 1.15, margin: '0 0 1rem' }}>
        {page.question}
      </h1>

      <div
        style={{
          background: 'linear-gradient(135deg, #0d2137 0%, #061424 100%)',
          border: '1px solid rgba(74,144,217,0.3)',
          borderRadius: 12,
          padding: '1.25rem 1.5rem',
          marginBottom: '1.5rem',
          fontSize: '1.0625rem',
          color: 'rgba(255,255,255,0.92)',
          lineHeight: 1.55,
        }}
      >
        {page.short_answer}
      </div>

      <article style={{ color: 'rgba(255,255,255,0.75)', fontSize: '0.9375rem', lineHeight: 1.7 }}>
        {renderMarkdown(page.full_answer_md)}
      </article>

      <section
        style={{
          background: 'var(--s2)',
          border: '1px solid var(--border)',
          borderRadius: 12,
          padding: '1.25rem',
          marginTop: '2rem',
        }}
      >
        <h2 style={{ fontSize: '1.125rem', color: '#fff', fontWeight: 700, marginBottom: '1rem' }}>
          Frequently asked questions
        </h2>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
          {page.faqs.map((f, i) => (
            <details key={i} style={{ borderTop: i > 0 ? '1px solid var(--border)' : 'none', paddingTop: i > 0 ? '0.75rem' : 0 }}>
              <summary style={{ color: '#fff', fontWeight: 600, cursor: 'pointer', fontSize: '0.9375rem' }}>
                {f.q}
              </summary>
              <p style={{ color: 'rgba(255,255,255,0.7)', fontSize: '0.875rem', lineHeight: 1.65, marginTop: '0.5rem', marginBottom: 0 }}>
                {f.a}
              </p>
            </details>
          ))}
        </div>
      </section>

      <section
        style={{
          marginTop: '1.5rem',
          padding: '1rem 1.25rem',
          background: 'rgba(255,255,255,0.03)',
          border: '1px solid var(--border)',
          borderRadius: 8,
          fontSize: '0.8125rem',
          color: 'rgba(255,255,255,0.55)',
        }}
      >
        <div style={{ fontWeight: 700, color: 'rgba(255,255,255,0.7)', marginBottom: '0.5rem', fontSize: '0.625rem', letterSpacing: '0.1em', textTransform: 'uppercase' }}>
          Data sources
        </div>
        <ul style={{ listStyle: 'none', padding: 0, margin: 0 }}>
          {page.data_sources.map((ds, i) => (
            <li key={i}>
              {ds.source}: <strong style={{ color: 'rgba(255,255,255,0.85)' }}>{ds.count.toLocaleString()}</strong> records
            </li>
          ))}
        </ul>
        <div style={{ marginTop: '0.5rem' }}>
          <Link href="/data-methodology" style={{ color: '#4A90D9', fontSize: '0.75rem' }}>
            Read RinkStop's data methodology →
          </Link>
        </div>
      </section>

      <section style={{ marginTop: '2rem' }}>
        <h3 style={{ fontSize: '1rem', color: '#fff', fontWeight: 700, marginBottom: '0.75rem' }}>
          Continue exploring
        </h3>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.625rem' }}>
          {page.related_urls.map((r, i) => (
            <Link
              key={i}
              href={r.url}
              style={{
                display: 'inline-block',
                padding: '0.5rem 1rem',
                background: 'rgba(74,144,217,0.15)',
                border: '1px solid rgba(74,144,217,0.4)',
                borderRadius: 6,
                color: '#4A90D9',
                fontSize: '0.875rem',
                textDecoration: 'none',
              }}
            >
              {r.label} →
            </Link>
          ))}
        </div>
      </section>
    </main>
  );
}
