const path = require('path');

/** @type {import('next').NextConfig} */
const nextConfig = {
  // Bump on every deploy to invalidate Vercel's per-build CDN cache.
  // Without this, Vercel can serve stale bundles for ~hours after a
  // successful deploy (seen 2026-07-30 08:04 CDT — 3 successful deploys
  // in a row, CDN stuck on the build hash from 90 min earlier).
  // Bump this to the current epoch when shipping a fix you need on
  // production immediately. Cheap, safe, deterministic.
  generateBuildId: async () => `v-${Date.now()}`,
  reactStrictMode: true,
  // WS-Recovery 2026-08-11: skip ESLint during builds.
  // eslint is not in devDependencies, and Next.js's build fails with
  // "ESLint must be installed in order to run during builds" otherwise.
  // Our safety net is the pre-push guard: gate 3 (tsc --noEmit) catches
  // type errors, gate 5 catches dynamic-segment collisions. ESLint policy
  // can be added later as a deliberate choice with a real rule set.
  eslint: { ignoreDuringBuilds: true },
  // Fix 3 followup (2026-07-08): skip Next.js's default trailing-slash
  // redirect. Combined with our /index.php/* catch-all sources below, this
  // means /index.php/news/ -> /news in a single 308 hop instead of going
  // through /index.php/news first. Cleaner redirect chain, same SEO.
  skipTrailingSlashRedirect: true,
  webpack: (config) => {
    config.resolve.alias['@'] = path.resolve(__dirname, 'src');
    return config;
  },
  images: {
    // Restrict remote image sources to known-good hosts (closes M4 from the
    // 2026-06-11 security audit — the previous '**' allowed any HTTPS host
    // to be used as an image source, which could be abused for SSRF or to
    // bypass cache controls).
    remotePatterns: [
      { protocol: 'https', hostname: 'img.clerk.com' },      // Clerk avatars
      { protocol: 'https', hostname: 'images.clerk.com' },    // Clerk image proxy
      { protocol: 'https', hostname: '*.supabase.co' },       // Supabase storage
      { protocol: 'https', hostname: 'avatars.githubusercontent.com' }, // GitHub avatars
      { protocol: 'https', hostname: 'lh3.googleusercontent.com' },     // Google avatars
      { protocol: 'https', hostname: 'platform-lookaside.fbsbx.com' }, // FB OAuth avatars
    ],
  },
  async headers() {
    // Security headers (closes M3 from the 2026-06-11 security audit).
    // We set conservative defaults here; tune CSP per page as needed.
    return [
      {
        source: '/:path*',
        headers: [
          { key: 'X-Frame-Options', value: 'SAMEORIGIN' },
          { key: 'X-Content-Type-Options', value: 'nosniff' },
          { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
          { key: 'Permissions-Policy', value: 'camera=(), microphone=(), geolocation=(self), interest-cohort=()' },
          {
            key: 'Strict-Transport-Security',
            value: 'max-age=31536000; includeSubDomains',
          },
          // Content Security Policy. Clerk's hosted components require
          // 'unsafe-inline' / 'unsafe-eval' for their bundled scripts.
          // Supabase, Stripe, and Zoho need their own origins in connect-src.
          // Tighten iteratively after Clerk publishes a nonce-based mode.
          //
          // WS16 PR1 (2026-08-03): AdSense origins added so AdSense can
          // load + render on the site. Per Google's CSP guide
          // (support.google.com/adsense/answer/16283098), publishers using
          // CSP must allow AdSense origins. Without these, even PR2's
          // <AdSlot> code can't reach googlesyndication.com or the
          // doubleclick iframe. Scope is intentionally minimal — only the
          // AdSense + Google-CMP origins. GA4 and GTM are listed because
          // AdSense's auto-analytics piggybacks on them. Once we know
          // which ad units we actually run (PR2), we can prune any unused
          // origins.
          {
            key: 'Content-Security-Policy',
            value: [
              "default-src 'self'",
              "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.clerk.accounts.dev https://clerk.rinkstop.com https://*.stripe.com https://pagead2.googlesyndication.com https://*.googlesyndication.com https://www.googletagservices.com https://*.googletagmanager.com https://*.google-analytics.com https://*.doubleclick.net https://www.google.com",
              "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
              "img-src 'self' data: blob: https:",
              "font-src 'self' data: https://*.clerk.accounts.dev https://*.clerk.com https://fonts.gstatic.com",
              "connect-src 'self' https://*.clerk.accounts.dev https://clerk.rinkstop.com https://*.supabase.co https://api.stripe.com https://*.highlightly.net wss://*.supabase.co https://*.google-analytics.com https://*.doubleclick.net https://pagead2.googlesyndication.com https://*.googlesyndication.com https://www.google.com",
              "frame-src 'self' https://*.clerk.accounts.dev https://clerk.rinkstop.com https://js.stripe.com https://hooks.stripe.com https://www.youtube.com https://googleads.g.doubleclick.net https://*.googlesyndication.com https://*.doubleclick.net https://www.google.com https://verification.didit.me",
              "worker-src 'self' blob:",
              "object-src 'none'",
              "base-uri 'self'",
              "form-action 'self' https://*.clerk.accounts.dev https://clerk.rinkstop.com",
              "frame-ancestors 'none'",
              "upgrade-insecure-requests",
            ].join('; '),
          },
        ],
      },
      {
        source: '/dashboard/identity',
        headers: [
          { key: 'Permissions-Policy', value: 'camera=(self), microphone=(self), geolocation=(self), interest-cohort=()' },
        ],
      },
      // Immutable 1-year cache for static images in /public/images/.
      // Vercel's CDN serves these directly; without this header, every
      // crawler request re-fetches the file. With max-age=31536000,
      // repeat requests are served from edge cache. Saves bandwidth on
      // Vercel Hobby plan (100GB/mo cap).
      {
        source: '/images/:path*',
        headers: [
          { key: 'Cache-Control', value: 'public, max-age=31536000, immutable' },
        ],
      },
      // Also cache the favicon and other static assets for 1 year.
      {
        source: '/:path(favicon\\.ico|og-image\\.png|rinkstoplogo\\.png|robots\\.txt)',
        headers: [
          { key: 'Cache-Control', value: 'public, max-age=31536000, immutable' },
        ],
      },
    ];
  },
  async redirects() {
    return [
      {
        source: '/scores',
        destination: '/directory/games',
        permanent: true,
      },
      // Legacy /draft/[year] URLs from before the namespace split
      // (per Arnel's decision 2026-06-30, Option A). All historical
      // references to /draft/2026, /draft/2025, etc. should now go
      // to /draft/nhl/[year]. Future sibling routes will live at
      // /draft/ohl/[year], /draft/whl/[year], etc. so we use a regex
      // that only matches the 4-digit year pattern — not landing pages
      // like /draft/ohl which we'll add later.
      {
        source: '/draft/:year(\\d{4})',
        destination: '/draft/nhl/:year',
        permanent: true,
      },
      // /directory/staffs → /directory/staff. The dynamic [country] route
      // catches /directory/staffs and renders 'Hockey in Staffs' (a non-country
      // the geo template didn't recognize). The actual staff directory lives
      // at the singular path. Permanent redirect so old links + bookmarks
      // resolve to the right page.
      {
        source: '/directory/staffs',
        destination: '/directory/staff',
        permanent: true,
      },
      // /directory/locations/czechia/* and /directory/czechia → /directory/locations/czech-republic/* and /directory/czech-republic
      // (canonical URL is now czech-republic; czechia was the legacy slug).
      {
        source: '/directory/locations/czechia/:path*',
        destination: '/directory/locations/czech-republic/:path*',
        permanent: true,
      },
      {
        source: '/directory/czechia',
        destination: '/directory/czech-republic',
        permanent: true,
      },
      {
        source: '/hockey/czechia',
        destination: '/hockey/czech-republic',
        permanent: true,
      },
      {
        source: '/hockey/czechia/:path*',
        destination: '/hockey/czech-republic/:path*',
        permanent: true,
      },
      // /news/2026-nhl-draft-complete-results → /news/2026-nhl-draft-round-1-storylines
      // The article title changed in iteration 2 but the slug wasn't updated
      // until iteration 3. Old slug URL no longer matches the content; redirect
      // so social shares + bookmarks from the original publish still resolve.
      {
        source: '/news/2026-nhl-draft-complete-results',
        destination: '/news/2026-nhl-draft-round-1-storylines',
        permanent: true,
      },
      {
        source: '/gear-reviews',
        destination: '/gear-brands',
        permanent: true,
      },
      // Partner/businesses rename (WS7 PR1, 2026-07-23).
      // /partner → /partner-with-us (marketing page got its own slug).
      // /businesses → /partners (list + detail). Both /businesses/[id] and
      // /businesses/[id]/... go to /partners/[id]/... so deep links resolve.
      {
        source: '/partner',
        destination: '/partner-with-us',
        permanent: true,
      },
      {
        source: '/businesses',
        destination: '/partners',
        permanent: true,
      },
      {
        source: '/businesses/:path*',
        destination: '/partners/:path*',
        permanent: true,
      },
      // www.rinkstop.com → rinkstop.com (301)
      // Closes the brand-signal split: GSC's 90d report shows both
      // www.rinkstop.com (6 clicks, 9 impr, pos 1.11) and
      // rinkstop.com (23 clicks, 72 impr, pos 1.60) getting impressions
      // for the same queries. Consolidating to the naked domain
      // doubles our ranking signal for the home page.
      {
        source: '/:path*',
        has: [
          { type: 'host', value: 'www.rinkstop.com' },
        ],
        destination: 'https://rinkstop.com/:path*',
        permanent: true,
      },
      // Legacy WordPress URLs (Fix 3, 2026-07-08). The old /index.php/*
      // paths were indexed by Google before the rebuild and still 404.
      // 301 redirects to current routes pass any residual link equity
      // instead of dropping it. Both bare and trailing-slash variants
      // are caught, plus a :path* catch-all for any deeper URLs.
      // Verified 2026-07-08: all targets ( /news, /pricing, /contact,
      // /terms ) exist and return 200. Sitemap is already clean.
      {
        source: '/index.php/news/:path*',
        destination: '/news',
        permanent: true,
      },
      {
        source: '/index.php/store/:path*',
        destination: '/pricing',
        permanent: true,
      },
      {
        source: '/index.php/contacts-us/:path*',
        destination: '/contact',
        permanent: true,
      },
      {
        source: '/index.php/terms-and-conditions/:path*',
        destination: '/terms',
        permanent: true,
      },
      {
        source: '/(.*)',
        has: [
          { type: 'host', value: 'rinkstop-platform\.vercel\.app' },
        ],
        destination: 'https://rinkstop.com/$1',
        permanent: true,
      },
      // Rink 404 redirects (SEO cleanup, 2026-07-19).
      // Source: /tmp/coverage-2026-07-19/Table.csv (GSC crawl errors).
      // Audit: rinkstop-content/seo/audit-404-slugs.mjs re-ran 2026-07-19,
      // resolved each old slug against the live Supabase `rinks` table.
      // 8 redirects go to a current canonical slug (verified to exist);
      // 8 redirect to the /directory/rinks listing because no exact or
      // fuzzy match was found in the DB.
      { source: '/directory/rinks/versowood-arena-heinola', destination: '/directory/rinks/versowood-arena', permanent: true },
      { source: '/directory/rinks/scheels-arena', destination: '/directory/rinks/scheels-arena-fargo', permanent: true },
      { source: '/directory/rinks/td-place', destination: '/directory/rinks/td-place-arena', permanent: true },
      { source: '/directory/rinks/joynext-arena', destination: '/directory/rinks/joynext-arena-rudolf-harbig-halle', permanent: true },
      { source: '/directory/rinks/beijing-world-ice-arena-skating-rink-qinghe-mixc', destination: '/directory/rinks/world-ice-arena', permanent: true },
      { source: '/directory/rinks/olympia-eishalle', destination: '/directory/rinks/olympia-eishalle-munich', permanent: true },
      { source: '/directory/rinks/kisapuisto-kisapuiston-jaahalli', destination: '/directory/rinks/kisapuisto', permanent: true },
      { source: '/directory/rinks/rogers-arena-vancouver', destination: '/directory/rinks/rogers-arena', permanent: true },
      { source: '/directory/rinks/skellefte-kraft-arena', destination: '/directory/rinks', permanent: true },
      { source: '/directory/rinks/psd-bank-n-rnberg-arena', destination: '/directory/rinks', permanent: true },
      { source: '/directory/rinks/probonio-arena-kasseler-sportsworld', destination: '/directory/rinks', permanent: true },
      { source: '/directory/rinks/colee-financiere-sun-life', destination: '/directory/rinks', permanent: true },
      { source: '/directory/rinks/slush-puppie-place', destination: '/directory/rinks', permanent: true },
      { source: '/directory/rinks/st-ngebro-ishall', destination: '/directory/rinks', permanent: true },
      { source: '/directory/rinks/upplands-bilforum-arena-gr-nby-ishall', destination: '/directory/rinks', permanent: true },
      { source: '/directory/rinks/brantford-civic-centre', destination: '/directory/rinks', permanent: true },
      // Team 404 redirects (SEO cleanup, 2026-07-19).
      // Source: /tmp/coverage-2026-07-19/Table.csv (GSC crawl errors).
      // Audit: rinkstop-content/seo/audit-404-slugs.mjs re-ran 2026-07-19,
      // resolved each old slug against the live Supabase `teams` table.
      //
      // Cross-slug (5): verified city/country/league match for destination.
      { source: '/directory/teams/sochi', destination: '/directory/teams/hc-sochi', permanent: true },
      { source: '/directory/teams/cherepovets', destination: '/directory/teams/severstal-cherepovets', permanent: true },
      { source: '/directory/teams/vitiaz-podolsk', destination: '/directory/teams/podolsk', permanent: true },
      { source: '/directory/teams/modo-hockey', destination: '/directory/teams/modo-hockey-shl', permanent: true },
      { source: '/directory/teams/brynas-if', destination: '/directory/teams/brynas-if-shl', permanent: true },
      // Self-slug -> /directory/teams listing (626 redirects).
      // These slugs exist in `teams` table but not in `team_workspaces`,
      // so /directory/teams/[slug] returns 404 (page reads team_workspaces).
      // The listing these teams belong to is /directory/teams.
      { source: '/directory/teams/riga-prizma', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/oberthurgau', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/angers', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/karpat', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/henderson-silver-knights', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/progress-glazov', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/raron', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/penza', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/edmonton-oilers', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/tps-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/thun', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/tri-city-storm', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/roki-rovaniemi-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/kunlun-red-star', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/jonquiere-marquis', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/pyry-nokian', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/oji-eagles', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/st-louis-blues', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/mamonty-yugry', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/hämeenlinna-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/portland-winterhawks', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/omskie-yastreby', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/ladya', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/owen-sound-platers', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/slavia-praha', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/youngstown-phantoms', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/martigny', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/podolsk', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/saipa', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/maribor', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/kadan', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/ontario-reign', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/tappara', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/vítkovice', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/krasnoyarsk', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/hk-mk-bled', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/voronezh', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/evansville-thunderbolts', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/kansas-city', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/mikhaylov-academy-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/karpat-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/reaktor', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/frölunda', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/ilves-tampere', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/fps', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/sapko', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/lukko-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/kapitan', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/technika-brno-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/oshawa-generals', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/brasov', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/technika-brno', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/snezhnye-medvedi', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/kaltern', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/poitiers-ducs', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/žilina', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/ravensburg', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/russia', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/alleghe', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/temirtau', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/queens', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/kingston-frontenacs', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/saint-marys', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/ticino-rockets', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/everest', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/lida', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/metz', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/fribourg-gottéron', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/thailand-magna', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/zvolen-hkm', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/syracuse-crunch', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/carleton', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/gladiator', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/křemenchuk', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/loko-junior', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/kharkiv', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/yunost-minsk', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/germany', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/sibir-novosibirsk', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/vsetín', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/litoměřice', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/israel-herzliya-pioneers', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/beibarys-atyrau', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/academy-zug', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/hc-lausanne', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/moncton-wildcats', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/avto', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/bystrye-rysi', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/boston-fleet', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/colgate-university', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/cheboksary', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/k-vantaa-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/chetyre-ledokola', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/blain-bois-brisbane', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/belfast', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/calgary-hitmen', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/shest-trolley', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/atlant-minsk-ii', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/jukurit-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/montr-al-canadiens', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/krakow', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/jihlava', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/croatia-khl-medve-ak-ii', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/auckland-mako', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/aik-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/yokohama-grits', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/dinamo-minsk', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/chicago-steel', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/dnipro-kherson', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/tolzer-lowen', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/northeastern-university', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/eppan', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/chicoutimi-saguen-es', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/mercyhurst-university', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/hk-olimp', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/boston-bruins', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/ledoviy-desant', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/tours', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/polot', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/mulhouse', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/kookoo-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/meudon', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/krasnye-kryliya', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/belleville-bulls', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/brandon-wheat-kings', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/connecticut-whale-w', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/rit', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/toronto-six', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/kings-town', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/slovakia-u18', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/florida-panthers', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/dynamo-moscow', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/red-deer-rebels', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/châlons', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/united-arab-emirates-abu-dhabi-storms', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/brazil-ozone', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/jokerit-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/sherbrooke-phoenix', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/ohio-state-buckeyes', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/jht', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/vita-hästen', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/vityaz-podolsk', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/qu-bec-remparts', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/kettera', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/villard', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/moose-jaw-warriors', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/south-korea', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/hc-v-tkovice-ridera', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/norway', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/västerås-ik', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/university-of-massachusetts-amherst', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/lehigh-valley-phantoms', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/kaunas-baltu-ainiai', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/granby-pr-dateurs', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/charlotte-checkers', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/tuto-hockey', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/leksands-if-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/huttwil', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/worcester-railers', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/erie-otters', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/utah-grizzlies', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/north-bay-battalion', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/masaryk-university', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/tonsberg', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/minnesota-pwhl', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/kansas-city-mavericks', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/visp', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/soligorsk', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/dab', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/nottingham', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/university-of-nebraska-omaha', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/indy-fuel', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/chetyre-ronina', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/acadie-bathurst-titan', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/jaca', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/tampa-bay-lightning', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/valenciennes', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/ottawa-pwhl', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/újpest-te', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/rouen', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/ritten', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/almtuna', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/frederikshavn', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/university-of-wisconsin', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/laser-ht', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/vitebsk', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/sparta-sarpsborg', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/serbia-hk-vojvodina-novi-sad', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/united-arab-emirates-abu-dhabi-scorpions', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/carolina-thunderbirds', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/minnesota-state-mavericks', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/bietigheim-steelers', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/koovee-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/belgorod', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/brampton-steelheads', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/penticton-vees', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/brampton-beast', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/kalamazoo-wings', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/sakhalinskie-akuly', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/straubing-tigers', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/cincinnati-cyclones', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/sioux-falls-stampede', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/new-york-rangers', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/buzadam', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/mhk-ryazan', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/sault-ste-marie-greyhounds', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/kosice', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/hc-litv-nov', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/narva-psk', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/huntsville-havoc', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/dallas-stars', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/zürich-lions', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/cbr-brave', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/raahek', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/rapid-city-rush', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/hc-biel-bienne', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/nidaros', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/val-pusteria-hc', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/guor-karelia', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/deac', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/nashville-predators', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/manchester-storm', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/philippines-manila-bearcats', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/south-korea-hl-anyang', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/avtomobilist-yekaterinburg', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/san-diego-gulls', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/watertown-wolves', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/kelowna-rockets', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/tappara-tampere', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/chile-black-star', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/quinnipiac-university', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/hc-energie-karlovy-vary', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/hc-olomouc', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/basel', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/cavaliers-brno', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/hifk-helsinki', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/st-thomas-university', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/banská-bystrica', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/chernye-grifony', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/minnesota-frost', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/lausanne', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/gatineau-olympiques', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/utah-hockey-club', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/florida-everblades', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/chiavenna', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/winterthur', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/avangard-omsk', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/thailand-canstars-red', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/greenville-swamp-rabbits', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/kalininsky-front', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/ehc-kloten', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/uoit', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/university-of-denver', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/benatky', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/aik', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/boston-college', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/hc-sierre-annecy', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/iceland-umfk-esja', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/switzerland', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/sarnia-sting', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/neuchâtel-young-sprinters', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/laurier', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/ústí-nad-labem', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/ifk-helsingfors-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/mexico-teotihuacan-priests', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/hong-kong-hk-chiefs', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/ässät-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/detva', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/winnipeg-jets', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/poland', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/st-cloud-state-huskies', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/muik-hockey', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/newfoundland-growlers', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/japan', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/toronto-marlies', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/university-of-new-hampshire', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/cortina', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/yermak-angarsk', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/usa-hockey-national-team-development-program', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/bilyi-bars', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/lethbridge-hurricanes', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/thunderbirds', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/slovan-bratislava-hc', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/university-of-maine', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/lincoln-stars', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/admiral-vladivostok', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/minnesota-wild', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/latvia', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/providence-bruins', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/pensacola-ice-flyers', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/k-rp-t-oulu', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/ak-bars-kazan', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/katowice', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/decin-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/dinamo-576', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/linköping-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/kristall-saratov', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/brazil-sociedad-hipica-de-campinas', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/west-auckland-admirals', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/grüner', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/hc-vipers', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/sheffield', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/karlskrona-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/hc-sochi', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/mexico-mayan-astronomers', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/croatia-khl-kuna-zagreb', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/küzneцkie-medvedi', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/kassel', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/lausanne-hc', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/israel-jerusalem-capitals', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/prince-albert-raiders', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/atlanta-gladiators', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/chaika', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/ryerson', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/baranavichy', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/calgary-flames', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/canada-east-u19', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/hong-kong-hc-kunlun-red-star-swot', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/canada-u18-w', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/clémenas', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/brantford-bulldogs', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/courchevel', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/augustana-vikings', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/merano', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/alaska-nanooks', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/cool-fm-st-georges', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/berezinskye-lisy', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/air-force-falcons', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/adler-mannheim-u19', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/akm-junior', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/blue-ridge-bobcats', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/acroni-jesenice-ii', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/brezno', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/bregenzerwald', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/bowling-green-falcons', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/black-wings-linz', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/levice', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/belgium-w', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/belgium-u18-w', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/central-coast-rhinos', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/bülach', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/bosnia-herzegovina-u18', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/bsfk', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/arlanda', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/colmar', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/chotěboř', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/amnéville', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/avignon', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/bratislava', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/burgdorf', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/andorra', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/brezno-b', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/armeyets-murmansk', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/calgary-wranglers', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/marseille', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/bolzano', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/china-u18', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/china-w', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/budapest-akademia-u21', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/åmåls', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/alvesta', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/buran-voronezh', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/björklöven-w', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/netherlands', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/muskegon-lumberjacks', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/canisius-college', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/sc-bern', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/carolina-hurricanes', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/bentley-university', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/dizelist', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/gyergyoi', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/ringerike', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/sacred-heart-university', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/israel-puckempire-holon-vipers', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/waterloo-black-hawks', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/frisk-asker', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/sinie-tigry', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/nantes', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/dubnica', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/plzeň', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/allen-americans', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/hc-kometa-brno', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/anaheim-ducks', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/slovan-bratislava', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/university-of-minnesota', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/almaty', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/everett-silvertips', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/slovakia', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/ambrì-piotta', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/ottawa-67-s', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/tambov', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/manitoba-moose', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/china', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/germany-u17', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/italy', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/united-arab-emirates-al-ain-theebs', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/guelph-storm', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/hc-davos', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/orlando-solar-bears', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/regina-pats', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/lake-superior-state-university', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/schwenninger-wild-wings', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/bakersfield-condors', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/wichita-thunder', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/iserlohn-roosters', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/metallurg-magnitogorsk', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/san-jose-barracuda', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/düsseldorf', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/sudbury-wolves', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/jokerit', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/krasnoyarskie-rysi', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/nice-hockey-côte-d’azur', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/sioux-city-musketeers', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/idaho-steelheads', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/yukselis', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/dynamo-riga', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/philippines-manila-chiefs', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/kokshetau', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/severstal-cherepovets', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/new-jersey-devils', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/buffalo-sabres', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/columbus-blue-jackets', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/macon-mayhem', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/adirondack-thunder', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/colorado-avalanche', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/bulgaria-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/bulgaria-w', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/baton-rouge', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/chomutov-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/hermes', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/cana', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/chinese-taipei-univ-w', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/canada-univ-women', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/bäcken', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/academy-pilsen', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/peoria-rivermen', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/bodens', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/american-international', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/chinese-taipei-u18-w', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/bulgaria', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/argovia-stars', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/bentley-falcons', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/concordia-edmonton', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/chemnitz', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/chinese-taipei-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/canada-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/denmark-u18-w', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/austria-u18', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/canada-w', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/chur', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/denver-pioneers', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/australia-w', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/davos-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/budapest-akademia-2', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/dijon', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/deac-2', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/anna-maria', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/brive', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/bardejov', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/annecy', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/aosta', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/boden', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/aquacity-pikes', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/denmark-w', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/canada-white-u17', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/costa-rica-costa-rica-national-ice-hockey-team', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/české-budějovice-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/belgium', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/croatia-w', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/austria-w', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/athens-rock-lobsters', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/canada-u18', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/black-dogs-budweis', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/chernyshev-division', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/djurgården-w', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/canada-red-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/chinese-taipei', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/dortmund', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/croatia-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/denmark-u18', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/canisius', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/dubnica-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/boston-w', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/besançon', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/clermont-ferrand', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/canisius-golden-griffins', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/boras', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/caen', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/aichyna-minsk', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/brynäs-women', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/bosnia-herzegovina', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/brown-bears', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/cheb', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/china-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/bosnia-herzegovina-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/canada-west-u19', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/akm-novomoskovsk', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/druzhkovka', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/chinese-taipei-u18', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/belarus-u17', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/brisbane-lightning', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/bergen', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/bílina', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/dizel', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/clarkson-golden-knights', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/bahrain', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/dornbirn', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/canada-univ', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/bo-ostrava', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/champigny-sur-marne', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/canada-black-u17', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/bulgaria-u18', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/canada-red-u17', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/binghamton-black-bears', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/chinese-taipei-w', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/bobrov-division', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/dolny-kubin', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/croatia-u18', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/atlant-minsk', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/biloxi-breakers', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/denmark-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/diez-limburg', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/denmark-b', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/cholet', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/dukla-trencin-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/bosnia-and-herzegovina-bosnia-and-herzegovina-national-ice-hockey-team', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/dresdner-eislowen-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/bloomington-bison', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/adler-mannheim-u17', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/budaynik-minsk', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/assumption', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/deggendorf', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/bulle-la-gruyère', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/croatia', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/deggendorfer', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/chrudim', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/cayyolu-gordion', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/dielsdorf-niederhasli', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/dudingen', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/cornell-big-red', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/austria-u19', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/compiègne', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/dalen', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/arosa', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/decin', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/australia', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/courbevoie', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/army-black-knights', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/björklöven-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/čzu-farmers-praha', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/austria-u16', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/bosnia-herzegovina-w', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/buran-moscow', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/corgemont', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/austria-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/dinslaken-kobras', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/chambery', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/budapest-akademia', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/bern-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/aik-w', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/3l-rivière-du-loup', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/andorra-andorra-national-ice-hockey-team', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/břeclav', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/bataillon-st-hyacinthe', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/dalen-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/bulgaria-u18-w', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/brödernasväsby', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/china-u18-w', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/alaska-anchorage', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/boston-pride-w', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/bytom', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/borlänge', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/arktika', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/chrudim-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/calgary', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/armenia', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/crocodiles-hamburg', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/colgate-raiders', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/ambrì-piotta-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/assurancia-thetford', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/canada-white-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/czech-republic-u18-w', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/almtuna-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/connecticut-huskies', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/dartmouth-big-green', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/buchloe', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/akm', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/arboga', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/hc-koda-plze', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/cape-breton-eagles', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/hamilton-bulldogs', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/rochester-americans', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/tps-turku-women', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/new-york-sirens', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/ottawa-charge', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/cornell-university', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/glasgow-clan', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/cleveland-monsters', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/amur-khabarovsk', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/utica-comets', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/philadelphia-flyers', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/tucson-roadrunners', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/prince-george-cougars', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/st-cloud-state-university', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/stoczniowiec-gdansk', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/chicoutimi-saguenees', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/augustana-university', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/kalpa-kuopio', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/rensselaer-polytechnic-institute', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/kalpa-u20', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/new-york-pwhl', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/jokerit-helsinki', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/austria', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/minnesota-state-university', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/cedar-rapids-roughriders', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/rimouski-oc-anic', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/saskatoon-blades', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/adler-mannheim', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/bemidji-state-university', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/maine-mariners', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/hc-zubr-p-erov', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/springfield-thunderbirds', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/texas-stars', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/ryt-i-kladno', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/new-york-islanders', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/saginaw-spirit', destination: '/directory/teams', permanent: true },
      // Missing-slug -> /directory/teams listing (12 redirects; 3 UUID test-data slugs removed).
      // No DB match found (UUIDs, test data, diacritics, renames).
      // Listing is the destination.
      { source: '/directory/teams/ska-neva-st-petersburg', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/test-team-seed', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/malm-redhawks', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/eisb-ren-m-nchen', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/orebro-hk', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/ss-t-pori', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/v-xj-lakers', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/barys-nur-sultan', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/lule-hf', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/ska-st-petersburg', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/d-sseldorfer-eg', destination: '/directory/teams', permanent: true },
      { source: '/directory/teams/abbottford-canucks', destination: '/directory/teams', permanent: true },
    ];
  },
};
module.exports = nextConfig;
