import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Hockey Shooting Guide - Wrist Shot, Snap Shot, Slap Shot, Backhand, and How to Score',
  description: 'Everything you need to know about hockey shooting: the four main shot types, mechanics of each, how to pick a corner, the release, follow-through, and the shooting drills that build a hard, accurate shot.',
  openGraph: {
    title: 'Hockey Shooting Guide',
    description: 'Wrist shot, snap shot, slap shot, backhand - mechanics, accuracy tips, and the drills that build them.',
    type: 'article',
  },
  alternates: { canonical: 'https://rinkstop.com/guides/shooting' },
};

export default function ShootingGuide() {
  return (
    <div style={{ maxWidth: '860px', margin: '0 auto', padding: '0.75rem 1rem 4rem' }}>
      <nav style={{ fontSize: '0.75rem', color: '#555', marginBottom: '1rem' }}>
        <Link href="/">Home</Link>
        <span style={{ margin: '0 0.4rem' }}>›</span>
        <Link href="/guides" style={{ color: '#555' }}>Guides</Link>
        <span style={{ margin: '0 0.4rem' }}>›</span>
        <span style={{ color: '#A0A0A0' }}>Shooting</span>
      </nav>
      <span style={{ display: 'inline-block', fontSize: '0.5625rem', fontWeight: 800, letterSpacing: '0.12em', textTransform: 'uppercase', padding: '0.2rem 0.6rem', borderRadius: '4px', background: 'rgba(200,16,46,0.12)', color: '#C8102E', marginBottom: '0.75rem' }}>Guide</span>
      <h1 style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: 'clamp(2rem, 5vw, 2.75rem)', color: '#fff', letterSpacing: '0.04em', lineHeight: 1, margin: '0 0 0.75rem' }}>HOCKEY SHOOTING GUIDE</h1>
      <p style={{ color: 'rgba(255,255,255,0.4)', fontSize: '0.9375rem', lineHeight: 1.6, marginBottom: '1.5rem' }}>The four shots every hockey player should master - wrist, snap, slap, backhand - and the mechanics, accuracy tips, and drills that build them.</p>

      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ '@context': 'https://schema.org', '@type': 'Article', headline: 'Hockey Shooting Guide', description: 'Wrist shot, snap shot, slap shot, backhand - mechanics, accuracy tips, and the drills that build them.', author: { '@type': 'Organization', name: 'RinkStop' }, publisher: { '@type': 'Organization', name: 'RinkStop', url: 'https://rinkstop.com' }, datePublished: '2026-08-11' }) }} />

      <section style={{ marginBottom: '2.5rem' }}>
        <h2 style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: '1.5rem', color: '#fff', letterSpacing: '0.04em', marginBottom: '1rem' }}>THE FOUR MAIN SHOTS</h2>
        <p style={{ color: '#aaa', lineHeight: 1.75, marginBottom: '1rem', fontSize: '0.9375rem' }}>Every hockey shot is a variation of four basic shot types. Mastering all four gives a player a complete offensive toolkit:</p>
        <div style={{ display: 'grid', gap: '0.75rem' }}>
          {[
            { name: 'Wrist shot', speed: '60-85 mph (NHL avg)', accuracy: 'Highest', desc: 'The most versatile and accurate shot. The puck is loaded with energy through a sweeping motion of the stick blade, then released with a quick wrist snap. Used everywhere on the ice.' },
            { name: 'Snap shot', speed: '75-95 mph (NHL avg)', accuracy: 'Moderate-High', desc: 'A compact, quick-release shot. The stick travels only a few inches before release, with velocity generated by rapid wrist rotation. The dominant one-timer shot in the modern NHL.' },
            { name: 'Slap shot', speed: '90-108 mph (NHL avg, top end)', accuracy: 'Lowest', desc: 'The hardest shot in hockey. The player takes a full wind-up before striking the puck, transferring energy from the swing into the puck. Less accurate but extremely difficult to stop when on target.' },
            { name: 'Backhand', speed: '50-80 mph (NHL avg)', accuracy: 'High in close', desc: 'The most underrated shot. Modern NHL players use the backhand as a primary scoring weapon in tight to the net. Often more accurate than the forehand at close range.' },
          ].map((row, i) => (
            <div key={i} style={{ background: 'var(--s2)', border: '1px solid var(--border)', borderRadius: '6px', padding: '0.875rem 1.125rem' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', gap: '0.5rem', flexWrap: 'wrap', marginBottom: '0.4rem' }}>
                <h3 style={{ color: '#fff', fontSize: '1rem', fontWeight: 700, margin: 0 }}>{row.name}</h3>
                <span style={{ color: 'rgba(255,255,255,0.4)', fontSize: '0.8125rem' }}>{row.speed}</span>
              </div>
              <p style={{ color: 'rgba(255,255,255,0.7)', fontSize: '0.8125rem', lineHeight: 1.55, margin: '0 0 0.4rem' }}><strong style={{ color: '#fff' }}>Accuracy:</strong> {row.accuracy}</p>
              <p style={{ color: 'rgba(255,255,255,0.7)', fontSize: '0.875rem', lineHeight: 1.55, margin: 0 }}>{row.desc}</p>
            </div>
          ))}
        </div>
      </section>

      <section style={{ marginBottom: '2.5rem' }}>
        <h2 style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: '1.5rem', color: '#fff', letterSpacing: '0.04em', marginBottom: '1rem' }}>THE WRIST SHOT MECHANICS</h2>
        <p style={{ color: '#aaa', lineHeight: 1.75, marginBottom: '1rem', fontSize: '0.9375rem' }}>The wrist shot is the foundation of every other shot. Players who haven\'t mastered the wrist shot typically struggle with the snap shot and slap shot as well.</p>
        <ol style={{ color: '#aaa', lineHeight: 1.7, fontSize: '0.9375rem', paddingLeft: '1.5rem', marginBottom: '1.5rem' }}>
          <li style={{ marginBottom: '0.5rem' }}>Position the puck slightly behind your back foot at a 90-degree angle to your body</li>
          <li style={{ marginBottom: '0.5rem' }}>Cup the puck with the blade. The toe of the blade should curl around the back of the puck.</li>
          <li style={{ marginBottom: '0.5rem' }}>Drag the puck forward, loading energy as the blade flexes against the ice</li>
          <li style={{ marginBottom: '0.5rem' }}>Release with a quick snap of the wrist. The blade closes against the puck.</li>
          <li style={{ marginBottom: '0.5rem' }}>Follow through toward the target, keeping the blade pointed where you want the puck to go</li>
          <li style={{ marginBottom: '0.5rem' }}>Weight transfers from the back leg to the front leg through the shot</li>
        </ol>
        <p style={{ color: '#aaa', lineHeight: 1.75, marginBottom: '1rem', fontSize: '0.9375rem' }}>The mistake most beginners make: pushing the puck instead of snapping it. Pushing produces a slow, easy-to-save shot. Snapping transfers the energy from the stick blade through the puck in a fraction of a second.</p>
      </section>

      <section style={{ marginBottom: '2.5rem' }}>
        <h2 style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: '1.5rem', color: '#fff', letterSpacing: '0.04em', marginBottom: '1rem' }}>SNAP SHOT VS SLAP SHOT</h2>
        <p style={{ color: '#aaa', lineHeight: 1.75, marginBottom: '1rem', fontSize: '0.9375rem' }}>The snap shot and slap shot both generate high velocity, but through very different mechanics:</p>
        <div style={{ display: 'grid', gap: '0.75rem' }}>
          {[
            { name: 'Snap shot', pros: 'Faster release. Harder for goalies to track.', cons: 'Lower peak velocity than slap shot', desc: 'Stick travels only a few inches. Velocity comes from rapid wrist rotation and blade flex. Ideal for one-timers, tight spaces, and quick releases in traffic.' },
            { name: 'Slap shot', pros: 'Highest possible velocity', cons: 'Longer load time. Easier for goalies to track.', desc: 'Stick drawn back above the shoulder for a full wind-up. Energy transfers through the swing and into the puck at contact. Used from the point on power plays.' },
          ].map((row, i) => (
            <div key={i} style={{ background: 'var(--s2)', border: '1px solid var(--border)', borderRadius: '6px', padding: '0.875rem 1.125rem' }}>
              <div style={{ marginBottom: '0.4rem' }}>
                <h3 style={{ color: '#fff', fontSize: '1rem', fontWeight: 700, margin: 0 }}>{row.name}</h3>
              </div>
              <p style={{ color: 'rgba(255,255,255,0.7)', fontSize: '0.8125rem', lineHeight: 1.55, margin: '0 0 0.4rem' }}><strong style={{ color: '#fff' }}>Pros:</strong> {row.pros}. <strong style={{ color: '#fff' }}>Cons:</strong> {row.cons}.</p>
              <p style={{ color: 'rgba(255,255,255,0.7)', fontSize: '0.875rem', lineHeight: 1.55, margin: 0 }}>{row.desc}</p>
            </div>
          ))}
        </div>
      </section>

      <section style={{ marginBottom: '2.5rem' }}>
        <h2 style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: '1.5rem', color: '#fff', letterSpacing: '0.04em', marginBottom: '1rem' }}>SHOOTING DRILLS</h2>
        <p style={{ color: '#aaa', lineHeight: 1.75, marginBottom: '1rem', fontSize: '0.9375rem' }}>A consistent shooting practice routine will accelerate development more than any other skill work. The most effective drills:</p>
        <div style={{ display: 'grid', gap: '0.75rem' }}>
          {[
            { name: 'Target practice', desc: 'Place small targets (water bottles, taped squares, hole targets) in each corner of the net. Shoot 10 reps from each corner of the offensive zone. Aim for 70%+ accuracy.' },
            { name: 'One-timers', desc: 'Pass the puck off the boards to yourself and shoot in stride without stopping the puck. Builds hand-eye coordination and quick-release mechanics.' },
            { name: 'Shoot in stride', desc: 'Start skating from the hash marks, shoot from in motion. Shooting while moving transfers practice to game situations.' },
            { name: 'Off-ice shooting pad', desc: 'Synthetic shooting tiles or a shooting pad at home allow hundreds of reps per week. The blade flex and puck contact feel are nearly identical to ice.' },
            { name: 'Snap shot reps', desc: 'From a stationary position, practice the snap shot. Small stick motion, fast release. 50+ reps per session builds the muscle memory.' },
          ].map((row, i) => (
            <div key={i} style={{ background: 'var(--s2)', border: '1px solid var(--border)', borderRadius: '6px', padding: '0.875rem 1.125rem' }}>
              <div style={{ marginBottom: '0.4rem' }}>
                <h3 style={{ color: '#fff', fontSize: '1rem', fontWeight: 700, margin: 0 }}>{row.name}</h3>
              </div>
              <p style={{ color: 'rgba(255,255,255,0.7)', fontSize: '0.875rem', lineHeight: 1.55, margin: 0 }}>{row.desc}</p>
            </div>
          ))}
        </div>
      </section>

      <section style={{ marginBottom: '2.5rem' }}>
        <h2 style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: '1.5rem', color: '#fff', letterSpacing: '0.04em', marginBottom: '1rem' }}>SHOOTING IN GAME SITUATIONS</h2>
        <p style={{ color: '#aaa', lineHeight: 1.75, marginBottom: '1rem', fontSize: '0.9375rem' }}>The best shooters combine mechanics with smart situational play. The most common in-game shooting scenarios:</p>
        <ul style={{ color: '#aaa', lineHeight: 1.7, fontSize: '0.9375rem', paddingLeft: '1.25rem' }}>
          <li style={{ marginBottom: '0.5rem' }}><strong style={{ color: '#fff' }}>Slot shot:</strong> The most common scoring location. Quick wrist or snap shot, placed top corner or five-hole before the goalie can set.</li>
          <li style={{ marginBottom: '0.5rem' }}><strong style={{ color: '#fff' }}>One-timer:</strong> The puck is passed to a player in motion, who shoots without stopping it. Hardest shot for a goalie to track.</li>
          <li style={{ marginBottom: '0.5rem' }}><strong style={{ color: '#fff' }}>Point shot:</strong> Defensemen shooting from the blue line. Usually a slap shot aimed at traffic in front of the net.</li>
          <li style={{ marginBottom: '0.5rem' }}><strong style={{ color: '#fff' }}>Wraparound:</strong> Skating behind the net and tucking the puck around the goalpost. Low percentage but effective against over-committed goalies.</li>
          <li style={{ marginBottom: '0.5rem' }}><strong style={{ color: '#fff' }}>Backhand tuck:</strong> The most-used in-tight shot. The puck is on the backhand, pulled across the body and tucked inside the post.</li>
        </ul>
      </section>

      <section style={{ marginBottom: '2.5rem' }}>
        <h2 style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: '1.5rem', color: '#fff', letterSpacing: '0.04em', marginBottom: '1rem' }}>RELATED GUIDES</h2>
        <ul style={{ color: '#aaa', lineHeight: 1.7, fontSize: '0.9375rem', paddingLeft: '1.25rem' }}>
          <li style={{ marginBottom: '0.4rem' }}><Link href="/guides/hockey-stick-guide" style={{ color: '#C8102E' }}>Hockey Stick Guide</Link></li>
          <li style={{ marginBottom: '0.4rem' }}><Link href="/guides/skating" style={{ color: '#C8102E' }}>Hockey Skating Guide</Link></li>
          <li style={{ marginBottom: '0.4rem' }}><Link href="/guides/off-ice-hockey-training" style={{ color: '#C8102E' }}>Off-Ice Training Guide</Link></li>
          <li style={{ marginBottom: '0.4rem' }}><Link href="/guides/hockey-positions" style={{ color: '#C8102E' }}>Hockey Positions Explained</Link></li>
        </ul>
      </section>
    </div>
  );
}
