// Auto-generated from /tmp/2026_picks.json (xlsx parse, 2026-06-30)
// 224 picks total — 223 real + 1 forfeit at #63 (Vegas Golden Knights)
import type { PickStats } from './types';
export interface Pick {
  pick: number;
  round: number;
  team: string;
  player: string;
  position: string;
  league: string;
  nationality: string;
}

export const PICKS_2026: Pick[] = [
  { pick: 1, round: 1, team: 'Toronto Maple Leafs', player: 'Gavin McKenna', position: 'LW', league: 'Penn State (NCAA)', nationality: 'CAN' },
  { pick: 2, round: 1, team: 'San Jose Sharks', player: 'Ivar Stenberg', position: 'LW', league: 'Frolunda (SWE)', nationality: 'SWE' },
  { pick: 3, round: 1, team: 'Vancouver Canucks', player: 'Caleb Malhotra', position: 'C', league: 'Brantford (OHL)', nationality: 'CAN' },
  { pick: 4, round: 1, team: 'Buffalo Sabres (from Chicago)', player: 'Daxon Rudolph', position: 'D', league: 'Prince Albert (WHL)', nationality: 'CAN' },
  { pick: 5, round: 1, team: 'New York Rangers', player: 'Alberts Smits', position: 'D', league: 'Munchen (GER) / Jukurit (Liiga)', nationality: 'LAT' },
  { pick: 6, round: 1, team: 'Calgary Flames', player: 'Carson Carels', position: 'D', league: 'Prince George (WHL)', nationality: 'CAN' },
  { pick: 7, round: 1, team: 'Seattle Kraken', player: 'Chase Reid', position: 'D', league: 'Sault Ste. Marie (OHL)', nationality: 'USA' },
  { pick: 8, round: 1, team: 'Winnipeg Jets', player: 'Viggo Bjorck', position: 'C', league: 'Djurgarden (SWE)', nationality: 'SWE' },
  { pick: 9, round: 1, team: 'San Jose Sharks (from Florida)', player: 'Keaton Verhoeff', position: 'D', league: 'North Dakota (NCAA)', nationality: 'CAN' },
  { pick: 10, round: 1, team: 'Nashville Predators', player: 'Wyatt Cullen', position: 'LW', league: 'USA U-18 (NTDP-USHL)', nationality: 'USA' },
  { pick: 11, round: 1, team: 'St. Louis Blues', player: 'Tynan Lawrence', position: 'C', league: 'Boston University (Hockey East)', nationality: 'CAN' },
  { pick: 12, round: 1, team: 'New Jersey Devils', player: 'Alexander Command', position: 'C', league: 'Orebro Jr. (SWE-JR)', nationality: 'SWE' },
  { pick: 13, round: 1, team: 'New York Islanders', player: 'Malte Gustafsson', position: 'D', league: 'HV71 (SWE)', nationality: 'SWE' },
  { pick: 14, round: 1, team: 'Columbus Blue Jackets', player: 'Oscar Hemming', position: 'LW', league: 'Boston College (NCAA)', nationality: 'FIN' },
  { pick: 15, round: 1, team: 'Anaheim Ducks (from Detroit via St. Louis)', player: 'Nikita Klepov', position: 'RW', league: 'Saginaw (OHL)', nationality: 'USA' },
  { pick: 16, round: 1, team: 'St. Louis Blues', player: 'Maddox Dagenais', position: 'C', league: 'Quebec (QMJHL)', nationality: 'CAN' },
  { pick: 17, round: 1, team: 'Utah Mammoth (from LA Kings)', player: 'Ethan Belchetz', position: 'LW', league: 'Windsor (OHL)', nationality: 'CAN' },
  { pick: 18, round: 1, team: 'Washington Capitals (from Anaheim)', player: 'Oliver Suvanto', position: 'C', league: 'Tappara (FIN)', nationality: 'FIN' },
  { pick: 19, round: 1, team: 'Los Angeles Kings (from Utah)', player: 'Elton Hermansson', position: 'RW', league: 'MoDo (SWE-2)', nationality: 'SWE' },
  { pick: 20, round: 1, team: 'Buffalo Sabres (from Edmonton/San Jose)', player: 'Ilia Morozov', position: 'C', league: 'Miami (NCAA)', nationality: 'RUS' },
  { pick: 21, round: 1, team: 'San Jose Sharks (from Buffalo)', player: 'Ryan Lin', position: 'D', league: 'Vancouver (WHL)', nationality: 'CAN' },
  { pick: 22, round: 1, team: 'Pittsburgh Penguins', player: 'Liam Ruck', position: 'RW', league: 'Medicine Hat (WHL)', nationality: 'CAN' },
  { pick: 23, round: 1, team: 'Detroit Red Wings (from St. Louis)', player: 'JP Hurlbert', position: 'LW', league: 'Kamloops (WHL)', nationality: 'USA' },
  { pick: 24, round: 1, team: 'Vancouver Canucks (from Minnesota)', player: 'Adam Novotny', position: 'LW', league: 'Peterborough (OHL)', nationality: 'CZE' },
  { pick: 25, round: 1, team: 'Ottawa Senators (from Tampa Bay/Seattle/Florida)', player: 'Jonas Lagerberg Hoen', position: 'RW', league: 'Leksand Jr. (SWE-JR)', nationality: 'SWE' },
  { pick: 26, round: 1, team: 'Montreal Canadiens (from NY Rangers via Vegas)', player: 'Gleb Pugachyov', position: 'RW', league: 'Nizhny Novgorod Jr. (RUS-JR)', nationality: 'KAZ' },
  { pick: 27, round: 1, team: 'Philadelphia Flyers (from San Jose)', player: 'Maksim Sokolovskii', position: 'D', league: 'London (OHL)', nationality: 'KAZ' },
  { pick: 28, round: 1, team: 'Anaheim Ducks (from Montreal via Vegas)', player: 'Marcus Nordmark', position: 'LW', league: 'Djurgarden Jr. (SWE-JR)', nationality: 'SWE' },
  { pick: 29, round: 1, team: 'Vegas Golden Knights (from St. Louis via Anaheim)', player: 'Juho Piiparinen', position: 'D', league: 'Tappara (FIN)', nationality: 'FIN' },
  { pick: 30, round: 1, team: 'Calgary Flames (from Vegas)', player: 'Jack Hextall', position: 'C', league: 'Youngstown (USHL)', nationality: 'USA' },
  { pick: 31, round: 1, team: 'Nashville Predators (from Carolina)', player: 'Tommy Bleyl', position: 'D', league: 'Moncton (QMJHL)', nationality: 'USA' },
  { pick: 32, round: 1, team: 'Ottawa Senators', player: 'Jaxon Cover', position: 'RW', league: 'London (OHL)', nationality: 'CAY' },
  { pick: 33, round: 2, team: 'Vancouver Canucks', player: 'Brooks Rogowski', position: 'C', league: 'Oshawa (OHL)', nationality: 'USA' },
  { pick: 34, round: 2, team: 'Chicago Blackhawks', player: 'Xavier Villeneuve', position: 'D', league: 'Blainville-Boisbriand (QMJHL)', nationality: 'CAN' },
  { pick: 35, round: 2, team: 'Chicago Blackhawks', player: 'Ryan Roobroeck', position: 'LW', league: 'Niagara (OHL)', nationality: 'CAN' },
  { pick: 36, round: 2, team: 'Calgary Flames', player: 'Chase Harrington', position: 'LW', league: 'Spokane (WHL)', nationality: 'CAN' },
  { pick: 37, round: 2, team: 'New Jersey Devils', player: 'Matias Vanhanen', position: 'LW', league: 'Everett (WHL)', nationality: 'FIN' },
  { pick: 38, round: 2, team: 'Seattle Kraken', player: 'Casey Mutryn', position: 'RW', league: 'USA U-18 (NTDP-USHL)', nationality: 'USA' },
  { pick: 39, round: 2, team: 'Pittsburgh Penguins', player: 'Markus Ruck', position: 'C', league: 'Medicine Hat (WHL)', nationality: 'CAN' },
  { pick: 40, round: 2, team: 'Florida Panthers', player: 'Simas Ignatavicius', position: 'RW', league: 'Geneve (NL)', nationality: 'USA' },
  { pick: 41, round: 2, team: 'Vancouver Canucks', player: 'Niklas Aaram-Olsen', position: 'LW', league: 'Orebro (SHL)', nationality: 'NOR' },
  { pick: 42, round: 2, team: 'Calgary Flames', player: 'Tobias Trejbal', position: 'G', league: 'Youngstown (USHL)', nationality: 'CZE' },
  { pick: 43, round: 2, team: 'Colorado Avalanche', player: 'Egor Shilov', position: 'C', league: 'Victoriaville (QMJHL)', nationality: 'RUS' },
  { pick: 44, round: 2, team: 'New Jersey Devils', player: 'Nikita Shcherbakov', position: 'D', league: 'Ufa (MHL)', nationality: 'RUS' },
  { pick: 45, round: 2, team: 'Anaheim Ducks', player: 'Jayden Kurtz', position: 'D', league: 'Rogers (US-HS)', nationality: 'USA' },
  { pick: 46, round: 2, team: 'Los Angeles Kings', player: 'Liam Lefebvre', position: 'C', league: 'Chicoutimi (QMJHL)', nationality: 'CAN' },
  { pick: 47, round: 2, team: 'Detroit Red Wings', player: 'Victor Plante', position: 'LW', league: 'USA U-18 (NTDP-USHL)', nationality: 'USA' },
  { pick: 48, round: 2, team: 'Florida Panthers', player: 'Ryder Cali', position: 'C', league: 'North Bay (OHL)', nationality: 'SUI' },
  { pick: 49, round: 2, team: 'Los Angeles Kings', player: 'Adam Goljer', position: 'D', league: 'Trencin (Extraliga)', nationality: 'SVK' },
  { pick: 50, round: 2, team: 'Anaheim Ducks', player: 'Mathis Preston', position: 'RW', league: 'Vancouver (WHL)', nationality: 'CAN' },
  { pick: 51, round: 2, team: 'Carolina Hurricanes', player: 'William Hakansson', position: 'D', league: 'Lulea (SHL)', nationality: 'SWE' },
  { pick: 52, round: 2, team: 'Tampa Bay Lightning', player: 'Oleg Kulebiakin', position: 'RW', league: 'Halifax (QMJHL)', nationality: 'RUS' },
  { pick: 53, round: 2, team: 'Philadelphia Flyers', player: 'Brek Liske', position: 'D', league: 'Everett (WHL)', nationality: 'CAN' },
  { pick: 54, round: 2, team: 'Pittsburgh Penguins', player: 'Tomas Galvas', position: 'D', league: 'Liberec (Extraliga)', nationality: 'CZE' },
  { pick: 55, round: 2, team: 'Calgary Flames', player: 'Alan Shaikhlislamov', position: 'RW', league: 'Ufa (MHL)', nationality: 'RUS' },
  { pick: 56, round: 2, team: 'Boston Bruins', player: 'Yuri Ivanov', position: 'G', league: 'Spartak (MHL)', nationality: 'RUS' },
  { pick: 57, round: 2, team: 'Montreal Canadiens', player: 'Timofei Runtso', position: 'D', league: 'Victoria (WHL)', nationality: 'USA' },
  { pick: 58, round: 2, team: 'Edmonton Oilers', player: 'Rudolfs Berzkalns', position: 'C', league: 'Muskegon (USHL)', nationality: 'LAT' },
  { pick: 59, round: 2, team: 'Dallas Stars', player: 'Jakub Vanecek', position: 'D', league: 'Tri-City (WHL)', nationality: 'CZE' },
  { pick: 60, round: 2, team: 'Toronto Maple Leafs', player: 'Alexander Bilecki', position: 'D', league: 'Kitchener (OHL)', nationality: 'CAN' },
  { pick: 61, round: 2, team: 'Carolina Hurricanes', player: 'Wiggo Sorensson', position: 'C', league: 'Boro (HockeyEttan)', nationality: 'SWE' },
  { pick: 62, round: 2, team: 'Philadelphia Flyers', player: 'Martin Psohlavec', position: 'G', league: 'Karlovy (Extraliga)', nationality: 'CZE' },
  { pick: 63, round: 2, team: 'Vegas Golden Knights', player: 'FORFEITED', position: '', league: '', nationality: '' },
  { pick: 64, round: 2, team: 'New York Rangers', player: 'Benjamin MacBeath', position: 'D', league: 'Calgary (WHL)', nationality: 'CAN' },
  { pick: 65, round: 3, team: 'Calgary Flames', player: 'Joe Iginla', position: 'RW', league: 'Vancouver (WHL)', nationality: 'CAN' },
  { pick: 66, round: 3, team: 'Chicago Blackhawks', player: 'Samu Alalauri', position: 'D', league: 'Pelicans (SM-sarja)', nationality: 'FIN' },
  { pick: 67, round: 3, team: 'New York Rangers', player: 'Danai Shaiikov', position: 'G', league: 'Gatineau (QMJHL)', nationality: 'KAZ' },
  { pick: 68, round: 3, team: 'Carolina Hurricanes', player: 'Zachary Lansard', position: 'RW', league: 'Regina (WHL)', nationality: 'CAN' },
  { pick: 69, round: 3, team: 'Toronto Maple Leafs', player: 'Ethan MacKenzie', position: 'D', league: 'Edmonton (WHL)', nationality: 'CAN' },
  { pick: 70, round: 3, team: 'Nashville Predators', player: 'Dmitri Borichev', position: 'G', league: 'Loko Yaroslavl (MHL)', nationality: 'RUS' },
  { pick: 71, round: 3, team: 'Winnipeg Jets', player: 'Samuel Hrenak', position: 'G', league: 'Fargo (USHL)', nationality: 'SVK' },
  { pick: 72, round: 3, team: 'Ottawa Senators', player: 'Adam Nemec', position: 'LW', league: 'Sudbury (OHL)', nationality: 'SVK' },
  { pick: 73, round: 3, team: 'Toronto Maple Leafs', player: 'Zach Olsen', position: 'RW', league: 'Saskatoon (WHL)', nationality: 'CAN' },
  { pick: 74, round: 3, team: 'Colorado Avalanche', player: 'Beckett Hamilton', position: 'C', league: 'Red Deer (WHL)', nationality: 'CAN' },
  { pick: 75, round: 3, team: 'St. Louis Blues', player: 'Luke Schairer', position: 'D', league: 'USA U-18 (NTDP-USHL)', nationality: 'USA' },
  { pick: 76, round: 3, team: 'Toronto Maple Leafs', player: 'Mans Gudmundsson', position: 'D', league: 'Farjestad (SHL)', nationality: 'SWE' },
  { pick: 77, round: 3, team: 'New York Rangers', player: 'Charlie Morrison', position: 'D', league: 'Quebec (QMJHL)', nationality: 'CAN' },
  { pick: 78, round: 3, team: 'Vancouver Canucks', player: 'Dmitri Ivchenko', position: 'G', league: 'Omsk (MHL)', nationality: 'RUS' },
  { pick: 79, round: 3, team: 'Detroit Red Wings', player: 'Michal Orsulak', position: 'G', league: 'Prince Albert (WHL)', nationality: 'CZE' },
  { pick: 80, round: 3, team: 'Los Angeles Kings', player: 'Blake Zielinski', position: 'C', league: 'Des Moines (USHL)', nationality: 'USA' },
  { pick: 81, round: 3, team: 'New York Rangers', player: 'Tomas Chrenko', position: 'C', league: 'Nitra (Extraliga)', nationality: 'SVK' },
  { pick: 82, round: 3, team: 'Anaheim Ducks', player: 'Rian Chudzinski', position: 'RW', league: 'Moncton (QMJHL)', nationality: 'USA' },
  { pick: 83, round: 3, team: 'Minnesota Wild', player: 'Adam Andersson', position: 'C', league: 'Leksands (SHL)', nationality: 'SWE' },
  { pick: 84, round: 3, team: 'Edmonton Oilers', player: 'Malcom Gastrin', position: 'LW', league: 'MoDo (HockeyAllsvenskan)', nationality: 'SWE' },
  { pick: 85, round: 3, team: 'Toronto Maple Leafs', player: 'Juuso Ainasto', position: 'G', league: 'Jokerit (Mestis)', nationality: 'FIN' },
  { pick: 86, round: 3, team: 'Pittsburgh Penguins', player: 'Pierce Mbuyi', position: 'LW', league: 'Owen Sound (OHL)', nationality: 'CAN' },
  { pick: 87, round: 3, team: 'Ottawa Senators', player: 'Oscar Holmertz', position: 'C', league: 'Linkoping (SHL)', nationality: 'SWE' },
  { pick: 88, round: 3, team: 'Boston Bruins', player: 'Nils Bartholdsson', position: 'RW', league: 'Rogle (SHL)', nationality: 'SWE' },
  { pick: 89, round: 3, team: 'Los Angeles Kings', player: 'Yegor Rybkin', position: 'G', league: 'Nizhny Novgorod (MHL)', nationality: 'RUS' },
  { pick: 90, round: 3, team: 'Tampa Bay Lightning', player: 'Tomas Kralovic', position: 'D', league: 'Bratislava (Extraliga)', nationality: 'SVK' },
  { pick: 91, round: 3, team: 'Ottawa Senators', player: 'Louis-Felix Bourque', position: 'RW', league: 'Drummondville (QMJHL)', nationality: 'CAN' },
  { pick: 92, round: 3, team: 'Vegas Golden Knights', player: 'Benjamin Wilmott', position: 'C', league: 'Barrie (OHL)', nationality: 'USA' },
  { pick: 93, round: 3, team: 'Montreal Canadiens', player: 'Cooper Cleaves', position: 'D', league: 'Dartmouth (NCAA)', nationality: 'USA' },
  { pick: 94, round: 3, team: 'Columbus Blue Jackets', player: 'Alessandro Di Iorio', position: 'C', league: 'Sarnia (OHL)', nationality: 'CAN' },
  { pick: 95, round: 3, team: 'Vegas Golden Knights', player: 'Sean Burick', position: 'D', league: 'Penticton (WHL)', nationality: 'USA' },
  { pick: 96, round: 3, team: 'Utah Mammoth', player: 'Adam Valentini', position: 'C', league: 'Michigan (NCAA)', nationality: 'CAN' },
  { pick: 97, round: 4, team: 'Vancouver Canucks', player: 'Yaroslav Bryzgalov', position: 'LW', league: 'Medicine Hat (WHL)', nationality: 'BLR' },
  { pick: 98, round: 4, team: 'Florida Panthers', player: 'Jonas Kemps', position: 'D', league: 'Chicago (USHL)', nationality: 'USA' },
  { pick: 99, round: 4, team: 'Seattle Kraken', player: 'Viktor Fedorov', position: 'C', league: 'Torpedo-Gorky (VHL)', nationality: 'RUS' },
  { pick: 100, round: 4, team: 'Calgary Flames', player: 'Egor Barabanov', position: 'C', league: 'Saginaw (OHL)', nationality: 'RUS' },
  { pick: 101, round: 4, team: 'Washington Capitals', player: 'Tyus Sparks', position: 'C', league: 'Spokane (WHL)', nationality: 'USA' },
  { pick: 102, round: 4, team: 'New York Rangers', player: 'Spencer Bowes', position: 'LW', league: 'Ottawa (OHL)', nationality: 'CAN' },
  { pick: 103, round: 4, team: 'Los Angeles Kings', player: 'Thomas Vandenberg', position: 'C', league: 'Ottawa (OHL)', nationality: 'CAN' },
  { pick: 104, round: 4, team: 'Boston Bruins', player: 'Matvei Kotkov', position: 'RW', league: 'Loko Yaroslavl (MHL)', nationality: 'RUS' },
  { pick: 105, round: 4, team: 'Carolina Hurricanes', player: 'Michael Berchild', position: 'LW', league: 'USA U-18 (NTDP-USHL)', nationality: 'USA' },
  { pick: 106, round: 4, team: 'Nashville Predators', player: 'Jakub Floris', position: 'D', league: 'Lukko (SM-sarja)', nationality: 'SVK' },
  { pick: 107, round: 4, team: 'St. Louis Blues', player: 'Landon Nycz', position: 'D', league: 'UMass-Lowell (Hockey East)', nationality: 'USA' },
  { pick: 108, round: 4, team: 'Detroit Red Wings', player: 'Adam Levac', position: 'C', league: 'Peterborough (OHL)', nationality: 'CAN' },
  { pick: 109, round: 4, team: 'New York Islanders', player: 'Lincoln Kuehne', position: 'D', league: 'Arizona State (NCAA)', nationality: 'USA' },
  { pick: 110, round: 4, team: 'Ottawa Senators', player: 'Elliot Lennon', position: 'G', league: 'Deerfield (US-HS)', nationality: 'CAN' },
  { pick: 111, round: 4, team: 'Pittsburgh Penguins', player: 'Parker Von Richter', position: 'D', league: 'Barrie (OHL)', nationality: 'CAN' },
  { pick: 112, round: 4, team: 'Minnesota Wild', player: 'Kayden Lemire', position: 'RW', league: 'Prince George (WHL)', nationality: 'CAN' },
  { pick: 113, round: 4, team: 'Vegas Golden Knights', player: 'Jonah Sivertson', position: 'RW', league: 'Prince Albert (WHL)', nationality: 'CAN' },
  { pick: 114, round: 4, team: 'Toronto Maple Leafs', player: 'Patriks Plumins', position: 'G', league: 'Zemgale (LHHL)', nationality: 'LAT' },
  { pick: 115, round: 4, team: 'Utah Mammoth', player: 'Carl Axelsson', position: 'G', league: 'Muskegon (USHL)', nationality: 'SWE' },
  { pick: 116, round: 4, team: 'Winnipeg Jets', player: 'Zach Wooten', position: 'LW', league: 'Green Bay (USHL)', nationality: 'USA' },
  { pick: 117, round: 4, team: 'Montreal Canadiens', player: 'Brayden Klimpke', position: 'D', league: 'Saskatoon (WHL)', nationality: 'CAN' },
  { pick: 118, round: 4, team: 'Nashville Predators', player: 'Justin Graf', position: 'LW', league: 'Cedar Rapids (USHL)', nationality: 'USA' },
  { pick: 119, round: 4, team: 'New Jersey Devils', player: 'Lavr Gashilov', position: 'C', league: 'Yekaterinburg (MHL)', nationality: 'RUS' },
  { pick: 120, round: 4, team: 'Philadelphia Flyers', player: 'Marek Sklenicka', position: 'G', league: 'Seattle (WHL)', nationality: 'CZE' },
  { pick: 121, round: 4, team: 'Columbus Blue Jackets', player: 'Evan Jardine', position: 'LW', league: 'Youngstown (USHL)', nationality: 'USA' },
  { pick: 122, round: 4, team: 'Boston Bruins', player: 'Oscar Olsson', position: 'LW', league: 'Orebro (SHL)', nationality: 'SWE' },
  { pick: 123, round: 4, team: 'St. Louis Blues', player: 'Vladimir Proskurin', position: 'G', league: 'Mytischi (MHL)', nationality: 'RUS' },
  { pick: 124, round: 4, team: 'Buffalo Sabres', player: 'Olivers Murnieks', position: 'C', league: 'Saint John (QMJHL)', nationality: 'LAT' },
  { pick: 125, round: 4, team: 'Carolina Hurricanes', player: 'Ryder Fetterolf', position: 'G', league: 'Ottawa (OHL)', nationality: 'USA' },
  { pick: 126, round: 4, team: 'Colorado Avalanche', player: 'Tobias Tvrznik', position: 'G', league: 'Wenatchee (WHL)', nationality: 'CZE' },
  { pick: 127, round: 4, team: 'San Jose Sharks', player: 'Brady Knowling', position: 'G', league: 'USA U-18 (NTDP-USHL)', nationality: 'USA' },
  { pick: 128, round: 4, team: 'Colorado Avalanche', player: 'Axel Elofsson', position: 'D', league: 'Orebro (SHL)', nationality: 'SWE' },
  { pick: 129, round: 5, team: 'Vancouver Canucks', player: 'Connor Davis', position: 'RW', league: 'Cedar Rapids (USHL)', nationality: 'CAN' },
  { pick: 130, round: 5, team: 'Utah Mammoth', player: 'Theodor Knights', position: 'D', league: 'MoDo (HockeyAllsvenskan)', nationality: 'SWE' },
  { pick: 131, round: 5, team: 'Seattle Kraken', player: 'Finn Kearns', position: 'D', league: 'St. Andrews College (CA-HS)', nationality: 'CAN' },
  { pick: 132, round: 5, team: 'Calgary Flames', player: 'Simon Katolicky', position: 'LW', league: 'Tappara (SM-sarja)', nationality: 'CZE' },
  { pick: 133, round: 5, team: 'Edmonton Oilers', player: 'Andrew Robinson', position: 'D', league: 'Windsor (OHL)', nationality: 'CAN' },
  { pick: 134, round: 5, team: 'Tampa Bay Lightning', player: 'Morgan Anderberg', position: 'C', league: 'Vaxjo (SHL)', nationality: 'SWE' },
  { pick: 135, round: 5, team: 'Winnipeg Jets', player: 'Alexandre Taillefer', position: 'D', league: 'Quebec (QMJHL)', nationality: 'CAN' },
  { pick: 136, round: 5, team: 'Philadelphia Flyers', player: 'Kent Sauer', position: 'C', league: 'Andover (US-HS)', nationality: 'USA' },
  { pick: 137, round: 5, team: 'Minnesota Wild', player: 'Filip Ruzicka', position: 'G', league: 'Brandon (WHL)', nationality: 'CZE' },
  { pick: 138, round: 5, team: 'Nashville Predators', player: 'Philip Hemmyr', position: 'LW', league: 'Bjorkloven (HockeyAllsvenskan)', nationality: 'SWE' },
  { pick: 139, round: 5, team: 'St. Louis Blues', player: 'Nicholas Bogas', position: 'D', league: 'USA U-18 (NTDP-USHL)', nationality: 'USA' },
  { pick: 140, round: 5, team: 'Colorado Avalanche', player: 'Cole Tuminaro', position: 'D', league: 'Chicago (USHL)', nationality: 'USA' },
  { pick: 141, round: 5, team: 'New York Islanders', player: 'Vladimir Dravecky', position: 'D', league: 'Brantford (OHL)', nationality: 'CZE' },
  { pick: 142, round: 5, team: 'Columbus Blue Jackets', player: 'Parker Snell', position: 'G', league: 'Edmonton (WHL)', nationality: 'CAN' },
  { pick: 143, round: 5, team: 'Detroit Red Wings', player: 'Beckham Edwards', position: 'C', league: 'Sarnia (OHL)', nationality: 'CAN' },
  { pick: 144, round: 5, team: 'Washington Capitals', player: 'Brian McFadden', position: 'D', league: 'Thayer Academy (US-HS)', nationality: 'USA' },
  { pick: 145, round: 5, team: 'Los Angeles Kings', player: 'Vertti Svensk', position: 'D', league: 'Saipa (SM-sarja)', nationality: 'FIN' },
  { pick: 146, round: 5, team: 'Anaheim Ducks', player: 'Eric Frossard', position: 'D', league: 'Guelph (OHL)', nationality: 'CAN' },
  { pick: 147, round: 5, team: 'Utah Mammoth', player: 'Florent Houle', position: 'RW', league: 'Sherbrooke (QMJHL)', nationality: 'CAN' },
  { pick: 148, round: 5, team: 'Seattle Kraken', player: 'Luken Huff', position: 'D', league: 'Cedar Rapids (USHL)', nationality: 'USA' },
  { pick: 149, round: 5, team: 'New Jersey Devils', player: 'Daniil Rusakovich', position: 'G', league: 'Dinamo-Shinnik (MHL)', nationality: 'BLR' },
  { pick: 150, round: 5, team: 'St. Louis Blues', player: 'Carter Stevens', position: 'RW', league: 'Guelph (OHL)', nationality: 'CAN' },
  { pick: 151, round: 5, team: 'Ottawa Senators', player: 'Harris Pangretitsch', position: 'D', league: 'Sault Ste. Marie (OHL)', nationality: 'CAN' },
  { pick: 152, round: 5, team: 'Colorado Avalanche', player: 'Theodore Lechner', position: 'D', league: 'Holy Angels (US-HS)', nationality: 'USA' },
  { pick: 153, round: 5, team: 'Los Angeles Kings', player: 'Giorgos Pantelas', position: 'D', league: 'Brandon (WHL)', nationality: 'CAN' },
  { pick: 154, round: 5, team: 'Tampa Bay Lightning', player: 'Cooper Soller', position: 'C', league: 'Sioux Falls (USHL)', nationality: 'USA' },
  { pick: 155, round: 5, team: 'Dallas Stars', player: 'Ryan Brown', position: 'LW', league: 'London (OHL)', nationality: 'CAN' },
  { pick: 156, round: 5, team: 'Buffalo Sabres', player: 'Doman Szongoth', position: 'C', league: 'Kookoo (SM-sarja)', nationality: 'HU' },
  { pick: 157, round: 5, team: 'Boston Bruins', player: 'Jacob Vandeven', position: 'D', league: 'Komoka (GOHL)', nationality: 'CAN' },
  { pick: 158, round: 5, team: 'Toronto Maple Leafs', player: 'Cooper Williams', position: 'C', league: 'Saskatoon (WHL)', nationality: 'CAN' },
  { pick: 159, round: 5, team: 'Vegas Golden Knights', player: 'Will McLaughlin', position: 'D', league: 'Portland (WHL)', nationality: 'CAN' },
  { pick: 160, round: 5, team: 'Pittsburgh Penguins', player: 'Matvei Nikonovich', position: 'G', league: 'Togliatti (MHL)', nationality: 'BLR' },
  { pick: 161, round: 6, team: 'Toronto Maple Leafs', player: 'Yaroslav Fedoseyev', position: 'D', league: 'Chelyabinsk (MHL)', nationality: 'RUS' },
  { pick: 162, round: 6, team: 'New York Rangers', player: 'Andre Mondoux', position: 'D', league: 'Kingston (OHL)', nationality: 'CAN' },
  { pick: 163, round: 6, team: 'New York Rangers', player: 'Darian Anderson', position: 'RW', league: 'Flint (OHL)', nationality: 'USA' },
  { pick: 164, round: 6, team: 'Calgary Flames', player: 'Bode Laylin', position: 'D', league: 'Tri-City (USHL)', nationality: 'USA' },
  { pick: 165, round: 6, team: 'Carolina Hurricanes', player: 'Zachary Jovanovski', position: 'G', league: 'Guelph (OHL)', nationality: 'CAN' },
  { pick: 166, round: 6, team: 'Seattle Kraken', player: 'Ola Palme', position: 'D', league: 'Vaxjo (SHL)', nationality: 'SWE' },
  { pick: 167, round: 6, team: 'Winnipeg Jets', player: 'Landon Hafele', position: 'C', league: 'Green Bay (USHL)', nationality: 'USA' },
  { pick: 168, round: 6, team: 'Florida Panthers', player: 'Vilho Vanhatalo', position: 'RW', league: 'Tappara (SM-sarja)', nationality: 'FIN' },
  { pick: 169, round: 6, team: 'Toronto Maple Leafs', player: 'Brody Pepoy', position: 'RW', league: 'Saginaw (OHL)', nationality: 'USA' },
  { pick: 170, round: 6, team: 'Boston Bruins', player: 'Roberto Henriquez', position: 'G', league: 'Green Bay (USHL)', nationality: 'SVK' },
  { pick: 171, round: 6, team: 'St. Louis Blues', player: 'Lars Steiner', position: 'RW', league: 'Rouyn-Noranda (QMJHL)', nationality: 'SUI' },
  { pick: 172, round: 6, team: 'New Jersey Devils', player: 'Luke Wilfley', position: 'C', league: 'Portland (WHL)', nationality: 'USA' },
  { pick: 173, round: 6, team: 'New York Islanders', player: 'Artyom Matyuk', position: 'C', league: 'Nizhny Novgorod (MHL)', nationality: 'RUS' },
  { pick: 174, round: 6, team: 'San Jose Sharks', player: 'Jake Gustafson', position: 'C', league: 'Portland (WHL)', nationality: 'USA' },
  { pick: 175, round: 6, team: 'Detroit Red Wings', player: 'Luka Arkko', position: 'LW', league: 'Pelicans (SM-sarja)', nationality: 'FIN' },
  { pick: 176, round: 6, team: 'Vancouver Canucks', player: 'Lucian Bernat', position: 'RW', league: 'Tappara (SM-sarja)', nationality: 'SVK' },
  { pick: 177, round: 6, team: 'Los Angeles Kings', player: 'Alex Kostov', position: 'RW', league: 'Flint (OHL)', nationality: 'CAN' },
  { pick: 178, round: 6, team: 'Anaheim Ducks', player: 'Gleb Peshkov', position: 'G', league: 'Vladivostok (MHL)', nationality: 'RUS' },
  { pick: 179, round: 6, team: 'Nashville Predators', player: 'Benjamin Cossette-Ayotte', position: 'D', league: 'Val-d\'Or (QMJHL)', nationality: 'CAN' },
  { pick: 180, round: 6, team: 'Edmonton Oilers', player: 'Caden Harvey', position: 'C', league: 'Windsor (OHL)', nationality: 'USA' },
  { pick: 181, round: 6, team: 'Florida Panthers', player: 'Cole Zurawski', position: 'RW', league: 'Owen Sound (OHL)', nationality: 'CAN' },
  { pick: 182, round: 6, team: 'Columbus Blue Jackets', player: 'Anttoni Uronen', position: 'C', league: 'HIFK (Liiga)', nationality: 'FIN' },
  { pick: 183, round: 6, team: 'Ottawa Senators', player: 'Alexander Grunin', position: 'D', league: 'Novosibirsk (MHL)', nationality: 'RUS' },
  { pick: 184, round: 6, team: 'Vancouver Canucks', player: 'Samuel Eriksson', position: 'D', league: 'Farjestad (SHL)', nationality: 'SWE' },
  { pick: 185, round: 6, team: 'Columbus Blue Jackets', player: 'Jonas Woo', position: 'D', league: 'Medicine Hat (WHL)', nationality: 'CAN' },
  { pick: 186, round: 6, team: 'Tampa Bay Lightning', player: 'Stepan Shurygin', position: 'G', league: 'Saginaw (OHL)', nationality: 'RUS' },
  { pick: 187, round: 6, team: 'Dallas Stars', player: 'Anton Emil Wilde Larsen', position: 'G', league: 'Frederikshavn (Superisligaen)', nationality: 'DEN' },
  { pick: 188, round: 6, team: 'Buffalo Sabres', player: 'Dylan Dumont', position: 'RW', league: 'Drummondville (QMJHL)', nationality: 'CAN' },
  { pick: 189, round: 6, team: 'Montreal Canadiens', player: 'Parker Trottier', position: 'LW', league: 'USA U-18 (NTDP-USHL)', nationality: 'USA' },
  { pick: 190, round: 6, team: 'Montreal Canadiens', player: 'Wesley Royston', position: 'RW', league: 'Owen Sound (OHL)', nationality: 'CAN' },
  { pick: 191, round: 6, team: 'Vegas Golden Knights', player: 'Matthew Minchak', position: 'G', league: 'Kingston (OHL)', nationality: 'USA' },
  { pick: 192, round: 6, team: 'Anaheim Ducks', player: 'Noah Kosick', position: 'C', league: 'Seattle (WHL)', nationality: 'GER' },
  { pick: 193, round: 7, team: 'New York Rangers', player: 'Ivan Patrikhayev', position: 'D', league: 'CSKA (KHL)', nationality: 'RUS' },
  { pick: 194, round: 7, team: 'Chicago Blackhawks', player: 'Alexander Ivanov', position: 'D', league: 'Bars Kazan (VHL)', nationality: 'RUS' },
  { pick: 195, round: 7, team: 'Colorado Avalanche', player: 'Shawn Carrier', position: 'LW', league: 'Halifax (QMJHL)', nationality: 'CAN' },
  { pick: 196, round: 7, team: 'Detroit Red Wings', player: 'Myles Brosnan', position: 'D', league: 'Dexter School (US-HS)', nationality: 'USA' },
  { pick: 197, round: 7, team: 'Dallas Stars', player: 'Jasper Kuhta', position: 'C', league: 'Ottawa (OHL)', nationality: 'FIN' },
  { pick: 198, round: 7, team: 'Seattle Kraken', player: 'Rylan Singh', position: 'D', league: 'Guelph (OHL)', nationality: 'CAN' },
  { pick: 199, round: 7, team: 'Winnipeg Jets', player: 'Alofa Tunoa Ta\'amu', position: 'D', league: 'Edmonton (WHL)', nationality: 'USA' },
  { pick: 200, round: 7, team: 'Chicago Blackhawks', player: 'William Sorbrand', position: 'C', league: 'Timra (SHL)', nationality: 'SWE' },
  { pick: 201, round: 7, team: 'San Jose Sharks', player: 'Alexander Karmanov', position: 'D', league: 'North Bay (OHL)', nationality: 'MDA' },
  { pick: 202, round: 7, team: 'Nashville Predators', player: 'Charlie Puglisi', position: 'C', league: 'Winchendon (US-HS)', nationality: 'USA' },
  { pick: 203, round: 7, team: 'St. Louis Blues', player: 'Colin Fitzgerald', position: 'C', league: 'Sault Ste. Marie (OHL)', nationality: 'CAN' },
  { pick: 204, round: 7, team: 'Seattle Kraken', player: 'William Tomko', position: 'C', league: 'Sioux City (USHL)', nationality: 'USA' },
  { pick: 205, round: 7, team: 'New York Islanders', player: 'Robert Cowan', position: 'RW', league: 'Western Michigan (NCAA)', nationality: 'USA' },
  { pick: 206, round: 7, team: 'Columbus Blue Jackets', player: 'Filip Novak', position: 'LW', league: 'Sparta (Extraliga)', nationality: 'CZE' },
  { pick: 207, round: 7, team: 'Vegas Golden Knights', player: 'Noel Pakarinen', position: 'LW', league: 'K-Espoo (SM-sarja)', nationality: 'FIN' },
  { pick: 208, round: 7, team: 'Washington Capitals', player: 'Logan Stuart', position: 'C', league: 'USA U-18 (NTDP-USHL)', nationality: 'USA' },
  { pick: 209, round: 7, team: 'Los Angeles Kings', player: 'Tobias Krestan', position: 'RW', league: 'HV71 (SWE)', nationality: 'GER' },
  { pick: 210, round: 7, team: 'Anaheim Ducks', player: 'James Rieber', position: 'D', league: 'Waterloo (USHL)', nationality: 'USA' },
  { pick: 211, round: 7, team: 'Utah Mammoth', player: 'Artem Prima', position: 'LW', league: 'Minot (NAHL)', nationality: 'RUS' },
  { pick: 212, round: 7, team: 'Edmonton Oilers', player: 'Ryan Cameron', position: 'G', league: 'Cedar Rapids (USHL)', nationality: 'USA' },
  { pick: 213, round: 7, team: 'Philadelphia Flyers', player: 'Max Laatikainen', position: 'D', league: 'K-Espoo (SM-sarja)', nationality: 'SWE' },
  { pick: 214, round: 7, team: 'Colorado Avalanche', player: 'Ondrej Ruml', position: 'D', league: 'Ottawa (OHL)', nationality: 'CZE' },
  { pick: 215, round: 7, team: 'Colorado Avalanche', player: 'Alexandre Raymond', position: 'G', league: 'Rouyn-Noranda (QMJHL)', nationality: 'CAN' },
  { pick: 216, round: 7, team: 'Boston Bruins', player: 'Cullen McCrate', position: 'D', league: 'Fargo (USHL)', nationality: 'USA' },
  { pick: 217, round: 7, team: 'Florida Panthers', player: 'Louis-Antoine Denault', position: 'G', league: 'Newfoundland (QMJHL)', nationality: 'CAN' },
  { pick: 218, round: 7, team: 'Tampa Bay Lightning', player: 'Max Vilen', position: 'D', league: 'Moncton (QMJHL)', nationality: 'SWE' },
  { pick: 219, round: 7, team: 'Dallas Stars', player: 'Mikhail Cherepanov', position: 'D', league: 'New Hampshire (NAHL)', nationality: 'RUS' },
  { pick: 220, round: 7, team: 'Winnipeg Jets', player: 'John Parsons', position: 'G', league: 'Providence (NCAA)', nationality: 'USA' },
  { pick: 221, round: 7, team: 'Montreal Canadiens', player: 'Jean-Samuel Daigneault', position: 'D', league: 'Muskegon (USHL)', nationality: 'CAN' },
  { pick: 222, round: 7, team: 'New Jersey Devils', player: 'Quinn McKenzie', position: 'C', league: 'Sault Ste. Marie (OHL)', nationality: 'USA' },
  { pick: 223, round: 7, team: 'Los Angeles Kings', player: 'Lucas Ambrosio', position: 'D', league: 'Erie (OHL)', nationality: 'CAN' },
  { pick: 224, round: 7, team: 'Montreal Canadiens', player: 'Tyler Deakos', position: 'RW', league: 'Waterloo (USHL)', nationality: 'CAN' },
];

export const DRAFT_2026_STATS: PickStats = {
  totalPicks: 224,
  realPicks: 223,
  forfeits: 1,
  uniqueTeams: 49,
  rounds: 7,
  nationalities: 17,
  leagues: 138,
};
