// Auto-generated from /root/.openclaw/media/inbound/2025_NHL_Draft_Full_Results---3eb29370-bc43-41f7-ace5-4525699e5a0c.xlsx
// Cross-verified against Hockey-Reference.com (saved 2026-07-03 02:48 CDT)
// 224 picks total across 7 rounds, all picks loaded.
import type { PickStats } from './types';
export interface Pick {
  pick: number;
  round: number;
  team: string;
  player: string;
  position: string;
  league: string;
  nationality: string;
}

export const PICKS_2025: Pick[] = [
  { pick: 1, round: 1, team: 'New York Islanders', player: 'Matthew Schaefer', position: 'D', league: 'Erie Otters (OHL)', nationality: 'CAN' },
  { pick: 2, round: 1, team: 'San Jose Sharks', player: 'Michael Misa', position: 'C', league: 'Saginaw Spirit (OHL)', nationality: 'CAN' },
  { pick: 3, round: 1, team: 'Chicago Blackhawks', player: 'Anton Frondell', position: 'C', league: 'Djurgardens IF (HockeyAllsvenskan)', nationality: 'SWE' },
  { pick: 4, round: 1, team: 'Utah Hockey Club', player: 'Caleb Desnoyers', position: 'C', league: 'Moncton Wildcats (QMJHL)', nationality: 'CAN' },
  { pick: 5, round: 1, team: 'Nashville Predators', player: 'Brady Martin', position: 'C', league: 'Sault Ste. Marie Greyhounds (OHL)', nationality: 'CAN' },
  { pick: 6, round: 1, team: 'Philadelphia Flyers', player: 'Porter Martone', position: 'RW', league: 'Brampton Steelheads (OHL)', nationality: 'CAN' },
  { pick: 7, round: 1, team: 'Boston Bruins', player: 'James Hagens', position: 'C', league: 'Boston College Eagles (Hockey East)', nationality: 'USA' },
  { pick: 8, round: 1, team: 'Seattle Kraken', player: 'Jake O\'Brien', position: 'C', league: 'Brantford Bulldogs (OHL)', nationality: 'CAN' },
  { pick: 9, round: 1, team: 'Buffalo Sabres', player: 'Radim Mrtka', position: 'D', league: 'Seattle Thunderbirds (WHL)', nationality: 'CZE' },
  { pick: 10, round: 1, team: 'Anaheim Ducks', player: 'Roger McQueen', position: 'C', league: 'Brandon Wheat Kings (WHL)', nationality: 'CAN' },
  { pick: 11, round: 1, team: 'Pittsburgh Penguins', player: 'Ben Kindel', position: 'C', league: 'Calgary Hitmen (WHL)', nationality: 'CAN' },
  { pick: 12, round: 1, team: 'Philadelphia Flyers (from NYR)', player: 'Jack Nesbitt', position: 'C', league: 'Windsor Spitfires (OHL)', nationality: 'CAN' },
  { pick: 13, round: 1, team: 'Detroit Red Wings', player: 'Carter Bear', position: 'LW', league: 'Everett Silvertips (WHL)', nationality: 'CAN' },
  { pick: 14, round: 1, team: 'Columbus Blue Jackets', player: 'Jackson Smith', position: 'D', league: 'Tri-City Americans (WHL)', nationality: 'CAN' },
  { pick: 15, round: 1, team: 'Vancouver Canucks', player: 'Braeden Cootes', position: 'C', league: 'Seattle Thunderbirds (WHL)', nationality: 'CAN' },
  { pick: 16, round: 1, team: 'NY Islanders (from CGY)', player: 'Victor Eklund', position: 'RW', league: 'Djurgardens IF (HockeyAllsvenskan)', nationality: 'SWE' },
  { pick: 17, round: 1, team: 'NY Islanders (from MTL)', player: 'Kashawn Aitcheson', position: 'D', league: 'Barrie Colts (OHL)', nationality: 'CAN' },
  { pick: 18, round: 1, team: 'Calgary Flames (from NJD)', player: 'Cole Reschny', position: 'C', league: 'Victoria Royals (WHL)', nationality: 'CAN' },
  { pick: 19, round: 1, team: 'St. Louis Blues', player: 'Justin Carbonneau', position: 'RW', league: 'Blainville-Boisbriand Armada (QMJHL)', nationality: 'CAN' },
  { pick: 20, round: 1, team: 'Columbus Blue Jackets (from MIN)', player: 'Pyotr Andreyanov', position: 'G', league: 'Krasnaya Armiya (MHL)', nationality: 'RUS' },
  { pick: 21, round: 1, team: 'Nashville Predators (from OTT)', player: 'Cameron Reid', position: 'D', league: 'Kitchener Rangers (OHL)', nationality: 'CAN' },
  { pick: 22, round: 1, team: 'Pittsburgh Penguins (from COL)', player: 'Bill Zonnon', position: 'RW', league: 'Rouyn-Noranda Huskies (QMJHL)', nationality: 'CAN' },
  { pick: 23, round: 1, team: 'Ottawa Senators (from TB)', player: 'Logan Hensler', position: 'D', league: 'Wisconsin Badgers (Big Ten)', nationality: 'USA' },
  { pick: 24, round: 1, team: 'Pittsburgh Penguins (from LAK)', player: 'Will Horcoff', position: 'C', league: 'Michigan Wolverines (Big Ten)', nationality: 'CAN' },
  { pick: 25, round: 1, team: 'Chicago Blackhawks (from TOR)', player: 'Vaclav Nestrasil', position: 'RW', league: 'Muskegon Lumberjacks (USHL)', nationality: 'CZE' },
  { pick: 26, round: 1, team: 'Nashville Predators (from VGK)', player: 'Ryker Lee', position: 'RW', league: 'Madison Capitols (USHL)', nationality: 'USA' },
  { pick: 27, round: 1, team: 'Washington Capitals', player: 'Lynden Lakovic', position: 'LW', league: 'Moose Jaw Warriors (WHL)', nationality: 'CAN' },
  { pick: 28, round: 1, team: 'Winnipeg Jets', player: 'Sascha Boumedienne', position: 'D', league: 'Boston University (Hockey East)', nationality: 'FIN' },
  { pick: 29, round: 1, team: 'Chicago Blackhawks (from CAR)', player: 'Mason West', position: 'C', league: 'Edina Hornets (USHS-MN)', nationality: 'USA' },
  { pick: 30, round: 1, team: 'San Jose Sharks (from DAL)', player: 'Joshua Ravensbergen', position: 'G', league: 'Prince George Cougars (WHL)', nationality: 'CAN' },
  { pick: 31, round: 1, team: 'Los Angeles Kings (from EDM)', player: 'Henry Brzustewicz', position: 'D', league: 'London Knights (OHL)', nationality: 'USA' },
  { pick: 32, round: 1, team: 'Calgary Flames (from FLA)', player: 'Cullen Potter', position: 'C', league: 'Arizona State Sun Devils (NCHC)', nationality: 'USA' },
  { pick: 33, round: 2, team: 'San Jose Sharks', player: 'Simon (Haoxi) Wang', position: 'D', league: 'Oshawa Generals (OHL)', nationality: 'CHN' },
  { pick: 34, round: 2, team: 'Montreal Canadiens (from CHI via CAR)', player: 'Alexander Zharovsky', position: 'RW', league: 'Tolpar Ufa (MHL)', nationality: 'RUS' },
  { pick: 35, round: 2, team: 'Nashville Predators', player: 'Jacob Rombach', position: 'D', league: 'Lincoln Stars (USHL)', nationality: 'USA' },
  { pick: 36, round: 2, team: 'Seattle Kraken (from PHI)', player: 'Blake Fiddler', position: 'D', league: 'Edmonton Oil Kings (WHL)', nationality: 'USA' },
  { pick: 37, round: 2, team: 'Washington Capitals (from BOS)', player: 'Milton Gastrin', position: 'C', league: 'Modo Hockey (SHL)', nationality: 'SWE' },
  { pick: 38, round: 2, team: 'Philadelphia Flyers (from SEA)', player: 'Carter Amico', position: 'D', league: 'U.S. NTDP (USHL)', nationality: 'USA' },
  { pick: 39, round: 2, team: 'Pittsburgh Penguins (from BUF)', player: 'Peyton Kettles', position: 'D', league: 'Swift Current Broncos (WHL)', nationality: 'CAN' },
  { pick: 40, round: 2, team: 'Philadelphia Flyers (from ANA)', player: 'Jack Murtagh', position: 'LW', league: 'U.S. NTDP (USHL)', nationality: 'USA' },
  { pick: 41, round: 2, team: 'Carolina Hurricanes (from PIT via MTL)', player: 'Semyon Frolov', position: 'G', league: 'JHC Spartak (MHL)', nationality: 'RUS' },
  { pick: 42, round: 2, team: 'New York Islanders', player: 'Daniil Prokhorov', position: 'RW', league: 'HC Dinamo St. Petersburg (MHL)', nationality: 'RUS' },
  { pick: 43, round: 2, team: 'New York Rangers', player: 'Malcolm Spence', position: 'LW', league: 'Erie Otters (OHL)', nationality: 'CAN' },
  { pick: 44, round: 2, team: 'Detroit Red Wings', player: 'Eddie Genborg', position: 'RW', league: 'Linkoping HC (SHL)', nationality: 'SWE' },
  { pick: 45, round: 2, team: 'Anaheim Ducks (from CBJ via PHI)', player: 'Eric Nilson', position: 'C', league: 'Djurgardens IF J20 (J20 Nationell)', nationality: 'CAN' },
  { pick: 46, round: 2, team: 'Utah Hockey Club', player: 'Max Psenicka', position: 'D', league: 'Portland Winterhawks (WHL)', nationality: 'CZE' },
  { pick: 47, round: 2, team: 'Vancouver Canucks', player: 'Alexei Medvedev', position: 'G', league: 'London Knights (OHL)', nationality: 'RUS' },
  { pick: 48, round: 2, team: 'Philadelphia Flyers (from CGY)', player: 'Shane Vansaghi', position: 'RW', league: 'Michigan State Spartans (Big Ten)', nationality: 'USA' },
  { pick: 49, round: 2, team: 'Carolina Hurricanes (from MTL)', player: 'Charlie Cerrato', position: 'C', league: 'Penn State Nittany Lions (Big Ten)', nationality: 'USA' },
  { pick: 50, round: 2, team: 'New Jersey Devils', player: 'Conrad Fondrk', position: 'C', league: 'U.S. NTDP (USHL)', nationality: 'USA' },
  { pick: 51, round: 2, team: 'Boston Bruins (from STL)', player: 'William Moore', position: 'C', league: 'U.S. NTDP (USHL)', nationality: 'CAN' },
  { pick: 52, round: 2, team: 'Minnesota Wild', player: 'Theodor Hallquisth', position: 'D', league: 'Orebro HK J20 (J20 Nationell)', nationality: 'SWE' },
  { pick: 53, round: 2, team: 'San Jose Sharks (from OTT)', player: 'Cole McKinney', position: 'C', league: 'U.S. NTDP (USHL)', nationality: 'USA' },
  { pick: 54, round: 2, team: 'Calgary Flames (from COL via WSH)', player: 'Theo Stockselius', position: 'C', league: 'Djurgardens IF J20 (J20 Nationell)', nationality: 'SWE' },
  { pick: 55, round: 2, team: 'Vegas Golden Knights (from TB/NSH)', player: 'Jakob Ihs-Wozniak', position: 'RW', league: 'Lulea HF J20 (J20 Nationell)', nationality: 'AUT' },
  { pick: 56, round: 2, team: 'Tampa Bay Lightning (from LAK)', player: 'Ethan Czata', position: 'C', league: 'Niagara IceDogs (OHL)', nationality: 'CAN' },
  { pick: 57, round: 2, team: 'Philadelphia Flyers (from TOR)', player: 'Matthew Gard', position: 'C', league: 'Red Deer Rebels (WHL)', nationality: 'CAN' },
  { pick: 58, round: 2, team: 'Nashville Predators (from VGK)', player: 'Jack Ivankovic', position: 'G', league: 'Brampton Steelheads (OHL)', nationality: 'CAN' },
  { pick: 59, round: 2, team: 'Los Angeles Kings (from WSH via PIT)', player: 'Vojtech Cihar', position: 'LW', league: 'HC Energie Karlovy Vary (Czech Extraliga)', nationality: 'CZE' },
  { pick: 60, round: 2, team: 'Anaheim Ducks (from WPG via NJD)', player: 'Lasse Boelius', position: 'D', league: 'HC Assat Pori (Liiga)', nationality: 'FIN' },
  { pick: 61, round: 2, team: 'Boston Bruins (from CAR via COL)', player: 'Liam Pettersson', position: 'D', league: 'Vaxjo Lakers HC J20 (J20 Nationell)', nationality: 'SWE' },
  { pick: 62, round: 2, team: 'Carolina Hurricanes (from DAL via CHI)', player: 'Ivan Ryabkin', position: 'C', league: 'Muskegon Lumberjacks (USHL)', nationality: 'RUS' },
  { pick: 63, round: 2, team: 'New Jersey Devils (from EDM via UTA)', player: 'Ben Kevan', position: 'RW', league: 'Des Moines Buccaneers (USHL)', nationality: 'USA' },
  { pick: 64, round: 2, team: 'Toronto Maple Leafs (from FLA)', player: 'Tinus Luc Koblar', position: 'C', league: 'Leksands IF J20 (J20 Nationell)', nationality: 'SLO' },
  { pick: 65, round: 3, team: 'Vancouver Canucks (from SJ)', player: 'Kieren Dervin', position: 'C', league: 'St. Andrew\'s Saints (CISAA)', nationality: 'CAN' },
  { pick: 66, round: 3, team: 'Chicago Blackhawks', player: 'Nathan Behm', position: 'RW', league: 'Kamloops Blazers (WHL)', nationality: 'CAN' },
  { pick: 67, round: 3, team: 'Carolina Hurricanes (from NSH)', player: 'Kurban Limatov', position: 'D', league: 'MHC Dynamo Moscow (MHL)', nationality: 'RUS' },
  { pick: 68, round: 3, team: 'Seattle Kraken (from PHI)', player: 'Will Reynolds', position: 'D', league: 'Acadie-Bathurst Titan (QMJHL)', nationality: 'CAN' },
  { pick: 69, round: 3, team: 'Montreal Canadiens (from BOS)', player: 'Hayden Paupanekis', position: 'C', league: 'Kelowna Rockets (WHL)', nationality: 'CAN' },
  { pick: 70, round: 3, team: 'New York Rangers (from SEA)', player: 'Sean Barnhill', position: 'D', league: 'Dubuque Fighting Saints (USHL)', nationality: 'USA' },
  { pick: 71, round: 3, team: 'Buffalo Sabres', player: 'David Bedkowski', position: 'D', league: 'Owen Sound Attack (OHL)', nationality: 'CAN' },
  { pick: 72, round: 3, team: 'Anaheim Ducks', player: 'Noah Read', position: 'C', league: 'London Knights (OHL)', nationality: 'CAN' },
  { pick: 73, round: 3, team: 'Pittsburgh Penguins', player: 'Charlie Trethewey', position: 'D', league: 'U.S. NTDP (USHL)', nationality: 'USA' },
  { pick: 74, round: 3, team: 'New York Islanders', player: 'Luca Romano', position: 'C', league: 'Kitchener Rangers (OHL)', nationality: 'CAN' },
  { pick: 75, round: 3, team: 'Detroit Red Wings (from NYR via UTA)', player: 'Michal Pradel', position: 'G', league: 'Tri-City Storm (USHL)', nationality: 'SVK' },
  { pick: 76, round: 3, team: 'Columbus Blue Jackets (from DET)', player: 'Malte Vass', position: 'D', league: 'Farjestad BK J20 (J20 Nationell)', nationality: 'SWE' },
  { pick: 77, round: 3, team: 'Colorado Avalanche (from CBJ)', player: 'Francesco Dell\'Elce', position: 'D', league: 'UMass-Lowell (Hockey East)', nationality: 'CAN' },
  { pick: 78, round: 3, team: 'Utah Hockey Club', player: 'Stepan Hoch', position: 'LW', league: 'Motor Ceske Budejovice (Czech Extraliga)', nationality: 'CZE' },
  { pick: 79, round: 3, team: 'Boston Bruins (from VAN via MTL)', player: 'Cooper Simpson', position: 'LW', league: 'Shakopee (USHS-MN)', nationality: 'USA' },
  { pick: 80, round: 3, team: 'Calgary Flames', player: 'Mace\'o Phillips', position: 'D', league: 'U.S. NTDP (USHL)', nationality: 'USA' },
  { pick: 81, round: 3, team: 'Montreal Canadiens', player: 'Bryce Pickford', position: 'D', league: 'Medicine Hat Tigers (WHL)', nationality: 'CAN' },
  { pick: 82, round: 3, team: 'Montreal Canadiens (from NJD)', player: 'Arseni Radkov', position: 'G', league: 'Tyumensky Legion (MHL)', nationality: 'BLR' },
  { pick: 83, round: 3, team: 'Edmonton Oilers (from STL)', player: 'Tommy Lafreniere', position: 'RW', league: 'Kamloops Blazers (WHL)', nationality: 'CAN' },
  { pick: 84, round: 3, team: 'Pittsburgh Penguins (from MIN)', player: 'Gabriel D\'Aigle', position: 'G', league: 'Victoriaville Tigres (QMJHL)', nationality: 'CAN' },
  { pick: 85, round: 3, team: 'Vegas Golden Knights (from OTT)', player: 'Mateo Nobert', position: 'C', league: 'Blainville-Boisbriand Armada (QMJHL)', nationality: 'CAN' },
  { pick: 86, round: 3, team: 'Toronto Maple Leafs (from COL)', player: 'Tyler Hopkins', position: 'C', league: 'Kingston Frontenacs (OHL)', nationality: 'CAN' },
  { pick: 87, round: 3, team: 'Carolina Hurricanes (from TB)', player: 'Roman Bausov', position: 'D', league: 'HC Dinamo St. Petersburg U20 (MHL)', nationality: 'RUS' },
  { pick: 88, round: 3, team: 'Los Angeles Kings', player: 'Kristian Epperson', position: 'LW', league: 'Saginaw Spirit (OHL)', nationality: 'USA' },
  { pick: 89, round: 3, team: 'New York Rangers (from TOR via ANA)', player: 'Artyom Gonchar', position: 'D', league: 'Magnitogorsk Stalnye Lisy (MHL)', nationality: 'RUS' },
  { pick: 90, round: 3, team: 'New Jersey Devils (from VGK)', player: 'Mason Moe', position: 'C', league: 'Madison Capitols (USHL)', nationality: 'USA' },
  { pick: 91, round: 3, team: 'Pittsburgh Penguins (from WSH via VGK)', player: 'Brady Peddle', position: 'D', league: 'Waterloo Black Hawks (USHL)', nationality: 'CAN' },
  { pick: 92, round: 3, team: 'Winnipeg Jets', player: 'Owen Martin', position: 'C', league: 'Spokane Chiefs (WHL)', nationality: 'CAN' },
  { pick: 93, round: 3, team: 'Ottawa Senators (from CAR via WSH)', player: 'Blake Vanek', position: 'RW', league: 'Stillwater Ponies (USHS-MN)', nationality: 'USA' },
  { pick: 94, round: 3, team: 'Dallas Stars', player: 'Cameron Schmidt', position: 'RW', league: 'Vancouver Giants (WHL)', nationality: 'CAN' },
  { pick: 95, round: 3, team: 'San Jose Sharks (from EDM)', player: 'Teddy Mutryn', position: 'C', league: 'Chicago Steel (USHL)', nationality: 'USA' },
  { pick: 96, round: 3, team: 'Washington Capitals (from FLA via OTT)', player: 'Maxim Schafer', position: 'LW', league: 'Eisbaren Berlin (DEL)', nationality: 'GER' },
  { pick: 97, round: 4, team: 'Ottawa Senators (from SJ)', player: 'Lucas Beckman', position: 'G', league: 'Baie-Comeau Drakkar (QMJHL)', nationality: 'CAN' },
  { pick: 98, round: 4, team: 'Chicago Blackhawks', player: 'Julius Sumpf', position: 'C', league: 'Moncton Wildcats (QMJHL)', nationality: 'GER' },
  { pick: 99, round: 4, team: 'New Jersey Devils (from NSH)', player: 'Trenten Bennett', position: 'G', league: 'Kemptville 73\'s (CCHL)', nationality: 'CAN' },
  { pick: 100, round: 4, team: 'Boston Bruins (from PHI via TOR)', player: 'Vashek Blanar', position: 'D', league: 'IF Troja-Ljungby (Sweden-Jr.)', nationality: 'USA' },
  { pick: 101, round: 4, team: 'Anaheim Ducks (from BOS via DET)', player: 'Drew Schock', position: 'D', league: 'U.S. NTDP (USHL)', nationality: 'USA' },
  { pick: 102, round: 4, team: 'Minnesota Wild (from SEA)', player: 'Adam Benak', position: 'C', league: 'Youngstown Phantoms (USHL)', nationality: 'CZE' },
  { pick: 103, round: 4, team: 'Buffalo Sabres', player: 'Matous Kucharcik', position: 'C', league: 'HC Slavia Praha U20 (Czechia U20)', nationality: 'ITA' },
  { pick: 104, round: 4, team: 'Anaheim Ducks (from ANA)', player: 'Elijah Neuenschwander', position: 'G', league: 'HC Fribourg-Gotteron U20 (Swiss-Jr.)', nationality: 'SUI' },
  { pick: 105, round: 4, team: 'Pittsburgh Penguins', player: 'Travis Hayes', position: 'RW', league: 'Sault Ste. Marie Greyhounds (OHL)', nationality: 'USA' },
  { pick: 106, round: 4, team: 'New York Islanders', player: 'Tomas Poletin', position: 'LW', league: 'Lahti Pelicans (Liiga)', nationality: 'CZE' },
  { pick: 107, round: 4, team: 'Chicago Blackhawks (from NYR)', player: 'Parker Holmes', position: 'LW', league: 'Brantford Bulldogs (OHL)', nationality: 'CAN' },
  { pick: 108, round: 4, team: 'Tampa Bay Lightning (from DET)', player: 'Benjamin Rautiainen', position: 'C', league: 'Tappara (Liiga)', nationality: 'FIN' },
  { pick: 109, round: 4, team: 'Detroit Red Wings (from CBJ)', player: 'Brent Solomon', position: 'RW', league: 'Champlin Park (USHS-MN)', nationality: 'USA' },
  { pick: 110, round: 4, team: 'Utah Hockey Club', player: 'Yegor Borikov', position: 'RW', league: 'Dinamo Minsk (KHL)', nationality: 'BLR' },
  { pick: 111, round: 4, team: 'New York Rangers (from VAN)', player: 'Mikkel Eriksen', position: 'C', league: 'Farjestad BK J20 (J20 Nationell)', nationality: 'NOR' },
  { pick: 112, round: 4, team: 'Florida Panthers (from CGY)', player: 'Mads Kongsbak Klyvo', position: 'LW', league: 'Frolunda HC J20 (J20 Nationell)', nationality: 'DEN' },
  { pick: 113, round: 4, team: 'Montreal Canadiens', player: 'L.J. Mooney', position: 'C', league: 'U.S. NTDP (USHL)', nationality: 'USA' },
  { pick: 114, round: 4, team: 'New Jersey Devils', player: 'Gustav Hillstrom', position: 'C', league: 'Brynas IF (SHL)', nationality: 'SWE' },
  { pick: 115, round: 4, team: 'San Jose Sharks (from STL)', player: 'Ilyas Magomedsultanov', position: 'D', league: 'Lokomotiv Yaroslavl (KHL)', nationality: 'RUS' },
  { pick: 116, round: 4, team: 'Buffalo Sabres (from MIN)', player: 'Samuel Meloche', position: 'G', league: 'Rouyn-Noranda Huskies (QMJHL)', nationality: 'CAN' },
  { pick: 117, round: 4, team: 'Edmonton Oilers (from OTT)', player: 'David Lewandowski', position: 'LW', league: 'Saskatoon Blades (WHL)', nationality: 'GER' },
  { pick: 118, round: 4, team: 'Colorado Avalanche', player: 'Linus Funck', position: 'D', league: 'Lulea HF J20 (J20 Nationell)', nationality: 'SWE' },
  { pick: 119, round: 4, team: 'Detroit Red Wings (from TB)', player: 'Michal Svrcek', position: 'LW', league: 'Brynas IF (SHL)', nationality: 'SVK' },
  { pick: 120, round: 4, team: 'Los Angeles Kings', player: 'Caeden Herrington', position: 'D', league: 'Lincoln Stars (USHL)', nationality: 'USA' },
  { pick: 121, round: 4, team: 'Minnesota Wild (from TOR)', player: 'Lirim Amidovski', position: 'RW', league: 'North Bay Battalion (OHL)', nationality: 'CAN' },
  { pick: 122, round: 4, team: 'Nashville Predators (from VGK)', player: 'Alex Huang', position: 'D', league: 'Chicoutimi Sagueneens (QMJHL)', nationality: 'CAN' },
  { pick: 123, round: 4, team: 'Minnesota Wild (from WSH)', player: 'Carter Klippenstein', position: 'C', league: 'Brandon Wheat Kings (WHL)', nationality: 'CAN' },
  { pick: 124, round: 4, team: 'San Jose Sharks (from WPG)', player: 'Zachary Sharp', position: 'D', league: 'Western Michigan Broncos (NCHC)', nationality: 'USA' },
  { pick: 125, round: 4, team: 'Los Angeles Kings (from CAR)', player: 'Jimmy Lombardi', position: 'C', league: 'Flint Firebirds (OHL)', nationality: 'CAN' },
  { pick: 126, round: 4, team: 'Dallas Stars (from NYR)', player: 'Brandon Gorzynski', position: 'C', league: 'Calgary Hitmen (WHL)', nationality: 'USA' },
  { pick: 127, round: 4, team: 'Tampa Bay Lightning (from EDM)', player: 'Aiden Foster', position: 'C', league: 'Prince George Cougars (WHL)', nationality: 'CAN' },
  { pick: 128, round: 4, team: 'Florida Panthers', player: 'Shea Busch', position: 'LW', league: 'Everett Silvertips (WHL)', nationality: 'CAN' },
  { pick: 129, round: 5, team: 'Florida Panthers (from SJ)', player: 'Shamar Moses', position: 'RW', league: 'North Bay Battalion (OHL)', nationality: 'CAN' },
  { pick: 130, round: 5, team: 'Pittsburgh Penguins (from CHI)', player: 'Ryan Miller', position: 'C', league: 'Portland Winterhawks (WHL)', nationality: 'CAN' },
  { pick: 131, round: 5, team: 'Edmonton Oilers (from NSH)', player: 'Asher Barnett', position: 'D', league: 'U.S. NTDP (USHL)', nationality: 'USA' },
  { pick: 132, round: 5, team: 'Philadelphia Flyers', player: 'Max Westergard', position: 'LW', league: 'Frolunda HC J20 (J20 Nationell)', nationality: 'FIN' },
  { pick: 133, round: 5, team: 'Boston Bruins', player: 'Cole Chandler', position: 'C', league: 'Shawinigan Cataractes (QMJHL)', nationality: 'CAN' },
  { pick: 134, round: 5, team: 'Seattle Kraken', player: 'Maxim Agafonov', position: 'D', league: 'Ufa Jr. (MHL)', nationality: 'RUS' },
  { pick: 135, round: 5, team: 'Buffalo Sabres', player: 'Noah Laberge', position: 'D', league: 'Acadie-Bathurst Titan (QMJHL)', nationality: 'CAN' },
  { pick: 136, round: 5, team: 'Anaheim Ducks', player: 'Alexis Mathieu', position: 'D', league: 'Baie-Comeau Drakkar (QMJHL)', nationality: 'CAN' },
  { pick: 137, round: 5, team: 'Toronto Maple Leafs (from PIT)', player: 'William Belle', position: 'RW', league: 'U.S. NTDP (USHL)', nationality: 'CHN' },
  { pick: 138, round: 5, team: 'New York Islanders', player: 'Sam Laurila', position: 'D', league: 'Fargo Force (USHL)', nationality: 'USA' },
  { pick: 139, round: 5, team: 'New York Rangers', player: 'Zeb Lindgren', position: 'D', league: 'Skelleftea AIK J20 (J20 Nationell)', nationality: 'SWE' },
  { pick: 140, round: 5, team: 'Detroit Red Wings', player: 'Nikita Tyurin', position: 'D', league: 'Spartak Jr. (MHL)', nationality: 'RUS' },
  { pick: 141, round: 5, team: 'Minnesota Wild (from CBJ)', player: 'Justin Kipkie', position: 'D', league: 'Victoria Royals (WHL)', nationality: 'CAN' },
  { pick: 142, round: 5, team: 'Utah Hockey Club', player: 'Ivan Tkach-Tkachenko', position: 'G', league: 'Ufa Jr. (MHL)', nationality: 'RUS' },
  { pick: 143, round: 5, team: 'Vancouver Canucks', player: 'Wilson Bjorck', position: 'C', league: 'Djurgardens IF J20 (J20 Nationell)', nationality: 'SWE' },
  { pick: 144, round: 5, team: 'Calgary Flames', player: 'Ethan Wyttenbach', position: 'LW', league: 'Sioux Falls Stampede (USHL)', nationality: 'USA' },
  { pick: 145, round: 5, team: 'Montreal Canadiens', player: 'Alexis Cournoyer', position: 'G', league: 'Cape Breton Screaming Eagles (QMJHL)', nationality: 'CAN' },
  { pick: 146, round: 5, team: 'Dallas Stars (from NJD)', player: 'Atte Joki', position: 'C', league: 'Lukko Jr. (Finland-Jr.)', nationality: 'FIN' },
  { pick: 147, round: 5, team: 'St. Louis Blues', player: 'Mikhail Fyodorov', position: 'RW', league: 'Magnitogorsk Jr. (MHL)', nationality: 'RUS' },
  { pick: 148, round: 5, team: 'Pittsburgh Penguins (from MIN)', player: 'Quinn Beauchesne', position: 'D', league: 'Guelph Storm (OHL)', nationality: 'CAN' },
  { pick: 149, round: 5, team: 'Ottawa Senators', player: 'Dmitri Isayev', position: 'LW', league: 'Yekaterinburg Jr. (MHL)', nationality: 'RUS' },
  { pick: 150, round: 5, team: 'San Jose Sharks (from COL)', player: 'Max Heise', position: 'C', league: 'Penticton Vees (BCHL)', nationality: 'CAN' },
  { pick: 151, round: 5, team: 'Tampa Bay Lightning', player: 'Everett Baldwin', position: 'D', league: 'St. George\'s School (High-RI)', nationality: 'USA' },
  { pick: 152, round: 5, team: 'Los Angeles Kings', player: 'Petteri Rimpinen', position: 'G', league: 'K-Espoo (Finland)', nationality: 'FIN' },
  { pick: 153, round: 5, team: 'Toronto Maple Leafs', player: 'Harry Nansi', position: 'RW', league: 'Owen Sound Attack (OHL)', nationality: 'CAN' },
  { pick: 154, round: 5, team: 'Pittsburgh Penguins', player: 'Jordan Charron', position: 'RW', league: 'Sault Ste. Marie Greyhounds (OHL)', nationality: 'CAN' },
  { pick: 155, round: 5, team: 'Washington Capitals', player: 'Jackson Crowder', position: 'C', league: 'Chicago Steel (USHL)', nationality: 'USA' },
  { pick: 156, round: 5, team: 'Winnipeg Jets', player: 'Viktor Klingsell', position: 'RW', league: 'Skelleftea AIK J20 (J20 Nationell)', nationality: 'SWE' },
  { pick: 157, round: 5, team: 'Philadelphia Flyers (from CAR)', player: 'Luke Vlooswyk', position: 'D', league: 'Red Deer Rebels (WHL)', nationality: 'CAN' },
  { pick: 158, round: 5, team: 'Dallas Stars', player: 'Mans Goos', position: 'G', league: 'Farjestad BK J20 (J20 Nationell)', nationality: 'SWE' },
  { pick: 159, round: 5, team: 'Anaheim Ducks (from EDM)', player: 'Emile Guite', position: 'LW', league: 'Chicoutimi Sagueneens (QMJHL)', nationality: 'CAN' },
  { pick: 160, round: 5, team: 'Columbus Blue Jackets', player: 'Owen Griffin', position: 'C', league: 'Oshawa Generals (OHL)', nationality: 'CAN' },
  { pick: 161, round: 6, team: 'New Jersey Devils', player: 'David Rozsival', position: 'RW', league: 'Liberec Jr. (Czech-Jr.)', nationality: 'CZE' },
  { pick: 162, round: 6, team: 'Chicago Blackhawks', player: 'Ashton Cumby', position: 'D', league: 'Seattle Thunderbirds (WHL)', nationality: 'CAN' },
  { pick: 163, round: 6, team: 'Nashville Predators', player: 'Daniel Nieminen', position: 'D', league: 'Lahti Pelicans (Finland)', nationality: 'FIN' },
  { pick: 164, round: 6, team: 'Philadelphia Flyers', player: 'Nathan Quinn', position: 'C', league: 'Quebec Remparts (QMJHL)', nationality: 'CAN' },
  { pick: 165, round: 6, team: 'Boston Bruins', player: 'Kirill Yemelyanov', position: 'C', league: 'Yaroslavl Jr. (MHL)', nationality: 'RUS' },
  { pick: 166, round: 6, team: 'New York Rangers', player: 'Samuel Jung', position: 'RW', league: 'Karpat Jr. (Finland-Jr.)', nationality: 'CZE' },
  { pick: 167, round: 6, team: 'Buffalo Sabres', player: 'Ashton Schultz', position: 'C', league: 'Chicago Steel (USHL)', nationality: 'USA' },
  { pick: 168, round: 6, team: 'Anaheim Ducks', player: 'Anthony Allain-Samake', position: 'D', league: 'Sioux City Musketeers (USHL)', nationality: 'CAN' },
  { pick: 169, round: 6, team: 'Pittsburgh Penguins', player: 'Carter Sanderson', position: 'LW', league: 'Muskegon Lumberjacks (USHL)', nationality: 'USA' },
  { pick: 170, round: 6, team: 'New York Islanders', player: 'Burke Hood', position: 'G', league: 'Vancouver Giants (WHL)', nationality: 'CAN' },
  { pick: 171, round: 6, team: 'New York Rangers', player: 'Evan Passmore', position: 'D', league: 'Barrie Colts (OHL)', nationality: 'CAN' },
  { pick: 172, round: 6, team: 'Detroit Red Wings', player: 'Will Murphy', position: 'D', league: 'Cape Breton Screaming Eagles (QMJHL)', nationality: 'CAN' },
  { pick: 173, round: 6, team: 'Columbus Blue Jackets', player: 'Victor Raftheim', position: 'D', league: 'Brynas IF Jr. (Sweden-Jr.)', nationality: 'SWE' },
  { pick: 174, round: 6, team: 'Utah Hockey Club', player: 'Ludvig Johnson', position: 'D', league: 'EV Zug (Swiss)', nationality: 'SUI' },
  { pick: 175, round: 6, team: 'Vancouver Canucks', player: 'Gabriel Chiarot', position: 'RW', league: 'Brampton Steelheads (OHL)', nationality: 'CAN' },
  { pick: 176, round: 6, team: 'Calgary Flames', player: 'Aiden Lane', position: 'RW', league: 'St. Andrew\'s College (HIGH-ON)', nationality: 'CAN' },
  { pick: 177, round: 6, team: 'Montreal Canadiens', player: 'Carlos Handel', position: 'D', league: 'Halifax Mooseheads (QMJHL)', nationality: 'GER' },
  { pick: 178, round: 6, team: 'New Jersey Devils', player: 'Sigge Holmgren', position: 'D', league: 'Brynas IF U18 (Sweden-Jr.)', nationality: 'SWE' },
  { pick: 179, round: 6, team: 'St. Louis Blues', player: 'Love Harenstam', position: 'G', league: 'Skelleftea AIK Jr. (Sweden-Jr.)', nationality: 'SWE' },
  { pick: 180, round: 6, team: 'Washington Capitals', player: 'Aron Dahlqvist', position: 'D', league: 'Brynas IF Jr. (Sweden-Jr.)', nationality: 'SWE' },
  { pick: 181, round: 6, team: 'Ottawa Senators', player: 'Bruno Idzan', position: 'LW', league: 'Lincoln Stars (USHL)', nationality: 'CRO' },
  { pick: 182, round: 6, team: 'Utah Hockey Club', player: 'Reko Alanko', position: 'D', league: 'Jokerit Jr. (Finland-Jr.)', nationality: 'FIN' },
  { pick: 183, round: 6, team: 'Carolina Hurricanes', player: 'Viggo Nordlund', position: 'LW', league: 'Skelleftea AIK Jr. (Sweden-Jr.)', nationality: 'SWE' },
  { pick: 184, round: 6, team: 'Los Angeles Kings', player: 'Jan Chovan', position: 'C', league: 'Tappara Jr. (Finland-Jr.)', nationality: 'SVK' },
  { pick: 185, round: 6, team: 'Toronto Maple Leafs', player: 'Rylan Fellinger', position: 'D', league: 'Flint Firebirds (OHL)', nationality: 'CAN' },
  { pick: 186, round: 6, team: 'Vegas Golden Knights', player: 'Alexander Weiermair', position: 'C', league: 'Portland Winterhawks (WHL)', nationality: 'USA' },
  { pick: 187, round: 6, team: 'Vegas Golden Knights', player: 'Gustav Sjoqvist', position: 'D', league: 'AIK (Sweden-2)', nationality: 'SWE' },
  { pick: 188, round: 6, team: 'Winnipeg Jets', player: 'Edison Engle', position: 'D', league: 'Dubuque Fighting Saints (USHL)', nationality: 'USA' },
  { pick: 189, round: 6, team: 'Montreal Canadiens', player: 'Andrew MacNiel', position: 'D', league: 'Kitchener Rangers (OHL)', nationality: 'CAN' },
  { pick: 190, round: 6, team: 'Dallas Stars', player: 'Dawson Sharkey', position: 'RW', league: 'Acadie-Bathurst Titan (QMJHL)', nationality: 'CAN' },
  { pick: 191, round: 6, team: 'Edmonton Oilers', player: 'Daniel Salonen', position: 'G', league: 'Lukko Jr. (Finland-Jr.)', nationality: 'FIN' },
  { pick: 192, round: 6, team: 'Florida Panthers', player: 'Arvid Drott', position: 'RW', league: 'Djurgardens IF Jr. (Sweden-Jr.)', nationality: 'SWE' },
  { pick: 193, round: 7, team: 'Tampa Bay Lightning (from SJ)', player: 'Caleb Heil', position: 'G', league: 'Madison Capitols (USHL)', nationality: 'USA' },
  { pick: 194, round: 7, team: 'Chicago Blackhawks', player: 'Ilya Kanarsky', position: 'G', league: 'Akm Tula Jr. (Russia-Jr.)', nationality: 'RUS' },
  { pick: 195, round: 7, team: 'Buffalo Sabres (from NSH)', player: 'Melvin Novotny', position: 'LW', league: 'Leksands IF Jr. (Sweden-Jr.)', nationality: 'SWE' },
  { pick: 196, round: 7, team: 'Los Angeles Kings (from PHI)', player: 'Brendan McMorrow', position: 'C', league: 'Waterloo Black Hawks (USHL)', nationality: 'USA' },
  { pick: 197, round: 7, team: 'Florida Panthers (from BOS via CHI)', player: 'Brendan Dunphy', position: 'D', league: 'Wenatchee Wild (WHL)', nationality: 'USA' },
  { pick: 198, round: 7, team: 'Columbus Blue Jackets', player: 'Jeremy Loranger', position: 'C', league: 'Sherwood Park Crusaders (BCHL)', nationality: 'CAN' },
  { pick: 199, round: 7, team: 'Buffalo Sabres', player: 'Yevgeni Prokhorov', position: 'G', league: 'Dinamo-Shinnik Jr. (Russia-Jr.)', nationality: 'BLR' },
  { pick: 200, round: 7, team: 'Anaheim Ducks', player: 'Brady Turko', position: 'RW', league: 'Brandon Wheat Kings (WHL)', nationality: 'CAN' },
  { pick: 201, round: 7, team: 'Pittsburgh Penguins', player: 'Kale Dach', position: 'C', league: 'Sherwood Park Crusaders (BCHL)', nationality: 'CAN' },
  { pick: 202, round: 7, team: 'New York Islanders', player: 'Jacob Kvasnicka', position: 'RW', league: 'U.S. NTDP (USHL)', nationality: 'USA' },
  { pick: 203, round: 7, team: 'New York Rangers', player: 'Felix Farhammar', position: 'D', league: 'Orebro HK Jr. (Sweden-Jr.)', nationality: 'SWE' },
  { pick: 204, round: 7, team: 'Detroit Red Wings', player: 'Grayden Robertson-Palmer', position: 'C', league: 'Phillips Andover Academy (High-MA)', nationality: 'CAN' },
  { pick: 205, round: 7, team: 'Seattle Kraken (from Columbus)', player: 'Karl Annborn', position: 'D', league: 'HV71 (SHL)', nationality: 'SWE' },
  { pick: 206, round: 7, team: 'Tampa Bay Lightning (from Utah)', player: 'Roman Luttsev', position: 'C', league: 'Loko Yaroslavl (KHL)', nationality: 'RUS' },
  { pick: 207, round: 7, team: 'Vancouver Canucks', player: 'Matthew Lansing', position: 'C', league: 'Fargo Force (USHL)', nationality: 'USA' },
  { pick: 208, round: 7, team: 'Calgary Flames', player: 'Jakob Leander', position: 'D', league: 'HV71 Jr. (Sweden-Jr.)', nationality: 'SWE' },
  { pick: 209, round: 7, team: 'Montreal Canadiens', player: 'Maxon Vig', position: 'D', league: 'Cedar Rapids RoughRiders (USHL)', nationality: 'USA' },
  { pick: 210, round: 7, team: 'San Jose Sharks (from NJD)', player: 'Richard Gallant', position: 'LW', league: 'U.S. NTDP (USHL)', nationality: 'USA' },
  { pick: 211, round: 7, team: 'Calgary Flames (from STL via DET)', player: 'Yan Matveiko', position: 'LW', league: 'Krasnaya Armiya Moskva (MHL)', nationality: 'RUS' },
  { pick: 212, round: 7, team: 'Tampa Bay Lightning (from MIN)', player: 'Grant Spada', position: 'D', league: 'Guelph Storm (OHL)', nationality: 'CAN' },
  { pick: 213, round: 7, team: 'Ottawa Senators', player: 'Andrei Trofimov', position: 'G', league: 'Magnitogorsk Jr. (MHL)', nationality: 'RUS' },
  { pick: 214, round: 7, team: 'Colorado Avalanche', player: 'Nolan Roed', position: 'C', league: 'Tri-City Storm (USHL)', nationality: 'USA' },
  { pick: 215, round: 7, team: 'Tampa Bay Lightning', player: 'Marco Mignosa', position: 'RW', league: 'Sault Ste. Marie Greyhounds (OHL)', nationality: 'CAN' },
  { pick: 216, round: 7, team: 'Los Angeles Kings', player: 'William Sharpe', position: 'D', league: 'Kelowna Rockets (WHL)', nationality: 'CAN' },
  { pick: 217, round: 7, team: 'Toronto Maple Leafs', player: 'Matthew Hlacar', position: 'LW', league: 'Kitchener Rangers (OHL)', nationality: 'CAN' },
  { pick: 218, round: 7, team: 'Seattle Kraken (from VGK via CBJ)', player: 'Loke Krantz', position: 'RW', league: 'Linkoping HC J20 (J20 Nationell)', nationality: 'SWE' },
  { pick: 219, round: 7, team: 'Buffalo Sabres (from WSH via SJ)', player: 'Ryan Rucinski', position: 'C', league: 'Youngstown Phantoms (USHL)', nationality: 'USA' },
  { pick: 220, round: 7, team: 'Winnipeg Jets', player: 'Jacob Cloutier', position: 'RW', league: 'Saginaw Spirit (OHL)', nationality: 'CAN' },
  { pick: 221, round: 7, team: 'Carolina Hurricanes', player: 'Filip Ekberg', position: 'RW', league: 'Ottawa 67\'s (OHL)', nationality: 'SWE' },
  { pick: 222, round: 7, team: 'Dallas Stars', player: 'Charlie Paquette', position: 'RW', league: 'Guelph Storm (OHL)', nationality: 'CAN' },
  { pick: 223, round: 7, team: 'Edmonton Oilers', player: 'Aidan Park', position: 'C', league: 'Green Bay Gamblers (USHL)', nationality: 'USA' },
  { pick: 224, round: 7, team: 'Florida Panthers (from BOS via CHI)', player: 'Yegor Midlak', position: 'G', league: 'JHC Spartak (MHL)', nationality: 'RUS' }
];

// Draft statistics (computed from PICKS_2025)
export const DRAFT_2025_STATS: PickStats = {
  totalPicks: 224,
  realPicks: 224,
  forfeits: 0,
  uniqueTeams: 33,
  rounds: 7,
  nationalities: 17,
  leagues: 140,
};
